### ISSUE TITLE
 torch2的 mmcv-full安装不了，一直卡在Building wheel for mmcv-full (setup.py) ... /

### ISSUE THREAD

**Issue by chuan19** [modelscope/facechain#10]
mim install mmcv-full==1.7.0
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Looking in links: https://download.openmmlab.com/mmcv/dist/cu117/torch2.0.0/index.html
Collecting mmcv-full==1.7.0
  Downloading http://mirrors.aliyun.com/pypi/packages/a1/81/89120850923f4c8b49efba81af30160e7b1b305fdfa9671a661705a8abbf/mmcv-full-1.7.0.tar.gz (593 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 593.6/593.6 kB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from mmcv-full==1.7.0) (2.4.0)
Requirement already satisfied: numpy in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from mmcv-full==1.7.0) (1.22.0)
Requirement already satisfied: packaging in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from mmcv-full==1.7.0) (23.1)
Requirement already satisfied: Pillow in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from mmcv-full==1.7.0) (10.0.0)
Requirement already satisfied: pyyaml in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from mmcv-full==1.7.0) (6.0.1)
Requirement already satisfied: yapf in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from mmcv-full==1.7.0) (0.40.1)
Requirement already satisfied: importlib-metadata>=6.6.0 in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from yapf->mmcv-full==1.7.0) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from yapf->mmcv-full==1.7.0) (3.10.0)
Requirement already satisfied: tomli>=2.0.1 in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from yapf->mmcv-full==1.7.0) (2.0.1)
Requirement already satisfied: zipp>=0.5 in /root/autodl-tmp/conda/envs/facechain/lib/python3.10/site-packages (from importlib-metadata>=6.6.0->yapf->mmcv-full==1.7.0) (3.16.2)
Building wheels for collected packages: mmcv-full
  Building wheel for mmcv-full (setup.py) ... /

**Comment by tastelikefeet** [comment]
这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些

**Comment by chuan19** [comment]
> 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些



> 



> 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些

他官方：https://mmcv.readthedocs.io/zh_CN/1.x/get_started/installation.html#mmcv-full
最高只支持torch1版本
根据系统的类型、CUDA 版本、PyTorch 版本以及 MMCV 版本选择相应的安装命令
Linux
cuda 11.7
torch 1.13.x
mmcv 1.7.0
pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html

**Comment by yingdachen** [comment]
> > 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些
> 
> > 
> 
> > 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些
> 
> 他官方：https://mmcv.readthedocs.io/zh_CN/1.x/get_started/installation.html#mmcv-full 最高只支持torch1版本 根据系统的类型、CUDA 版本、PyTorch 版本以及 MMCV 版本选择相应的安装命令 Linux cuda 11.7 torch 1.13.x mmcv 1.7.0 pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html

你如果选择其他cuda版本，是可以支持torch2.x的。
![image](https://github.com/modelscope/facechain/assets/5042027/4740050f-feeb-492a-b2fc-2b782b06d8cd)

**Comment by RyanzW0521** [comment]
> > > 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些
> > 
> > 
> > > 
> > 
> > 
> > > 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些
> > 
> > 
> > 他官方：https://mmcv.readthedocs.io/zh_CN/1.x/get_started/installation.html#mmcv-full 最高只支持torch1版本 根据系统的类型、CUDA 版本、PyTorch 版本以及 MMCV 版本选择相应的安装命令 Linux cuda 11.7 torch 1.13.x mmcv 1.7.0 pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13/index.html
> 
> 你如果选择其他cuda版本，是可以支持torch2.x的。 ![image](https://user-images.githubusercontent.com/5042027/260363520-4740050f-feeb-492a-b2fc-2b782b06d8cd.png)

但是modelscope库里的很多函数和功能看上去都是基于mmcv<2.0.0编写的，需要修改海量的地方

**Comment by wangzhaolei** [comment]
> 这个库安装会有点慢，大概要20分钟到40分钟不等，我们会给mmcv社区提交对应的issue，希望安装能够快一些 另外，您可以查看这个：[open-mmlab/mmcv#1386](https://github.com/open-mmlab/mmcv/issues/1386) 选择对应cuda版本的预编译mmcv-full进行安装，会快很多

可以的，我就等了40分钟

**Comment by mengchao-git** [comment]
只是很慢，我等了30多分钟就装上了

**Comment by RyanzW0521** [comment]
您的邮件我已收到，辛苦！

**Comment by jienhui9407** [comment]
垃圾库，不知道存在的意义是什么，人力过剩？

**Comment by RyanzW0521** [comment]
您的邮件我已收到，辛苦！

**Comment by Dystopians** [comment]
这个库是真难绷，安装到半小时左右报错又重新装，感觉整个人都老了五岁

**Comment by RyanzW0521** [comment]
您的邮件我已收到，辛苦！

**Comment by Murasame2333** [comment]
逆天库
