### ISSUE TITLE
other style lora inference questions

### ISSUE THREAD

**Issue by Number18-tong** [modelscope/facechain#100]
I try to use other lora models (such as bellows) in civitai to generate results
![企业微信截图_16927778176156](https://github.com/modelscope/facechain/assets/52230160/237f2858-ac2b-42f4-a93e-f739e43d53a3)
I find that there are several black images in the 10 images after sd (I only merge the style lora, and I tried different lora models , and also many different multiplier_style numbers). How to fix this problem? THANKs VERY MUCH!
![企业微信截图_16927783321212](https://github.com/modelscope/facechain/assets/52230160/e7c4115d-4778-4d59-9aee-cfa8353f8884)

**Comment by sunbaigui** [comment]
if you are interested in more other style lora, welcome to join our interest group for more information. https://www.yuque.com/forms/share/5892d145-99c3-406c-8785-13dcb50353b8 .
