### ISSUE TITLE
"妙鸭"有一个参考的写真模板，但是这个好像没有写真模板输入？

### ISSUE THREAD

**Issue by dragen1860** [modelscope/facechain#102]
"妙鸭"有一个参考的写真模板，但是这个好像没有写真模板输入？这个好像只有给定人脸，和Style LORA, 和妙鸭的写真模板应该还是不一样吧，写真模板定死了背景和衣服，但是这个Style LORA好像只是一种简单的风格指定？谢谢。

**Comment by jiqizaisikao** [comment]
![WechatIMG55](https://github.com/modelscope/facechain/assets/16893734/e6ed673f-9f50-441f-9bbc-f6e4d17c3d34)
![WechatIMG54](https://github.com/modelscope/facechain/assets/16893734/0d038cd6-03a6-4351-898d-3739567db5d7)
这是我最新的WX 小程序《换影CP》 一键换头 换脸型 用一张照片作为参考 类似于Adobe的生成填充 希望可以找到合作伙伴共同开发和研究 这个需要自己训练我可能没有那么多资源再训练了
