### ISSUE TITLE
可以支持多GPU训练推理吗

### ISSUE THREAD

**Issue by Nomination-NRB** [modelscope/facechain#107]
你好，我想问一下现在版本可以支持多GPU训练推理吗，因为单独使用一张卡显存吃的很满，另一张又是空闲的

**Comment by dragen1860** [comment]
> 

这个问题和这个仓库关系不大了，需要你将算法拆解开，模型放在2张显卡上跑。但是这里核心的是LDM，LDM主要是在循环迭代耗时上面，放在多卡上的意义不大。

**Comment by Nomination-NRB** [comment]
> > 
> 
> 这个问题和这个仓库关系不大了，需要你将算法拆解开，模型放在2张显卡上跑。但是这里核心的是LDM，LDM主要是在循环迭代耗时上面，放在多卡上的意义不大。

哦哦好的，感谢你的回复！
