### ISSUE TITLE
人脸性别识别问题，男生总会被识别成女生?

### ISSUE THREAD

**Issue by wangyong860401** [modelscope/facechain#108]
fair_face_attribute_func 同一个有些图片识别成女生，有些是男生，用https://vision.aliyun.com/experience/detail?tagName=facebody&children=RecognizeFace&spm=a2cio.27993362返回都比较正常，有没有其他的改进或替代方案呢

**Comment by sunbaigui** [comment]
收到。这个开源模型可能不太稳定，后续有稳定的可以更新上去，我们需要找到稳定可用的开源模型，如找到合适的，欢迎上来贡献代码或者模型哈。
