### ISSUE TITLE
什么时候可以提供api接口

### ISSUE THREAD

**Issue by feixueck** [modelscope/facechain#111]
希望能早日提供相应的api接口 , 各类场景的二次开发就爽了 .

**Comment by sunbaigui** [comment]
看起来是新feature的需求，我们先close掉这个issue了哈，感谢提供建议。我们近期会去思考下如何构建。

**Comment by sunbaigui** [comment]
merged to #314

**Comment by sunbaigui** [comment]
@feixueck 请查看问题 #314 ，目前已支持API接口。
