### ISSUE TITLE
Error Expecting value: line 1 column 1 (char 0) occur when start taining

### ISSUE THREAD

**Issue by DancingFox** [modelscope/facechain#112]
Error Expecting value: line 1 column 1 (char 0) occur when start taining

![image](https://github.com/modelscope/facechain/assets/6283792/fa7178cc-ca41-4fe5-8324-e15aff9a0a83)

**Comment by sunbaigui** [comment]
please supply a screenshot of log and which system you are using.

**Comment by DancingFox** [comment]
> please supply a screenshot of log and which system you are using.

base window10 use conda virtual environment 

sys.platform: win32
Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 4090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32822 版
GCC: n/a
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.2+cpu
OpenCV: 4.8.0
MMCV: 1.7.0
MMCV Compiler: MSVC 193732822
MMCV CUDA Compiler: 11.7
MMDetection: 2.26.0+e224989

**Comment by ultimatech-cn** [comment]
Please provide more detail message on the command terminal.

**Comment by DancingFox** [comment]
> Please provide more detail message on the command terminal.

nothting print on the Anaconda Prompt window

**Comment by ultimatech-cn** [comment]
try following steps：
1. pip upgrade gradio
2. close VPN or Firewall

**Comment by DancingFox** [comment]
> try following steps：
> 
> 1. pip upgrade gradio
> 2. close VPN or Firewall

both are checked ; 
the error occur after i pull new code from repo

**Comment by mnbvcxz8** [comment]
碰到了同样的问题

**Comment by GeneLiuXe** [comment]
Same problem

**Comment by DancingFox** [comment]
issue closed by lastest code updated
