### ISSUE TITLE
FileNotFoundError: ImageFaceFusionPipeline: ImageFaceFusion: [Errno 2] No such file or directory: '/home/ubuntu/.cache/modelscope/hub/damo/cv_unet-image-face-fusion_damo/faceEnhance/GPEN-BFR-1024.pth'

### ISSUE THREAD

**Issue by luoxianjun** [modelscope/facechain#115]
No such file or directory: '/home/ubuntu/.cache/modelscope/hub/damo/cv_unet-image-face-fusion_damo/faceEnhance/GPEN-BFR-1024.pth'

**Comment by FuNian788** [comment]
same bug

**Comment by sunbaigui** [comment]
@FuNian788 @luoxianjun can you gays delete the old repo or '/home/ubuntu/.cache/modelscope/, and then restart it to see if this problem can be solved by repo updating.

**Comment by FuNian788** [comment]
> 

I fixed the bug by directly downloading model in ModelScope, and I think your solution may help. PS gays may be guys :)

**Comment by longlongago** [comment]
I fix this bug by add the code below in the front of the  `run_inference.py` file

`from modelscope.hub.file_download import model_file_download`

`model_file_download('damo/cv_unet-image-face-fusion_damo', file_path='faceEnhance/GPEN-BFR-1024.pth')
`

**Comment by TechnicallyRobert** [comment]
@longlongago's comment finally allowed me to track down this file.

Here's a direct link:

https://www.modelscope.cn/models/iic/cv_unet-image-face-fusion_damo/file/view/master/faceEnhance%2FGPEN-BFR-1024.pth
