### ISSUE TITLE
can we use this on google colab?

### ISSUE THREAD

**Issue by sudip550** [modelscope/facechain#12]
please make colab version of this repo

**Comment by sunbaigui** [comment]
we'll discuss this asap.

**Comment by kcoderhtml** [comment]
Yes please that would be awesome!

**Comment by wangxingjun778** [comment]
> please make colab version of this repo

Try this colab notebook:  https://colab.research.google.com/drive/1cUhnVXseqD2EJiotZk3k7GsfQK9_yJu_?usp=sharing
