### ISSUE TITLE
Colab now work.

### ISSUE THREAD

**Issue by aetherwu** [modelscope/facechain#122]
os.chdir('/path/to/facechain') # Note: replace with your facechain root
os.chdir('/mnt/workspace/facechain')    # You may change to your own path

/content
python3: can't open file '/content/app.py': [Errno 2] No such file or directory

**Comment by yingdachen** [comment]
please follow the instrcution (comment), and ensure that you are executing app.py from the correct facechain directory

**Comment by aetherwu** [comment]
> please follow the instrcution (comment), and ensure that you are executing app.py from the correct facechain directory

It's coab notebook, so it runs in cloud, isn't it?

**Comment by yingdachen** [comment]
> > please follow the instrcution (comment), and ensure that you are executing app.py from the correct facechain directory
> 
> It's coab notebook, so it runs in cloud, isn't it?

it does. 

but even on the cloud colab creates a virtual envrionment for you, so the old-school concept of file and directory still applies

<img width="456" alt="image" src="https://github.com/modelscope/facechain/assets/5042027/1a46862d-9274-4ac3-be3f-90e6b19c4952">
