### ISSUE TITLE
When run facechain/inference.py,Loading model,but can't generate images,Why?What happened?

### ISSUE THREAD

**Issue by randompaga** [modelscope/facechain#126]
2023-08-27 21:41:36,136 - modelscope - INFO - Model revision not specified, use the latest revision: v2.0
2023-08-27 21:41:36,638 - modelscope - INFO - initiate model from ./models/damo/cv_manual_face-quality-assessment_fqa
2023-08-27 21:41:36,638 - modelscope - INFO - initiate model from location ./models/damo/cv_manual_face-quality-assessment_fqa.

**Comment by sunbaigui** [comment]
try regenerate, or retrain, or rebuild the latest facechain project.

**Comment by randompaga** [comment]
> try regenerate, or retrain, or rebuild the latest facechain project.

Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.

Please help!!  I just input prompt:a boy,then this happend.Don't allowed me to create images again.I tried many times,every time it said NSFW.Just a boy,why??

**Comment by ultimatech-cn** [comment]
Facechain generates images depending on the underlying SD (Stable Diffusion). After SD generating an image, Facechain assesses the image's quality. As I know, there are two situations where images are filtered out: NSFW content and when the face size is too large or too small (including cases where no face is detected), you can see the message on the console. If you're interested, you can debug the source code to see the generated images by SD."
