### ISSUE TITLE
关于结果图生成，目前跑出的图片的发型都是中分或者偏分(女)

### ISSUE THREAD

**Issue by Nomination-NRB** [modelscope/facechain#131]
你好，请问如何控制保留原图的发型或者不进行修改呢

我查看过facechain/facechain/constants
发现prompt没有和发型有关的，如果需要保持原发型，需要直接加入对应prompt吗

**Comment by sunbaigui** [comment]
这块有发型描述的支持。本周会commit一些示例，教大家如何实现多样性的发型。

**Comment by Nomination-NRB** [comment]
> 这块有发型描述的支持。本周会commit一些示例，教大家如何实现多样性的发型。

好的，感谢回复！
