### ISSUE TITLE
Missing config.json for pose-v1.1-with-depth

### ISSUE THREAD

**Issue by GefeiSHEN** [modelscope/facechain#132]
The latest pr merged support for controlnet, running pose-v1.1 works fine. However, running pose-v1.1-with-depth throws error:
`lllyasviel/control_v11p_sd15_depth does not appear to have a file named config.json.`

Upon checking, it attempts to load config.json from the following url.
[https://huggingface.co/lllyasviel/control_v11p_sd15_depth/resolve/main/config.json](https://[huggingface.co/lllyasviel/control_v11p_sd15_depth/resolve/main/config.json)
The corresponding repo has moved to: [https://huggingface.co/lllyasviel/control_v11f1p_sd15_depth](https://huggingface.co/lllyasviel/control_v11f1p_sd15_depth) instead.

**Comment by sunbaigui** [comment]
Thanks. we'll work on it for stable file access. we'll solve it today or tomorrow.

**Comment by sunbaigui** [comment]
Fixed. please try it agian. If it's still a problem in your case, feel free to reopen it.
