### ISSUE TITLE
RuntimeError about TensorFlow version when run Colab

### ISSUE THREAD

**Issue by yaduns** [modelscope/facechain#133]
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
This version of TensorFlow Probability requires TensorFlow version >= 2.12; Detected an installation of version 2.8.0. Please upgrade TensorFlow to proceed.

But if I upgrade TensorFlow other errors occurred.

**Comment by sunbaigui** [comment]
please pull the latest master, we've deleted tensorflow.

**Comment by sunbaigui** [comment]
> please pull the latest master, we've deleted tensorflow.

we find there's still one model remain needs tf, we'll solve it asap.

**Comment by sunbaigui** [comment]
pull the latest master, we've deleted tensorflow.
