### ISSUE TITLE
在modelscope社区开了GPU环境，但第二次速度非常慢而且一直在训练而没有结果

### ISSUE THREAD

**Issue by michael230811** [modelscope/facechain#134]
按照官方教程，登录并用支付宝扫码使用modelscope社区基于GPU环境的Notebook，第一次用盖尔加朵的照片训练，成功了。
但第二次我上传自己的照片（6张高清头肩照），一直在训练，过20分钟都没有训练完成。

请问这是因为什么原因？谢谢。

**Comment by michael230811** [comment]
额度还有29小时13分钟。所以应该不是额度不够的问题……

**Comment by ultimatech-cn** [comment]
我实测的结果facechain上传一张高质量的照片就行，因为它后台算法好像也会只找一张质量最好的来替换生成的照片。你可以看后台的日志输出，看看卡在那里了。

**Comment by sunbaigui** [comment]
感觉慢直接打断掉，传1~2张图试试即可，也能出很好的效果。
