### ISSUE TITLE
/tmp/qw/personalization_lora/文件夹下没有存储训练后的的lora权重pytorch_lora_weights.bin

### ISSUE THREAD

**Issue by wwwjiahuan** [modelscope/facechain#137]
本地服务器部署。训练之后切换到“形象体验”，报错“您还没有进行形象定制，请先进行训练。”。检查发现并没有存pytorch_lora_weights.bin。

**Comment by sunbaigui** [comment]
已经拉取了最新的代码了么，另外之前issue大家有讨论过这个问题，我先合并问题了哈。

**Comment by sunbaigui** [comment]
please refer to #46
