### ISSUE TITLE
如何更新base model 为sdxl？

### ISSUE THREAD

**Issue by wen020** [modelscope/facechain#138]
如何更新base model 为sdxl？

**Comment by sunbaigui** [comment]
有兴趣参与开发贡献，可以钉钉搜索“FaceChain开源VIP”群的钉钉群号： 30255027701，里面会有相应指导。搜索不到相关个人联系信息可以发到sunbaigui85@126.com。

**Comment by wen020** [comment]
申请了未通过

**Comment by yiqiedoushizuihaodeanpai** [comment]
so why this issue is closed?
