### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by luoxianjun** [modelscope/facechain#143]
<img width="680" alt="image" src="https://github.com/modelscope/facechain/assets/5306492/692e454d-03cd-41af-aa55-4389f16d235d">
Traceback (most recent call last):
  File "run_inference.py", line 53, in <module>
    outputs = gen_portrait(processed_dir, num_generate, base_model,
  File "/home/ubuntu/facechain/facechain/inference.py", line 475, in __call__
    swap_results = face_swap_fn(self.use_face_swap, gen_results, selected_face)
  File "/home/ubuntu/facechain/facechain/inference.py", line 399, in face_swap_fn
    for img in gen_results:
TypeError: 'NoneType' object is not iterable
执行python run_inference.py这个报的错

**Comment by luoxianjun** [comment]
<img width="1030" alt="image" src="https://github.com/modelscope/facechain/assets/5306492/34f49db7-ad8b-448a-8bf0-1e8638e9a668">

**Comment by luoxianjun** [comment]
<img width="942" alt="image" src="https://github.com/modelscope/facechain/assets/5306492/d6037c99-ac45-49ed-ae8a-0e800e4c2ae8">

**Comment by chaobeiying** [comment]
这个应该是个bug,将run_inference.py  49 行加入三个姿态控制的相关参数，改为：

gen_portrait = GenPortrait(pose_model_path, pose_image, use_depth_control, pos_prompt, neg_prompt, style_model_path, multiplier_style, use_main_model,
                            use_face_swap, use_post_process,
                            use_stylization)

**Comment by sunbaigui** [comment]
solved, try the latest code.
