### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by chaobeiying** [modelscope/facechain#147]
你好，经过调试，发现run_inference.py  49 行应该是更新姿态版本之后，未更新此处，需要加入pose_model_path, pose_image, use_depth_control三个参数。

**Comment by sunbaigui** [comment]
@You-Cun 帮忙一起看下。

**Comment by You-Cun** [comment]
Thanks for your suggestion, we will update 'run_inference.py' to support facechain inference with and without pose control no later than tomorrow.

**Comment by sunbaigui** [comment]
same as #151
