### ISSUE TITLE
onnxruntime version problem

### ISSUE THREAD

**Issue by blx0102** [modelscope/facechain#148]
I'm trying to use facechain on my own linux server, but using onnxruntime==1.14, when train the image, I encountered an error like this:
![image](https://github.com/modelscope/facechain/assets/17761044/2308c319-b539-4781-b3ef-af381d010d4d)

I modified relative code parts in facechain, but it seem there are same problems in modelscope's code.

**Comment by sunbaigui** [comment]
@ly19965 do you have any suggestion of this problem.

**Comment by sunbaigui** [comment]
> You can upgrade the onnxruntime module, i.e., "pip install onnxruntime==1.5.1".

try this, if you have further issues, feel free to reopen it.
