### ISSUE TITLE
find a bug

### ISSUE THREAD

**Issue by luoxianjun** [modelscope/facechain#151]
<img width="777" alt="image" src="https://github.com/modelscope/facechain/assets/5306492/62da3e1c-03f8-404d-ad9a-c769de029d30">
如果pose_prompt长度过长会报错

**Comment by luoxianjun** [comment]
传错参数了,
<img width="739" alt="image" src="https://github.com/modelscope/facechain/assets/5306492/db5bc958-356b-4351-9ff5-38b4ad538440">

**Comment by sunbaigui** [comment]
@You-Cun please check this

**Comment by sunbaigui** [comment]
solved by #157 , merged. please try it again.
