### ISSUE TITLE
执行"开始推理"时报错 OSError: [Errno 122] Disk quota exceeded

### ISSUE THREAD

**Issue by ufologist** [modelscope/facechain#16]
按照 ModelScope notebook 的方式跑起来了, 提示模型训练成功后, 执行"开始推理"时报错 `OSError: [Errno 122] Disk quota exceeded`

运行环境: 魔搭平台免费实例, PAI-DSW, GPU环境
```
8核 32GB 显存16G
预装 ModelScope Library
预装镜像  ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.1
```

工作空间的空间大小如下
```
root@dsw:/mnt/workspace# du -h -d 1
14G     ./.cache
73K     ./.ipynb_checkpoints
8.5K    ./.virtual_documents
574K    ./facechain
14G     .
```

魔搭平台免费实例是不是提供的硬盘太小了? 看 facechain 官方 README 是要求 Disk: About 50GB

有没有什么办法能够在魔搭平台免费实例上成功体验完全流程呢?

**Comment by yingdachen** [comment]
你的账号可能是比较早的一批账号了，所以只支持了10G的存储，新账号支持50G临时存储了。我们正在做用户迁移。

现在着急的话，可以加一下钉钉用户群（https://www.modelscope.cn/docs  社区交流），我们先手工处理一下账号。

**Comment by ufologist** [comment]
按照上面的指示, 加入到魔搭钉钉群`44837352`, 由`橙语`帮我升级到 50G 存储后就可以跑完全流程了, 非常感谢
