### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/ly261666/cv_portrait_model/test_labeled/metadata.jsonl'

### ISSUE THREAD

**Issue by Tohhanabi** [modelscope/facechain#161]
The platform used is Kaggle Notebooks.
Full log is in the attachment below.
[facechain.ipynb.zip](https://github.com/modelscope/facechain/files/12486275/facechain.ipynb.zip)

**Comment by sunbaigui** [comment]
@ly19965 please check it once you have a time

**Comment by ly19965** [comment]
This error comes from preprocess.py

**Comment by Tohhanabi** [comment]
> metadata.json

As I'm not particularly good at programming, could you please tell me what I can do to get the programme to generate the metadata.json properly?

**Comment by Tohhanabi** [comment]
> This error comes from preprocess.py. You can check following codes (try except) to find the reason why metadata.json is not generated. https://github.com/modelscope/facechain/blob/main/facechain/data_process/preprocessing.py#L271-L303 https://github.com/modelscope/facechain/blob/main/facechain/data_process/preprocessing.py#L356-L461

As I'm not particularly good at programming, could you please tell me what I can do to get the programme to generate the metadata.json properly?

**Comment by ly19965** [comment]
remove "try except" in  https://github.com/modelscope/facechain/blob/main/facechain/data_process/preprocessing.py#L271-L303 https://github.com/modelscope/facechain/blob/main/facechain/data_process/preprocessing.py#L356-L461
you can discover the real error. In our opinion, this error comes from your conda enviroment is not correct.

**Comment by ly19965** [comment]
Additionally, you have the option to pull the latest code, eliminating the need for the tensorflow package.

**Comment by huan-xi** [comment]
I also have the same issue, which seems to be a problem with the dependencies of mmcv. However, the previous version did not have this issue.

Traceback (most recent call last):
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 66, in _instantiate
    return cls(**kwargs)
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/modelscope/models/cv/face_detection/scrfd/damofd_detect.py", line 31, in __init__
    super().__init__(model_dir, **kwargs)
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/modelscope/models/cv/face_detection/scrfd/scrfd_detect.py", line 36, in __init__
    from mmdet.models import build_detector
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmdet/models/utils/__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmdet/models/utils/point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/huanxi/anaconda3/envs/fc_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/huanxi/anaconda3/envs/fc_new/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

**Comment by robbsaber** [comment]
Getting the same error on colab. Above advice didnt work. Can someone update/fix the colab please.

**Comment by sunbaigui** [comment]
we'll work on it, it's because of the updated env.

**Comment by RahulBhalley** [comment]
SAME error!

**Comment by whiteewei** [comment]
Same error in Colab notebook

**Comment by sunbaigui** [comment]
@wangxingjun778 please help to solve this on colab once you have a time.

**Comment by 00wan00** [comment]
SAME error!
并且tensorflow、pytorch、numpy卸载安装了好几遍了。还是不行！

**Comment by darenzai** [comment]
same error

**Comment by SoftologyPro** [comment]
Same error here under Windows.  Using these package versions to build the venv.

```
python -m pip install --upgrade pip
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wheel==0.38.4
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts accelerate==0.22.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts transformers==4.32.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts diffusers==0.20.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts onnxruntime==1.15.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts modelscope==1.8.4
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts Pillow==10.0.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts opencv-python==4.8.0.76
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts mmdet==2.26.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts mmengine==0.8.4
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts protobuf==3.20.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts timm==0.9.6
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts scikit-image==0.21.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts gradio==3.41.2
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts controlnet_aux==0.0.6
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts mediapipe==0.10.3
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts python-slugify==8.0.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts tensorflow==2.8.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts https://softology.pro/wheels/mmcv_full-1.7.1-cp310-cp310-win_amd64.whl
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 --index-url https://download.pytorch.org/whl/cu118
pip uninstall -y typing_extensions
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts typing_extensions==4.7.1
```

**Comment by sunbaigui** [comment]
issue #169 merged here.

**Comment by coripple** [comment]
网络不好，模型下载timeout了

**Comment by coripple** [comment]
> 

模型下载超时，导致preprocess没正确执行，就出现metadata.jsonl找不到问题。

1. 环境变量配置 export MODELSCOPE_CACHE=/facechain/models
2. 改下timeout设置 /opt/conda/lib/python3.8/site-packages/modelscope/hub/constants.py

**Comment by coripple** [comment]
> > > 
> > 
> > 
> > 模型下载超时，导致preprocess没正确执行，就出现metadata.jsonl找不到问题。
> > 
> > 1. 环境变量配置 export MODELSCOPE_CACHE=/facechain/models
> > 2. 改下timeout设置 /opt/conda/lib/python3.8/site-packages/modelscope/hub/constants.py
> 
> 这个改完后，你这个就成功了是么？

成功了，也是尝试下载了很多次。

**Comment by SoftologyPro** [comment]
It still does not work here with latest code.
Under Windows.
1. python app.py
2. Open the UI in browser
3. Load an image
4. Click Start Training
Fails after a minute or so with no such file.
Python environment packages here
https://github.com/modelscope/facechain/issues/161#issuecomment-1704290997
