### ISSUE TITLE
ValueError: --caption_column' value 'text' needs to be one of: image

### ISSUE THREAD

**Issue by mederka** [modelscope/facechain#171]
Hi there, thanks for the great work.

When I try to run:
```
PYTHONPATH=. sh train_lora.sh "ly261666/cv_portrait_model" "v2.0" "film/film" "my_pictures" "./processed" "./output"
```

I get this error:
```
Traceback (most recent call last):
2023-09-04 08:11:57.459 [stderr   ]   File "/data/repos/facechain/facechain/train_text_to_image_lora.py", line 1469, in <module>
2023-09-04 08:11:57.460 [stderr   ]     main()
2023-09-04 08:11:57.460 [stderr   ]   File "/data/repos/facechain/facechain/train_text_to_image_lora.py", line 1015, in main
2023-09-04 08:11:57.460 [stderr   ]     raise ValueError(
2023-09-04 08:11:57.460 [stderr   ] ValueError: --caption_column' value 'text' needs to be one of: image
```

The `my_pictures` directory has 10 pictures of a person.

**Comment by sunbaigui** [comment]
@You-Cun please check this out.

**Comment by You-Cun** [comment]
A probable reason is that some problems might occur in the "try-except" step in data preprocessing, so that no image or tag is generated in "./processed_labeled". You can remove the "try-except" codes in facechain/data_process/preprocessing.py to check the detailed problem.

**Comment by sunbaigui** [comment]
> Thank you for a quick response, @You-Cun! I feel like maybe I have a wrong version of `datasets`. The processed_labeled directory get created and it contains the metadata.jsonl file:
> 
> ```
> {"file_name": "0.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "1.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "2.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "3.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "4.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "5.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "6.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "7.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "8.png", "text": "<fcsks>, a handsome man"}
> {"file_name": "9.png", "text": "<fcsks>, a handsome man"}
> ```
> 
> I'm trying to run everything with in a conda environment.

it seems the issue was solved ?

**Comment by xaio6** [comment]
@mederka Hello, I want to ask you what the correct version of datasets is
