### ISSUE TITLE
关于风格LoRA模型的一些疑问

### ISSUE THREAD

**Issue by 904763189cy** [modelscope/facechain#174]
风格LoRA模型是你们预训练好的吗？
不同的pos_prompt对应不同的风格LoRA模型吗？
如果我增加新的cloth_prompt，然后使用新的cloth_prompt，如何拿到对应的风格LoRA模型从而进行推理？

谢谢。

**Comment by sunbaigui** [comment]
![image](https://github.com/modelscope/facechain/assets/2352602/d10b2c3a-6266-4995-ab3d-b11126462d35)
hi，周五这里的直播会有详细解释和教程，欢迎关注上来提问题哈。

**Comment by 904763189cy** [comment]
谢谢。
