### ISSUE TITLE
难道就我用不了吗

### ISSUE THREAD

**Issue by Bailey-24** [modelscope/facechain#175]
尝试过colab, 魔塔，docker部署都用不了，直接用hugging face的也用不了。
本地docker部署访问不了网站
![image](https://github.com/modelscope/facechain/assets/72083251/85ab0e36-22c8-4fd4-802e-23416fd47d31)
![image](https://github.com/modelscope/facechain/assets/72083251/d545b372-421d-49c4-b42e-952d4a32e845)

魔塔一直在转圈
![image](https://github.com/modelscope/facechain/assets/72083251/0f7732d2-59d5-4e0d-b69d-a669b0b387f7)

colab关了
反正本地那个网站网站不了，公开那个网站能访问，但是不能用，跟huggingface报一样的错。

**Comment by sjk7524068** [comment]
用0.0.0.0试一下

**Comment by ultimatech-cn** [comment]
欢迎加入windows平台，用pycharm安装棒棒的，还可以单步跟踪调试，学习源代码。

**Comment by sunbaigui** [comment]
> 尝试过colab, 魔塔，docker部署都用不了，直接用hugging face的也用不了。 本地docker部署访问不了网站 ![image](https://user-images.githubusercontent.com/72083251/265631922-85ab0e36-22c8-4fd4-802e-23416fd47d31.png) ![image](https://user-images.githubusercontent.com/72083251/265632686-d545b372-421d-49c4-b42e-952d4a32e845.png)
> 
> 魔塔一直在转圈 ![image](https://user-images.githubusercontent.com/72083251/265632006-0f7732d2-59d5-4e0d-b69d-a669b0b387f7.png)
> 
> colab关了 反正本地那个网站网站不了，公开那个网站能访问，但是不能用，跟huggingface报一样的错。

其实你已经都搞成功了。如果
<img width="171" alt="image" src="https://github.com/modelscope/facechain/assets/2352602/c84b513a-6a1f-49d6-9a34-62de226a6458">
点击这个链接访问不了。你可以改一句代码，share=False改为share=True应该就能访问公网链接了，参考https://discuss.huggingface.co/t/how-to-share-gradio-app-in-my-local-machine/37979 。

**Comment by Bailey-24** [comment]
点了链接还是无法访问，而且docker部署本来就是share=True，但是没有公网链接。
![image](https://github.com/modelscope/facechain/assets/72083251/caa6e03f-3e77-47a2-87a5-effa112c86f9)
![image](https://github.com/modelscope/facechain/assets/72083251/259e59bd-091c-4a95-833b-b209da085b41)
![image](https://github.com/modelscope/facechain/assets/72083251/336fa1fc-f256-4495-964c-e0b714f98f47)

**Comment by sjk7524068** [comment]
> 点了链接还是无法访问，而且docker部署本来就是share=True，但是没有公网链接。 ![image](https://user-images.githubusercontent.com/72083251/265658015-caa6e03f-3e77-47a2-87a5-effa112c86f9.png) ![image](https://user-images.githubusercontent.com/72083251/265658137-259e59bd-091c-4a95-833b-b209da085b41.png) ![image](https://user-images.githubusercontent.com/72083251/265658214-336fa1fc-f256-4495-964c-e0b714f98f47.png)

demo.queue(status_update_rate=1).launch(share=True, server_name="0.0.0.0", server_port=7860)

**Comment by sjk7524068** [comment]
demo.queue(status_update_rate=1).launch(share=True, server_name="0.0.0.0", server_port=7860)

**Comment by Bailey-24** [comment]
可以了，要关掉代理才可以
