### ISSUE TITLE
Colab Demo Error

### ISSUE THREAD

**Issue by bensonbs** [modelscope/facechain#178]
使用Colab範例得到錯誤
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/YorickHe/majicmixRealistic_v6/test_labeled/metadata.jsonl'
```

**Comment by sunbaigui** [comment]
@wangxingjun778 帮忙看看

**Comment by podradio** [comment]
The same error

**Comment by BERT202206** [comment]
me too, wish hurry fix

**Comment by B-1368** [comment]
me too, got the same error

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/personalization_lora_labeled/metadata.jsonl'`

**Comment by wangxingjun778** [comment]
I can't replicate this issue on colab A100 envs ...  We are trying  to locate this problem with more configs.

**Comment by sunbaigui** [comment]
#204 issue merged here. @wangxingjun778

**Comment by wangxingjun778** [comment]
The connection error may cause  this issue, please refer to the latest colab demo:

https://colab.research.google.com/github/modelscope/facechain/blob/main/facechain_demo.ipynb
