### ISSUE TITLE
In Conda env get error `Expecting value: line 1 column 1 (char 0)`

### ISSUE THREAD

**Issue by bensonbs** [modelscope/facechain#179]
使用Conda範例部屬能夠啟動app
```
(facechain) C:\Users\BBS\facechain>python app.py --debug
2023-09-05 22:38:01,371 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-09-05 22:38:01,373 - modelscope - INFO - Loading ast index from C:\Users\BBS\.cache\modelscope\ast_indexer
2023-09-05 22:38:01,435 - modelscope - INFO - Loading done! Current index file version is 1.9.0, with md5 2a765a53f97d8027ffd75bea37d4b289 and a total number of 921 components indexed
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://24683061fbc97c7a88.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
```

但在案`開始訓練`後再gradio介面會得到
```
Error
Expecting value: line 1 column 1 (char 0)
```
終端機沒有出現和錯誤代碼

**Comment by sunbaigui** [comment]
@wangxingjun778 帮忙看看conda环境下的问题。

**Comment by JPW0080** [comment]
Functionality verified
Win 11
3090

Command Prompt:

mkdir \ai-related
cd \ai-related
git clone https://github.com/ultimatech-cn/facechain-win.git
python -m venv \ai-related\facechain-win\venv
\ai-related\facechain-win\venv\Scripts\activate.bat
cd \ai-related\facechain-win
pip install -r reqiuirements.txt
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip uninstall torch
pip install mmcv-full
pip uninstall torchvision torch
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip uninstall numpy
pip install numpy --upgrade
accelerate config #Proceed with the below settings. #Remember to reset the config as desired for other AI related tasks.

This machine
No distributing training
NO
NO
NO
all
no

python app-win.py

**Comment by livehl** [comment]
关掉翻墙代理

**Comment by sunbaigui** [comment]
> 关掉翻墙代理

@JPW0080 你试下。

**Comment by sunbaigui** [comment]
see #112
