### ISSUE TITLE
Conda deployment, how to switch between different styles,

### ISSUE THREAD

**Issue by zyw11270106** [modelscope/facechain#181]
Conda deployment, how to switch between different styles,

base_model_sub_dir = 'film/film'，
Now there is only film/film, which is a formal style format.
And I modified the realistic, and the generated image style did not change
 If you want to generate photos in other styles, how do you set parameters, explain where the document is？
Or can senior personnel guide me?

I would greatly appreciate it

**Comment by sunbaigui** [comment]
you can choose maji* basemodel to train your ID lora, an then inference with maji* basemodel, currently styles are mapping to different basemodel.

**Comment by zyw11270106** [comment]
> you can choose maji* basemodel to train your ID lora, an then inference with maji* basemodel, currently styles are mapping to different basemodel.

Thank you very much for your reply. Is the parameter ly261666/cv_portrait_model the basemodel you mentioned? What are the specific basic models? I haven't found it yet.
I may not have expressed myself clearly. I want to switch Cloth Styles on my own server.
PYTHONPATH=. sh train_lora.sh "ly261666/cv_portrait_model" "v2.0" "film/film" "./imgs" "./processed" "./output"
However, it cannot be set in the above command. I would like to inquire about how to set this parameter. Thank you very much.
