### ISSUE TITLE
调用推理脚本 运行推理报错

### ISSUE THREAD

**Issue by hccywq** [modelscope/facechain#190]
[ WARN:0@70.173] global loadsave.cpp:248 findDecoder imread_('nsfw, paintings, sketches, (worst quality:2), (low quality:2) lowers, normal quality, ((monochrome)), ((grayscale)), logo, word, character'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "run_inference.py", line 60, in <module>
    outputs = gen_portrait(processed_dir, num_generate, base_model,
  File "/mnt/workspace/facechain/facechain/inference.py", line 474, in __call__
    gen_results = main_model_inference(self.pose_model_path, self.pose_image, self.use_depth_control,
  File "/mnt/workspace/facechain/facechain/inference.py", line 362, in main_model_inference
    pose_image = compress_image(pose_image, 1024 * 1024)
  File "/mnt/workspace/facechain/facechain/inference.py", line 503, in compress_image
    while cv2.imencode('.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, quality])[1].size > target_size:
cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:1113: error: (-215:Assertion failed) !image.empty() in function 'imencode'

**Comment by sunbaigui** [comment]
@LU-V please check this out at your convenience.

**Comment by sunbaigui** [comment]
> [ WARN:0@70.173] global loadsave.cpp:248 findDecoder imread_('nsfw, paintings, sketches, (worst quality:2), (low quality:2) lowers, normal quality, ((monochrome)), ((grayscale)), logo, word, character'): can't open/read file: check file path/integrity Traceback (most recent call last): File "run_inference.py", line 60, in outputs = gen_portrait(processed_dir, num_generate, base_model, File "/mnt/workspace/facechain/facechain/inference.py", line 474, in **call** gen_results = main_model_inference(self.pose_model_path, self.pose_image, self.use_depth_control, File "/mnt/workspace/facechain/facechain/inference.py", line 362, in main_model_inference pose_image = compress_image(pose_image, 1024 * 1024) File "/mnt/workspace/facechain/facechain/inference.py", line 503, in compress_image while cv2.imencode('.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, quality])[1].size > target_size: cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:1113: error: (-215:Assertion failed) !image.empty() in function 'imencode'

it's a random error? we can not reproduce it  stably.
