### ISSUE TITLE
网站点击开始训练，界面出现error

### ISSUE THREAD

**Issue by HuntZhaozq** [modelscope/facechain#193]
请问这个问题如何解决呀？后台也没有报错误信息。
我是本地docker部署的，没有外网，设置了share=False

**Comment by sunbaigui** [comment]
界面出现error没事，看后台log就行，因为训练和推理时间都超过gradio保活的时间。大概率都会出gradio界面报错。这个是gradio不支持长时间等待的问题。我们正尝试向gradio提feature修复。

**Comment by HuntZhaozq** [comment]
主要是后台log没有显示消息。。run on public URL，
1.点击训练后就没有出现log了，这个怎么解决呀？
2.显示训练完成后，inference点击产出模型，一直刷新不出来，看了本地文件，也没有新增的文件。
2.本地docker部署，没有连internet也能用这个模型吗？
