### ISSUE TITLE
能否支持多用户同时训练和推理？

### ISSUE THREAD

**Issue by HuntZhaozq** [modelscope/facechain#195]
请问生成了网址，如果两个用户同时点击训练和推理，是会各自运行自己的任务，最后生成两个用户的照片吗？
还是后来的任务会中断前用户的任务？

**Comment by GefeiSHEN** [comment]
根据我的观察，是顺序执行的。

**Comment by HuntZhaozq** [comment]
不会中断前用户的任务吗

> 根据我的观察，是顺序执行的。

**Comment by sunbaigui** [comment]
如果直接做成服务你是需要做些改动的。魔搭在线版本的应用你可以参考下。有些文件夹会按uid去区分。
