### ISSUE TITLE
Why need zjz_mj_jiyi_small_addtxt_fromleo lora model when Default Style?

### ISSUE THREAD

**Issue by vonchenplus** [modelscope/facechain#196]
Thank you for youre gread works! And one question, Why should I include the zjz_mj_jiyi_small_addtxt_fromleo lora model when the default style appears to be governed by the base model using various prompts, and my testing indicates that this model doesn't seem to make any difference?

**Comment by sunbaigui** [comment]
we have done some testing，it makes some difference when put different cloth，current version will be more stable for that. we‘ll make a big update soon. you can try it later.
