### ISSUE TITLE
部分lora模型推理时报错

### ISSUE THREAD

**Issue by thatsmyname0** [modelscope/facechain#203]
有些lora模型在推理时会报错“FileNotFoundError: No such file or directory: "/mnt/workspace/.cache/modelscope/xxx/xxx/xxx.safetensors"

**Comment by sunbaigui** [comment]
> 有些lora模型在推理时会报错“FileNotFoundError: No such file or directory: "/mnt/workspace/.cache/modelscope/xxx/xxx/xxx.safetensors"

具体是哪几个能发下么？我们去复现下。

**Comment by thatsmyname0** [comment]
https://civitai.com/models/129317/ballpointpainting
https://civitai.com/models/111793/pixel-portrait
https://civitai.com/models/43820/pixel-art-style
基模型用的是MajicmixRealistic_v6，无姿态控制。不管是放在modelscope的模型库然后再添加到constants中还是直接在网页上传.safetensors文件都不能用

**Comment by sunbaigui** [comment]
> https://civitai.com/models/43820/pixel-art-style

<img width="450" alt="image" src="https://github.com/modelscope/facechain/assets/2352602/33124809-11e5-464c-a550-5dc420ff9e48">
入下群，我们在这里做些排查，我看了其中明确写1.5的照理说应该可以的。
