### ISSUE TITLE
人物LoRA列表能否只显示当前训练的模型

### ISSUE THREAD

**Issue by HuntZhaozq** [modelscope/facechain#213]
在使用过程中发现，上一个用户训练的LoRA模型，下一个用户也能看到，如何屏蔽或删除之前训练好的LoRA模型？

**Comment by sunbaigui** [comment]
是github master里对吧，这个目前默认是单用户使用。如果面向多用户使用是需要做些服务化外围框架以及api设计。这块的feature在我们to do list里。如何服务好开发者的二次集成专项。

**Comment by HuntZhaozq** [comment]
是在github master里，那现在的话，如何删除已有的人物LoRA列表，清空历史model呢？
