### ISSUE TITLE
如何调整图片中的人物大小

### ISSUE THREAD

**Issue by Nomination-NRB** [modelscope/facechain#214]
你好，在我更新最新版本之后，发现和初版出图的人物大小有所变化，是通过prompt中的medium shot来控制吗，但最新版的prompt也有medium shot得到的却是半身照而不是头像照

初版：
![image](https://github.com/modelscope/facechain/assets/83486284/51cd08c4-455a-4160-914e-17094b37253a)

最新版：
![image](https://github.com/modelscope/facechain/assets/83486284/8ffb086b-17cf-4987-94b2-521918572a22)

**Comment by sunbaigui** [comment]
建议通过上传姿势模版来做pose，跟近景和远景的控制。

**Comment by Nomination-NRB** [comment]
> 建议通过上传姿势模版来做pose，跟近景和远景的控制。

好的，我去尝试一下

**Comment by Nomination-NRB** [comment]
> 建议通过上传姿势模版来做pose，跟近景和远景的控制。

经过尝试，指定pose图片的远近即可控制生成图的远近
