### ISSUE TITLE
windows10   python app.py    ValueError: Tried to find /tmp/qw/ly261666/cv_portrait_model/wyw\"fromfacecommon" but folder does not exist

### ISSUE THREAD

**Issue by Aruen24** [modelscope/facechain#215]

**Comment by sunbaigui** [comment]
@ultimatech-cn hi, can you help to check this out, if you have the experience in the latest version of windows.

**Comment by Aruen24** [comment]
@ultimatech-cn Resuming from checkpoint "fromfacecommon"
Traceback (most recent call last):
  File "facechain/train_text_to_image_lora.py", line 1161, in <module>
    main()
  File "facechain/train_text_to_image_lora.py", line 931, in main
    accelerator.load_state(os.path.join(args.output_dir, path))
  File "D:\soft\Miniconda\envs\facechain\lib\site-packages\accelerate\accelerator.py", line 2650, in load_state
    raise ValueError(f"Tried to find {input_dir} but folder does not exist")
ValueError: Tried to find /tmp/qw/ly261666/cv_portrait_model/wyw\"fromfacecommon" but folder does not exist

**Comment by Aruen24** [comment]
@ultimatech-cn When run in windows the app.py line 475 need change
 if not os.path.exists(f"/tmp/{uuid}"):
      os.makedirs(f"/tmp/{uuid}")
  work_dir = f"/tmp/{uuid}/{base_model_path}/{output_model_name}"

  if os.path.exists(work_dir):
      raise gr.Error("人物lora名称已存在。(This character lora name already exists.)")

  print("----------work_dir: ", work_dir)

**Comment by ak01user** [comment]
have the same question

**Comment by Aruen24** [comment]
> have the same question

@ak01user  Do you solve the problem？

**Comment by ultimatech-cn** [comment]
you should delete  quota ""  in app.py
something like that
'--resume_from_checkpoint=fromfacecommon',
That's the difference  of linux and windows.

**Comment by Aruen24** [comment]
@ultimatech-cn 
I change the app.py file line 105 
'--resume_from_checkpoint="fromfacecommon"'  to '--resume_from_checkpoint=fromfacecommon'
and all /tmp to E:\\PyCharmProject\\facechain\\tmp

**Comment by ultimatech-cn** [comment]
> @ultimatech-cn I change the app.py file line 105 '--resume_from_checkpoint="fromfacecommon"' to '--resume_from_checkpoint=fromfacecommon' and all /tmp to E:\PyCharmProject\facechain\tmp

good! how is going,
