### ISSUE TITLE
无限风格写真生成的时候提示下面的内容

### ISSUE THREAD

**Issue by wangyong860401** [modelscope/facechain#216]
Token indices sequence length is longer than the specified maximum sequence length for this model (82 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['photorealistic, best quality']

**Comment by sunbaigui** [comment]
hi, prompt length is too long, try to squeeze it.

**Comment by wangyong860401** [comment]
你好，现在默认的风格大部分都会提示超过77，没有自动手动添加prompt，这个后期会优化prompt吗？

**Comment by sunbaigui** [comment]
> 你好，现在默认的风格大部分都会提示超过77，没有自动手动添加prompt，这个后期会优化prompt吗？

之前好像有人提过这个问题。你可以先搜索下看看。
