### ISSUE TITLE
ValueError: --caption_column' value 'text' needs to be one of: image

### ISSUE THREAD

**Issue by xhyandwyy** [modelscope/facechain#218]
![image](https://github.com/modelscope/facechain/assets/29997785/f033e51c-7088-4ead-abe2-6889c7216135)

Dataset imagefolder downloaded and prepared to /root/.cache/huggingface/datasets/imagefolder/person1_labeled-efa20e7da2085b75/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 799.07it/s]
Traceback (most recent call last):
  File "facechain/train_text_to_image_lora.py", line 1161, in <module>
    main()
  File "facechain/train_text_to_image_lora.py", line 785, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=/tmp/qw/training_data/ly261666/cv_portrait_model/person1', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/tmp/qw/ly261666/cv_portrait_model/person1', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
<center><font size=4>训练已经完成！请切换至 [无限风格形象写真] 标签体验模型效果。</center>

通过gradio直接训练
![image](https://github.com/modelscope/facechain/assets/29997785/a960903c-5eb6-4c72-a0f0-8daa3007b460)

**Comment by sunbaigui** [comment]
maybe there's no actual face detected in training or testing. try to change the training photos.
