### ISSUE TITLE
提示训练完成了，但是生成却没没找到lora

### ISSUE THREAD

**Issue by BERT202206** [modelscope/facechain#236]
提示训练完成了，但是点击对应的Lora没有刷新，生成出现：Error
该基模型下没有人物LoRA，请先训练(There is no character LoRA under this base model, please train first)!

**Comment by 00wan00** [comment]
我的也是这个问题。

**Comment by starkbtc** [comment]
一样

**Comment by HotelEnglish** [comment]
me too.

**Comment by potazinc** [comment]
查看了一下训练相关代码，如果train_text_to_image_lora.py模块运行发生错误时，用户界面仍然会显示训练成功。不知道是不是这个原因，可以看看命令行的log

**Comment by livehl** [comment]
报错了，训练没有成功，看看后台日志找出具体原因
