### ISSUE TITLE
Trained on chinese facial traits only?

### ISSUE THREAD

**Issue by VioletRaven** [modelscope/facechain#238]
Pretty cool one but I am caucasian and I am trying to make it work on me but it seems like it can only handle chinese (asian) facial traits. Should I provide more training images or just give up at all?

Thanks in advance,

Andrea

**Comment by sunbaigui** [comment]
@VioletRaven Thanks for your appreciation, it's designed for all in the first place. And some usercases are showed in the below. https://twitter.com/camenduru/status/1697094503440486478 . Maybe there's something need to be improved. could you describe it a little bit more?
