### ISSUE TITLE
steps如何控制

### ISSUE THREAD

**Issue by Nomination-NRB** [modelscope/facechain#243]
你好，请问Steps: 100%|██████████| 2000/2000 [09:34<00:00,  3.48it/s, lr=0, step_loss=0.00111]

这个Step是如何控制的，是通过train_lora.sh中的num_train_epochs和图片数量控制的吗

**Comment by sunbaigui** [comment]
> 你好，请问Steps: 100%|██████████| 2000/2000 [09:34<00:00, 3.48it/s, lr=0, step_loss=0.00111]
> 
> 这个Step是如何控制的，是通过train_lora.sh中的num_train_epochs和图片数量控制的吗

你看下train的函数，应该有两个参数，训练图片数，以及每张图片step数。

**Comment by Nomination-NRB** [comment]
> > 你好，请问Steps: 100%|██████████| 2000/2000 [09:34<00:00, 3.48it/s, lr=0, step_loss=0.00111]
> > 这个Step是如何控制的，是通过train_lora.sh中的num_train_epochs和图片数量控制的吗
> 
> 你看下train的函数，应该有两个参数，训练图片数，以及每张图片step数。

好的
