### ISSUE TITLE
卡在load_dataset方法

### ISSUE THREAD

**Issue by SZLMessi** [modelscope/facechain#246]
执行load_dataset方法时，会有概率卡在这个方法很久很久
Downloading and preparing dataset imagefolder/personalizaition_lora_labeled to /root/.cache/huggingface/datasets/imagefolder/personalizaition_lora_labeled-3de72a2657913bda/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f...

**Comment by ultimatech-cn** [comment]
下载模型文件呢，取决于你的网速和之前是否下载过模型文件。耐心等等吧

**Comment by livehl** [comment]
huggingface 看概率，有可能会被墙。尝试用代理试试

**Comment by DevelopmentZheng** [comment]
能自己下载吗

**Comment by sunbaigui** [comment]
merged to issue #336
