### ISSUE TITLE
Bug：train_text_to_image_lora.py模块运行发生错误时，用户界面仍然会显示训练成功

### ISSUE THREAD

**Issue by HuntZhaozq** [modelscope/facechain#276]
请问如何修改该设定，当train_text_to_image_lora.py模块运行发生错误，提示用户训练失败呢？并且删除该失败的文件夹。
或者你们会修复下这个bug吗？

**Comment by sunbaigui** [comment]
> 请问如何修改该设定，当train_text_to_image_lora.py模块运行发生错误，提示用户训练失败呢？并且删除该失败的文件夹。 或者你们会修复下这个bug吗？

hi，如果你这边感兴趣的话，欢迎提交PR:-)

**Comment by HuntZhaozq** [comment]
不好意思啊，我是初学者，请问能指引下修改哪个地方会比较好吗

**Comment by ly19965** [comment]
已merge，感谢！
