### ISSUE TITLE
ZJU_19: neg_prompt强制全局共享，缺少风格尺度上的定制性

### ISSUE THREAD

**Issue by chkhu** [modelscope/facechain#278]
不同于正向Prompt有全局部分和定制部分，负向的prompt的仅有全局共享的部分
开发者无法随意为单独某一个新风格添加定制的否定词（是很普遍的需求），然而基于其共享属性，它将不可避免地被所有现存所有风格共享。
当定制词有利于某个风格但可能干扰其他现存风格时，问题就产生了。

<img width="995" alt="image" src="https://github.com/modelscope/facechain/assets/109655311/f7408ff0-7481-4e69-b4e4-ab543f0ff336">

目前的思路是：
原本的neg_prompt 改成 neg_ prompt base；
style 添加 add neg_prompt 字段
run inference.py 中 添加 generate_ neg_prompt 西数，来连接前二者。

<img width="802" alt="image" src="https://github.com/modelscope/facechain/assets/109655311/6a0f7faa-0af6-4a9b-8bb6-37b202a44732">
<br>
但由于涉及app.py的逻辑以及时间紧张，暂且放一个issue。后续将会PR。

**Comment by ly19965** [comment]
先关闭了，有PR的话回复我下哈
