### ISSUE TITLE
下载的一些风格lora模型和人脸处理相关的模型默认到.cache目录，能够改到指定的目录吗？

### ISSUE THREAD

**Issue by Aruen24** [modelscope/facechain#288]

**Comment by sunbaigui** [comment]
在等待一些同学的PR中

**Comment by wangzhaolei** [comment]
把默认下载到的目录'/root/.cache/modelscope/hub'  里的东西全部放到   ——>     '你想放到的自定义目录/modelscope'

然后 app.py里面开头加上 
import os
os.environ['MODELSCOPE_CACHE']= '你想放到的自定义目录/modelscope'

**Comment by livehl** [comment]
env MODELSCOPE_CACHE=/root/.cache/modelscope
设置环境变量即可

**Comment by Aruen24** [comment]
@wangzhaolei windows环境下也可以吧
