### ISSUE TITLE
Docker container for facechain on dockerhub

### ISSUE THREAD

**Issue by bianyuanop** [modelscope/facechain#295]
I noticed that you are using aliyun hangzhou registry to serve:
`docker pull registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.0`

but the downloading process is extremely slow when you are outside of China. 

Any way I can get a similar docker image from DockerHub?

**Comment by sunbaigui** [comment]
@wangxingjun778 please check this out at your convenience.

**Comment by wangxingjun778** [comment]
> I noticed that you are using aliyun hangzhou registry to serve: `docker pull registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.0`
> 
> but the downloading process is extremely slow when you are outside of China.
> 
> Any way I can get a similar docker image from DockerHub?



try this docker repo on us-west endpoint:    

registry.us-west-1.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.8.0-py38-torch2.0.1-tf2.13.0-1.9.2
