### ISSUE TITLE
RuntimeError: context has already been set

### ISSUE THREAD

**Issue by Tohhanabi** [modelscope/facechain#297]
The platform used is Kaggle Notebooks.
Full log is in the attachment below.
[facechain.ipynb.zip](https://github.com/modelscope/facechain/files/12621433/facechain.ipynb.zip)

**Comment by sunbaigui** [comment]
@wangxingjun778 please check it out at your convenience.

**Comment by Husky110** [comment]
Got the same error on Google Colab... Please check this!
