### ISSUE TITLE
Downloading and preparing dataset 这一步卡很久正常么

### ISSUE THREAD

**Issue by gripdestiny** [modelscope/facechain#299]
你好，

看起来这一步也不需要从网上下载文件，

在离线准备训练数Downloading and preparing dataset imagefolder/girl_labeled to /home/会卡很久，我试过过把代码搞出来弄出来在window下跑久很快这有什么解决方案不，在ubuntu下，3张图片，应该会卡个10-20分钟

代码是类似
```
 from datasets import load_dataset

 dataset = load_dataset(
             "./girl_labeled",
             None,
             cache_dir=None,
         )
```

**Comment by sunbaigui** [comment]
@ultimatech-cn please check this issue at your convenience.

**Comment by ultimatech-cn** [comment]
> 你好，
> 
> 看起来这一步也不需要从网上下载文件，
> 
> 在离线准备训练数Downloading and preparing dataset imagefolder/girl_labeled to /home/会卡很久，我试过过把代码搞出来弄出来在window下跑久很快这有什么解决方案不，在ubuntu下，3张图片，应该会卡个10-20分钟
> 
> 代码是类似
> 
> ```
>  from datasets import load_dataset
> 
>  dataset = load_dataset(
>              "./girl_labeled",
>              None,
>              cache_dir=None,
>          )
> ```

你的问题是在windows下，可以很快，但是在ubuntu上很慢么？
你说的这个方法会下载模型文件，是不是你windows环境已经有了模型文件，而ubuntu是第一次使用呢？
能给更详细的信息么？

**Comment by gripdestiny** [comment]
> > 你好，
> > 看起来这一步也不需要从网上下载文件，
> > 在离线准备训练数Downloading and preparing dataset imagefolder/girl_labeled to /home/会卡很久，我试过过把代码搞出来弄出来在window下跑久很快这有什么解决方案不，在ubuntu下，3张图片，应该会卡个10-20分钟
> > 代码是类似
> > ```
> >  from datasets import load_dataset
> > 
> >  dataset = load_dataset(
> >              "./girl_labeled",
> >              None,
> >              cache_dir=None,
> >          )
> > ```
> 
> 你的问题是在windows下，可以很快，但是在ubuntu上很慢么？ 你说的这个方法会下载模型文件，是不是你windows环境已经有了模型文件，而ubuntu是第一次使用呢？ 能给更详细的信息么？

对，我在windows下很快，ubuntu就很慢。
不是第一次也很慢，粗略，看这一步的应该是将用到和图片和图片文字jsonl文件
![image](https://github.com/modelscope/facechain/assets/23710846/e6edede5-4c26-4473-9252-90981620cae5)
换成的dataset_info.json等相关文件的
![image](https://github.com/modelscope/facechain/assets/23710846/eea57a8e-c41b-40bc-aaac-9129c3c61d9e)

按理应该是很快，没找出具体的问题

**Comment by ultimatech-cn** [comment]
出图的时间正常么？ 这个问题比较奇怪，要查的化估计需要debug来一步一步排查。你Ubuntu的机器配置是啥？

**Comment by gripdestiny** [comment]
> 出图的时间正常么？ 这个问题比较奇怪，要查的化估计需要debug来一步一步排查。你Ubuntu的机器配置是啥？

除了这一步，其他都正常。
我最后定位到是miniconda3/envs/facechain/lib/python3.10/site-packages/datasets/builder.py  函数def download_and_prepare中的with FileLock(lock_path) if is_local else contextlib.nullcontext(): 这行代码卡住了，is_local是True，看起来像是FileLock锁住了

**Comment by gripdestiny** [comment]
最终解决了这个问题，手段比较粗暴，离线环境下，仅自己用可以考虑
主要是修改miniconda3/envs/facechain/lib/python3.10/site-packages/datasets/builder.py 几处修改
1、FileLock(lock_path)会锁住，可以考虑将FileLock(lock_path)改成 contextlib.nullcontext()，有几处代码需要修改，搜索一下，
2、默认情况下，def download_and_prepare函数的参数try_from_hf_gcs应该会是true，true情况下会尝试访问网络耗时较长，可以在进入函数后强制设置成false。

修改上述两点后可以很快跑完训练流程，推理流程也正常。
期待更好的解决方案

**Comment by wwj1013** [comment]
> 最终解决了这个问题，手段比较粗暴，离线环境下，仅自己用可以考虑 主要是修改miniconda3/envs/facechain/lib/python3.10/site-packages/datasets/builder.py 几处修改 1、FileLock(lock_path)会锁住，可以考虑将FileLock(lock_path)改成 contextlib.nullcontext()，有几处代码需要修改，搜索一下， 2、默认情况下，def download_and_prepare函数的参数try_from_hf_gcs应该会是true，true情况下会尝试访问网络耗时较长，可以在进入函数后强制设置成false。
> 
> 修改上述两点后可以很快跑完训练流程，推理流程也正常。 期待更好的解决方案

您好，想问一下我也碰到了您的情况，修改之后也能成功训练和推理，但是想训练第二个人的数据时，再进行推理时生成的图片又是之前第一个人的样貌，您有碰到过这种情况吗？（我假如重新安装datasets再修改一遍又会正常，但这太麻烦了）
