### ISSUE TITLE
有考虑支持 macOS 吗

### ISSUE THREAD

**Issue by foolyoghurt** [modelscope/facechain#301]
希望能够提供 macOS 的支持，目前 MacBook 作为程序员的工作电脑已经非常普及了，如果支持 macOS 的话就可以用工作电脑本地跑了，而不用远程到 Linux 服务器，体验会提升很大～

**Comment by sunbaigui** [comment]
有的，你这边有兴趣一起开发么，目前这块还没有招募到合适的开发者。

**Comment by sunbaigui** [comment]
对facechain macOS感兴趣的开发者，可以留言报名哈。

**Comment by yingdachen** [comment]
> 希望能够提供 macOS 的支持，目前 MacBook 作为程序员的工作电脑已经非常普及了，如果支持 macOS 的话就可以用工作电脑本地跑了，而不用远程到 Linux 服务器，体验会提升很大～

现在macOS上哪里不支持了呢？如果macOS上有GPU应该是能跑的吧

**Comment by foolyoghurt** [comment]
> > 希望能够提供 macOS 的支持，目前 MacBook 作为程序员的工作电脑已经非常普及了，如果支持 macOS 的话就可以用工作电脑本地跑了，而不用远程到 Linux 服务器，体验会提升很大～
> 
> 现在macOS上哪里不支持了呢？如果macOS上有GPU应该是能跑的吧

点击「开始训练」会提示不支持 CUDA
<img width="465" alt="image" src="https://github.com/modelscope/facechain/assets/3326901/0de88633-8818-4f68-abc8-90a4cb66c8cb">

```bash
Traceback (most recent call last):
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/song/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 448, in run
    raise gr.Error('CUDA不可用(CUDA not available)')
gradio.exceptions.Error: 'CUDA不可用(CUDA not available)'
```

**Comment by yingdachen** [comment]
> > > 希望能够提供 macOS 的支持，目前 MacBook 作为程序员的工作电脑已经非常普及了，如果支持 macOS 的话就可以用工作电脑本地跑了，而不用远程到 Linux 服务器，体验会提升很大～
> > 
> > 
> > 现在macOS上哪里不支持了呢？如果macOS上有GPU应该是能跑的吧
> 
> 点击「开始训练」会提示不支持 CUDA <img alt="image" width="465" src="https://user-images.githubusercontent.com/3326901/270110832-0de88633-8818-4f68-abc8-90a4cb66c8cb.png">
> 
> ```shell
> Traceback (most recent call last):
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
>     output = await route_utils.call_process_api(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
>     result = await self.call_function(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
>     response = f(*args, **kwargs)
>   File "app.py", line 448, in run
>     raise gr.Error('CUDA不可用(CUDA not available)')
> gradio.exceptions.Error: 'CUDA不可用(CUDA not available)'
> ```
> 
> 如果把 CUDA 的检查去掉，会报如下错误
> 
> ```shell
> Traceback (most recent call last):
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
>     output = await route_utils.call_process_api(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
>     result = await self.call_function(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
>     response = f(*args, **kwargs)
>   File "app.py", line 489, in run
>     prepare_dataset([img['name'] for img in instance_images], output_dataset_dir=instance_data_dir)
>   File "/Users/xxxxx/Codes/github/facechain/facechain/train_text_to_image_lora.py", line 193, in prepare_dataset
>     image = get_rot(image)
>   File "/Users/xxxxx/Codes/github/facechain/facechain/train_text_to_image_lora.py", line 144, in get_rot
>     ort_session = onnxruntime.InferenceSession(model_path)
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
>     raise e
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
>     raise ValueError(
> ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
> ```

需要有GPU的机器才能跑起来。

**Comment by foolyoghurt** [comment]
> > > > 希望能够提供 macOS 的支持，目前 MacBook 作为程序员的工作电脑已经非常普及了，如果支持 macOS 的话就可以用工作电脑本地跑了，而不用远程到 Linux 服务器，体验会提升很大～
> 
> > > 
> 
> > > 
> 
> > > 现在macOS上哪里不支持了呢？如果macOS上有GPU应该是能跑的吧
> 
> > 
> 
> > 点击「开始训练」会提示不支持 CUDA <img alt="image" width="465" src="https://user-images.githubusercontent.com/3326901/270110832-0de88633-8818-4f68-abc8-90a4cb66c8cb.png">
> 
> > 
> 
> > ```shell
> 
> > Traceback (most recent call last):
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
> 
> >     output = await route_utils.call_process_api(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
> 
> >     output = await app.get_blocks().process_api(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
> 
> >     result = await self.call_function(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
> 
> >     prediction = await anyio.to_thread.run_sync(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
> 
> >     return await get_asynclib().run_sync_in_worker_thread(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
> 
> >     return await future
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
> 
> >     result = context.run(func, *args)
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
> 
> >     response = f(*args, **kwargs)
> 
> >   File "app.py", line 448, in run
> 
> >     raise gr.Error('CUDA不可用(CUDA not available)')
> 
> > gradio.exceptions.Error: 'CUDA不可用(CUDA not available)'
> 
> > ```
> 
> > 
> 
> > 如果把 CUDA 的检查去掉，会报如下错误
> 
> > 
> 
> > ```shell
> 
> > Traceback (most recent call last):
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
> 
> >     output = await route_utils.call_process_api(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
> 
> >     output = await app.get_blocks().process_api(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
> 
> >     result = await self.call_function(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
> 
> >     prediction = await anyio.to_thread.run_sync(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
> 
> >     return await get_asynclib().run_sync_in_worker_thread(
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
> 
> >     return await future
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
> 
> >     result = context.run(func, *args)
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
> 
> >     response = f(*args, **kwargs)
> 
> >   File "app.py", line 489, in run
> 
> >     prepare_dataset([img['name'] for img in instance_images], output_dataset_dir=instance_data_dir)
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechain/train_text_to_image_lora.py", line 193, in prepare_dataset
> 
> >     image = get_rot(image)
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechain/train_text_to_image_lora.py", line 144, in get_rot
> 
> >     ort_session = onnxruntime.InferenceSession(model_path)
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
> 
> >     raise e
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
> 
> >     self._create_inference_session(providers, provider_options, disabled_optimizers)
> 
> >   File "/Users/xxxxx/Codes/github/facechain/facechainenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
> 
> >     raise ValueError(
> 
> > ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
> 
> > ```
> 
> 
> 
> 需要有GPU的机器才能跑起来。

Mac 也是有 GPU 的，只不过是苹果的 GPU，不是英伟达的，跑开源的大模型 LLAMA2 这些都可以的，GPU 可以跑满 100%

**Comment by yingdachen** [comment]
明白你的意思了。GPU目前只支持CUDA适配，当前没有计划支持其他硬件。
