### ISSUE TITLE
release版本1.0.0和目前仓库版本出图效果差异很大，对人脸的还原差了很多

### ISSUE THREAD

**Issue by Nomination-NRB** [modelscope/facechain#302]
你好，请问在使用仓库目前版本代码，使用默认基模型和风格出图相较于release版本1.0.0差异很大
为什么使用相同的机模型和风格区别会这么大呢，prompt等其他控制信息都没有变化

**Comment by potoyeee** [comment]
我发现当前github的版本和之前的版本，对人脸的还原差了很多，生成的人物没有以前像了

**Comment by Nomination-NRB** [comment]
> 我发现当前github的版本和之前的版本，对人脸的还原差了很多，生成的人物没有以前像了

是的，我也是发现这个情况，但是以前的版本使用的参数和现在版本使用参数一样的

**Comment by Nomination-NRB** [comment]
> 我发现当前github的版本和之前的版本，对人脸的还原差了很多，生成的人物没有以前像了

我觉得是这个pr之后就开始不像原本的人脸了：
![)D1T%Z%R0R0D7OK{8VBKSYB](https://github.com/modelscope/facechain/assets/83486284/e1e4e2b2-3e94-4096-9ff2-19f7d6b62c6c)

打算看看能不能改回去

**Comment by sunbaigui** [comment]
> > 我发现当前github的版本和之前的版本，对人脸的还原差了很多，生成的人物没有以前像了
> 
> 我觉得是这个pr之后就开始不像原本的人脸了： ![)D1T%Z%R0R0D7OK{8VBKSYB](https://user-images.githubusercontent.com/83486284/268644057-e1e4e2b2-3e94-4096-9ff2-19f7d6b62c6c.png)
> 
> 打算看看能不能改回去

辛苦试下看看，帮忙找找哪里导致的问题，感谢。

**Comment by potoyeee** [comment]
> > 我发现当前github的版本和之前的版本，对人脸的还原差了很多，生成的人物没有以前像了
> 
> 是的，我也是发现这个情况，但是以前的版本使用的参数和现在版本使用参数一样的



> > > 我发现当前github的版本和之前的版本，对人脸的还原差了很多，生成的人物没有以前像了
> > 
> > 
> > 我觉得是这个pr之后就开始不像原本的人脸了： ![)D1T%Z%R0R0D7OK{8VBKSYB](https://user-images.githubusercontent.com/83486284/268644057-e1e4e2b2-3e94-4096-9ff2-19f7d6b62c6c.png)
> > 打算看看能不能改回去
> 
> 辛苦试下看看，帮忙找找哪里导致的问题，感谢。

可以尝试删除本地下载模型，重新下载。我怀疑是新版模型导致的。
