### ISSUE TITLE
是否有计划更新支持mmcv 2.0？

### ISSUE THREAD

**Issue by hoveychen** [modelscope/facechain#320]
图像相关的代码依赖了mmcv1.0的写法，导致只能安装mmcv1.x（也就是mmcv-full包），而不能安装mmcv2

这个事情就很恼人，因为如果使用torch2.0，那么[预编译包只有mmcv2的](https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html)。无论用pip还是mim，安装mmcv-full包都得从头开始编译，得花几个小时。

唯一可能可以解决的，是用conda安装```conda install -c esri mmcv-full```，但是这样会破坏原来pip装好的环境。

**Comment by sunbaigui** [comment]
@ly19965 please reply this at your convenience

**Comment by ly19965** [comment]
1. mmcv比较难安装，pip 或者mim安装失败的话，要按照对应的pytorch和cuda的版本去找对应的whl包安装。
2. 后续需要看下modelscope的升级计划，暂时不会支持
