### ISSUE TITLE
云服务器ubuntu按readme.md的docker方法跑，公网访问不了？

### ISSUE THREAD

**Issue by ronyland** [modelscope/facechain#325]
同一台服务器，同一个端口，我跑其他项目，公网是可以访问的。
跑facechain用命令python3 app.py有如下报错：
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
app.py:897: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['resources/inpaint_template/4.jpg'], ['resources/inpaint_template/5.jpg'], ['resources/inpaint_template/3.jpg'], ['resources/inpaint_template/2.jpg'], ['resources/inpaint_template/1.jpg']]
app.py:993: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
Running on local URL:  http://0.0.0.0:7860

请问如何解决？

**Comment by livehl** [comment]
要改参数 app.py最后一行 demo.queue(status_update_rate=1).launch(share=True)
要改成 demo.queue(status_update_rate=1).launch(share=True,server_name="0.0.0.0")
另外记得把容器端口暴露出来
