### ISSUE TITLE
FeatureRequest/Support Needed: Make LoRa downloadable

### ISSUE THREAD

**Issue by Husky110** [modelscope/facechain#327]
Hi people,

So I was playing around with this tool a bit on Google Colab and got it to train a LoRa for me. Now I would like to use said LoRa in my local SD-WebUI (A1111 + ComfyUI)-environment.
Is there a way to download the trained LoRa as a ckpt- or safetensors-file? 
If yes - where can I find that? If no - can it be implemented? :)

Greetings

P.S.: I do not speak Chinese - please stick to English. :)

**Comment by sunbaigui** [comment]
sure, you can download it by searching *.bin, @hehaha68 maybe you can provide precisely location here.

**Comment by hehaha68** [comment]
We recently made some updates - the trained LoRA models will now be saved in the `qw` folder of the current project (`qw` is the uuid). For example, if you train a character LoRA `person_1` using the base model `leosamsMoonfilm_filmGrain20` the LoRA model file will be saved at `f"{os.path.dirname(os.path.abspath(file))}/qw/ly261666/cv_portrait_model/person_1/pytorch_lora_weights.bin"`. `ly261666/cv_portrait_model` is the model id of the base model `leosamsMoonfilm_filmGrain20`.

If you are using an older version, the `qw` folder was saved under the `/tmp` folder.

**Comment by Husky110** [comment]
@sunbaigui and @hehaha68 - Thanks. I already found that. But what I'm asking for is (in laymen terms) a button in gradio that let's me download a .ckpt- or .safetensors-file - sort of like an "export"-button. Right now I have to use this script (https://github.com/harrywang/finetune-sd/blob/main/convert-to-safetensors.py) to get what I want, but it would be better to be able to export the trained LoRA.  
For a bit background: I don't know where you guys are actually want to go with this. The tool itself is really great and works pretty good, but in the end (in my oppinion) what most people WANT is to use facechain as a tool to create a LoRA and use the created LoRA in A1111 or ComfyUI. Right now facechain feels a bit as if it wants to replace A1111 which (again - only my oppinion :) ) it won't be able to do properly given A1111s standing in the scene right now. It's nice to have a playground to test the created LoRAs but ultimately if I want to create some images with SD and I have to choose between facechain and any other UI (like A1111, Comfy or whatnot) I would go for the latter.  
Please don't get me wrong - I just want to give you constructive feedback. :)

**Comment by sunbaigui** [comment]
> @sunbaigui and @hehaha68 - Thanks. I already found that. But what I'm asking for is (in laymen terms) a button in gradio that let's me download a .ckpt- or .safetensors-file - sort of like an "export"-button. Right now I have to use this script (https://github.com/harrywang/finetune-sd/blob/main/convert-to-safetensors.py) to get what I want, but it would be better to be able to export the trained LoRA right from the webinterface. For a bit background: I don't know where you guys are actually want to go with this. The tool itself is really great and works pretty good, but in the end (in my oppinion) what most people WANT is to use facechain as a tool to create a LoRA and use the created LoRA in A1111 or ComfyUI. Right now facechain feels a bit as if it wants to replace A1111 which (again - only my oppinion :) ) it won't be able to do properly given A1111s standing in the scene right now. It's nice to have a playground to test the created LoRAs but ultimately if I want to create some images with SD and I have to choose between facechain and any other UI (like A1111, Comfy or whatnot) I would go for the latter. Please don't get me wrong - I just want to give you constructive feedback. :)

thanks for your advice, we are developing a plugin for sd-webui now.

**Comment by Husky110** [comment]
> thanks for your advice, we are developing a plugin for sd-webui now.

@sunbaigui - Great! :) But I would still advocate for a separate download-button. In my case my Laptop that is running A1111 and Comfy is too weak to handle the facechain-process (running on a GTX 1070 Mobile - generating images works great tho) so I'm running facechain inside Google Colab, download the trained LoRA and use it locally.
