### ISSUE TITLE
怎么自定义图片的宽和高

### ISSUE THREAD

**Issue by xwzj12138** [modelscope/facechain#330]
固定的图片的大小无法适应现实生活中的照片，现实生活中照片的宽高比列是750*1050的，我要如何修改这个比例呢？

**Comment by sunbaigui** [comment]
we'll work on it for further feature by using super solution tech. @ly19965 FYI.

**Comment by sunbaigui** [comment]
@xwzj12138 currently we've supply four resolution choice, super resolution is not an issue now. choose a higher resolution, and then you can cut the image locally as you want.
