### ISSUE TITLE
国内这一步巨慢 Downloading and preparing dataset imagefolder/processed_labeled to /root/.cache/huggingface...

### ISSUE THREAD

**Issue by montychen** [modelscope/facechain#336]
`Downloading and preparing dataset imagefolder/processed_labeled to /root/.cache/huggingface/datasets/imagefolder/processed_labeled-16d48d4c706d36c4/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f...`

貌似要下载的文件才几百k，也不大，但在国内从阿里云的服务器上运行，巨慢（20多分钟）。  每次上传不同的照片重新训练，都要重新下载。  

请问下载的文件可以复用吗？ 不用每次都重新下载。

**Comment by DevelopmentZheng** [comment]
我也遇到了

**Comment by DevelopmentZheng** [comment]
等吧慢慢等

**Comment by montychen** [comment]
@wangxingjun778  国内Downloading and preparing dataset imagefolder/processed_labeled ... 这步超慢的问题，可以提供个解决的思路吗？ 感谢

**Comment by montychen** [comment]
理解huggingface 被墙导致下载巨慢， 一次还可以。 可是每次上传不同的照片重新训练，都要重新下载。是否可以复，不用每次都重新下载的办法？

**Comment by ly19965** [comment]
@wangxingjun778 代码重构时，可以把所有模型以及相关依赖的下载放在init里面哈

**Comment by madfrog** [comment]
这个问题有解决吗？
