### ISSUE TITLE
Question about the image-limit

### ISSUE THREAD

**Issue by Husky110** [modelscope/facechain#338]
Hi - I have a question regarding the 20-images-limit in gradio.
By editing the code (basically removing lines 445 + 446 in app.py) I can remove the image-limit of 20 images. That seems to be no problem in itself aswell (tested on colab with an A100). Now I wonder why the limit is there in the first place. I've already seen that the face-detection is not able to process every image (presumably because it can't detect the face properly), so I wonder about the implications of removing that image-limit. Shouldn't more image provide better results in the end? (Sorry - I'm still new to SD. :) )

**Comment by sunbaigui** [comment]
currently too much image will not help, because of the fixed human lora dimension (4) there.

**Comment by Husky110** [comment]
@sunbaigui - Ah okay, thank you. :) I even had the effect that more image can lead to broken LoRAs... (had one with 20 images and one with 33 which included the same 20 images as the first one) and the results were... well... scary... :D
