### ISSUE TITLE
面部旋转 face rotation的作用

### ISSUE THREAD

**Issue by zhangxiying** [modelscope/facechain#339]
请问各位老师们面部旋转的作用是什么呢，我执行了一下代码得到的处理结果也是整个图片进行了旋转，只是角度和图片旋转设定的3个角度不同，感觉没什么作用
![image](https://github.com/modelscope/facechain/assets/22190543/8a26b8fc-eb5f-49d8-be63-2cfdbd0c2d21)
![旋转后](https://github.com/modelscope/facechain/assets/22190543/67c75301-b1d8-4a8e-84b7-5ebb6bd1016d)

**Comment by sunbaigui** [comment]
@ly19965 @You-Cun 请答复下。

**Comment by ly19965** [comment]
面部旋转模型的作用是判断图片中的人脸是否朝上，不是的话会旋转图片90，180, 270度使人脸朝上。

**Comment by zhangxiying** [comment]
> 面部旋转模型的作用是判断图片中的人脸是否朝上，不是的话会旋转图片90，180, 270度使人脸朝上。

老师我问的是面部旋转，不是整体图片的旋转，您看我执行的结果，显然不是旋转90度
