### ISSUE TITLE
edge_tts问题导致无法正常部署？

### ISSUE THREAD

**Issue by frainer** [modelscope/facechain#346]
安装部署到这一步就错误退出了：
import edge_tts
ModuleNotFoundError: No module named 'edge_tts'

**Comment by wwdok** [comment]
@frainer 人物视频说话标签页需要依赖edge_tts，请您用`pip install edge-tts`安装一下，完整的安装教程见：https://github.com/modelscope/facechain/blob/main/doc/installation_for_talkinghead_ZH.md#3%E5%AE%89%E8%A3%85ffmpeg

**Comment by frainer** [comment]
> @frainer 人物视频说话标签页需要依赖edge_tts，请您用`pip install edge-tts`安装一下，完整的安装教程见：https://github.com/modelscope/facechain/blob/main/doc/installation_for_talkinghead_ZH.md#3%E5%AE%89%E8%A3%85ffmpeg

好的问题已解决，感谢！
