### ISSUE TITLE
the training pipeline about style lora

### ISSUE THREAD

**Issue by Delicious-Bitter-Melon** [modelscope/facechain#348]
Thanks for your excellent work. Do you have a plan to release the training script about how to train a style lora?

**Comment by sunbaigui** [comment]
> Thanks for your excellent work. Do you have a plan to release the training script about how to train a style lora?

sure, we'll release it in the near future.

**Comment by yerang823** [comment]
> > Thanks for your excellent work. Do you have a plan to release the training script about how to train a style lora?
> 
> sure, we'll release it in the near future.

Thanks for your excellent work, too.
When do you expect to release it ?

**Comment by sunbaigui** [comment]
> > > Thanks for your excellent work. Do you have a plan to release the training script about how to train a style lora?
> > 
> > 
> > sure, we'll release it in the near future.
> 
> Thanks for your excellent work, too. When do you expect to release it ?

we'll try our best to release it in 12.30 roughly.

**Comment by mountlin** [comment]
@sunbaigui Thank you for your excellent work on this project. I noticed that the training script for style LoRA is on the to-do list, and many of us are eagerly anticipating its release. Could you please provide an update on the progress? It would be greatly appreciated if you could prioritize this feature, as the ability to extend style LoRA would greatly enrich the applications of this project.

**Comment by sunbaigui** [comment]
A small development team has recently been established to expedite the release of this feature. @You-Cun FYI.

**Comment by You-Cun** [comment]
We have established the codebase, and are now managing to adjust the default training options to simplify usage. The training pipeline is expected to be released in 07.01 roughly.

**Comment by sosohungry** [comment]
I'm looking forward to the release of the training script.

**Comment by sunbaigui** [comment]
training pipeline merged #583 , enjoy :-).
