### ISSUE TITLE
app.py第1114行，启动可能报错，打开文件没有指定编码

### ISSUE THREAD

**Issue by terrellhu** [modelscope/facechain#349]
修改1113行with open(file_path, "r") as f:
改为：with open(file_path, "r", encoding="utf8") as f:

**Comment by wwdok** [comment]
这个PR（https://github.com/modelscope/facechain/pull/344/files ）里有提到，但还没合并
![image](https://github.com/modelscope/facechain/assets/43233772/74499fc3-89d0-4236-94ac-e0ea5980d09a)

**Comment by sunbaigui** [comment]
@terrellhu merged, #344 , please try it again.
