### ISSUE TITLE
你好，我看代码有一些小问题，能够公开拉取嘛，我们一起维护这个项目

### ISSUE THREAD

**Issue by 8baby8** [modelscope/facechain#354]
我想加入到项目的维护当中

**Comment by yingdachen** [comment]
项目是开源公开的，欢迎通过pull request来提交代码改动。

现在是pull request提交过程遇到什么问题吗

**Comment by 8baby8** [comment]
我拉取的时候，是这种情况




My,drame
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "modelscope/facechain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [modelscope/facechain] 你好，我看代码有一些小问题，能够公开拉取嘛，我们一起维护这个项目 (Issue #354)





 
项目是开源公开的，欢迎通过pull request来提交代码改动。
 
现在是pull request提交过程遇到什么问题吗

**Comment by yingdachen** [comment]
这个看起来没有什么信息量。请贴一下运行

git clone git@github.com:modelscope/facechain.git

的结果

**Comment by sunbaigui** [comment]
not a real issue. closed.
