### ISSUE TITLE
win10下面如何使用GPU训练和出图

### ISSUE THREAD

**Issue by hyperbrain1980** [modelscope/facechain#358]
在win10能正常运行程序，训练和跑图都不走GPU直接使用CPU，导致训练和出图时间巨慢无比，请问在程序中什么地方修改可以让系统默认跑GPU

**Comment by wangxingjun778** [comment]
torch.cuda.is_available() 查看一下本地的cuda环境是否生效； 
terminal 再看一下CUDA_VISIBLE_DEVICES的值： echo $CUDA_VISIBLE_DEVICES
如果该环境变量没有被设置，则执行： export CUDA_VISIBLE_DEVICES='0'

大体思路就是，能够被torch 探测到GPU即可。

**Comment by ultimatech-cn** [comment]
应该是安装的torch版本不对，如果是N卡，需要安装CUDA

```
pip uninstall torch
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```
验证torch，可以直接进入python
```
import torch # 如果pytorch安装成功即可导入
print(torch.cuda.is_available()) # 查看CUDA是否可用
print(torch.cuda.device_count()) # 查看可用的CUDA数量
print(torch.version.cuda) # 查看CUDA的版本号
```

**Comment by hyperbrain1980** [comment]
> 应该是安装的torch版本不对，如果是N卡，需要安装CUDA
> 
> ```
> pip uninstall torch
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> 验证torch，可以直接进入python
> 
> ```
> import torch # 如果pytorch安装成功即可导入
> print(torch.cuda.is_available()) # 查看CUDA是否可用
> print(torch.cuda.device_count()) # 查看可用的CUDA数量
> print(torch.version.cuda) # 查看CUDA的版本号
> ```

(facechain) D:\sdAI\facechain>python
Python 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> print(torch.cuda.device_count())
1
>>> print(torch.version.cuda)
11.8
>>>

**Comment by hyperbrain1980** [comment]
![image](https://github.com/modelscope/facechain/assets/130879298/449cb579-88ee-477d-b1d1-cd7d7e0de546)
用的是N卡3060

**Comment by hyperbrain1980** [comment]
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

昨晚用这个命令安装成功了：pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by hyperbrain1980** [comment]
训练脚本中有没有选择GPU还是CPU的地方吗？以前训练YOLO的时候记得脚本中可以修改

**Comment by ultimatech-cn** [comment]
默认应该用cuda，如果你facechain用的是上面相同的python环境的。
训练用的是accelerate，你看看是不是有系统里面默认的配置影响。
另外你可以尝试设置环境变量
CUDA_VISIBLE_DEVICES=0

**Comment by hyperbrain1980** [comment]
设置：CUDA_VISIBLE_DEVICES=0起作用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "modelscope/facechain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月14日(星期六) 上午8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [modelscope/facechain] win10下面如何使用GPU训练和出图 (Issue #358)





 
默认应该用cuda，如果你facechain用的是上面相同的python环境的。
 训练用的是accelerate，你看看是不是有系统里面默认的配置影响。
 另外你可以尝试设置环境变量
 CUDA_VISIBLE_DEVICES=0

**Comment by sunbaigui** [comment]
closed as solved.
