### ISSUE TITLE
在魔塔上按照文档教程训练命令行启动报错，请问什么原因呢？

### ISSUE THREAD

**Issue by jqsl2012** [modelscope/facechain#36]
![image](https://github.com/modelscope/facechain/assets/6802595/ccfbbc0a-b7b3-4fe4-9e28-eafd8be75e91)

**Comment by tastelikefeet** [comment]
PYTHONPATH=. sh train_lora.sh "ly261666/cv_portrait_model" "v2.0" "film/film" "./imgs" "./processed" "./output"
增加PYTHONPATH=.
