### ISSUE TITLE
选择风格的时候报错是：IndexError:list index out of range

### ISSUE THREAD

**Issue by hyperbrain1980** [modelscope/facechain#360]
![image](https://github.com/modelscope/facechain/assets/130879298/67a873a3-18e1-4da1-a582-cb69bbee2f8c)

**Comment by AXYZdong** [comment]
将`app.py`中的evt.value改为evt.value[1]

**Comment by hyperbrain1980** [comment]
> 将`app.py`中的evt.value改为evt.value[1]

使用以上方法，问题已解决

**Comment by sunbaigui** [comment]
merged PR. issue close. thanks for your contribution @wlchn
