### ISSUE TITLE
*尝试在本地部署的stable diffusion上安装和使用facechain插件* Lora训练素材打好标，即将开始训练的时候报错提示指定的文件无法找到

### ISSUE THREAD

**Issue by SakanakoChan** [modelscope/facechain#368]
以下是报错提示

2023-10-18 23:42:38,374 - modelscope - WARNING - task skin-retouching-torch input definition is missing
2023-10-18 23:42:39,766 - modelscope - WARNING - task skin-retouching-torch output keys are missing
000.jpg 0.966441884636879
1girl, black_hair, lips, looking_at_viewer, realistic, simple_background, solo, white_background
[['1girl', 'black_hair', 'lips', 'looking_at_viewer', 'realistic', 'simple_background', 'solo', 'white_background']]
0.png a handsome man
instance_data_dir E:\sd-webui-aki-v4.1\extensions\facechain\worker_data\qw\training_data\ly261666/cv_portrait_model\test222
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\sd-webui-aki-v4.1\extensions\facechain\app.py", line 545, in run
    train_lora_fn(base_model_path=base_model_path,
  File "E:\sd-webui-aki-v4.1\extensions\facechain\app.py", line 110, in train_lora_fn
    subprocess.run(command, check=True)
  File "E:\sd-webui-aki-v4.1\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\sd-webui-aki-v4.1\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\sd-webui-aki-v4.1\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

——

以下是我安装过的所有pip库

Package                 Version
----------------------- ------------------
absl-py                 1.4.0
accelerate              0.21.0
addict                  2.4.0
aenum                   3.1.12
aiofiles                23.1.0
aiohttp                 3.8.4
aiosignal               1.3.1
albumentations          1.3.1
aliyun-python-sdk-core  2.14.0
aliyun-python-sdk-kms   2.16.2
altair                  4.2.2
antlr4-python3-runtime  4.9.3
anyio                   3.6.2
async-timeout           4.0.2
attrs                   23.1.0
av                      10.0.0
basicsr                 1.4.2
beautifulsoup4          4.12.2
blendmodes              2022
boltons                 23.0.0
cachetools              5.3.0
certifi                 2023.7.22
cffi                    1.15.1
chardet                 4.0.0
charset-normalizer      3.1.0
clean-fid               0.1.35
click                   8.1.3
clip                    1.0
colorama                0.4.6
coloredlogs             15.0.1
contourpy               1.0.7
controlnet-aux          0.0.6
crcmod                  1.7
cryptography            41.0.4
cssselect2              0.7.0
cycler                  0.11.0
Cython                  3.0.2
datasets                2.13.0
deprecation             2.1.0
diffusers               0.21.4
dill                    0.3.6
easydict                1.10
edge-tts                6.1.8
einops                  0.4.1
entrypoints             0.4
facexlib                0.3.0
fastapi                 0.94.0
ffmpy                   0.3.0
filelock                3.12.0
filterpy                1.4.5
flatbuffers             23.3.3
font-roboto             0.0.1
fonts                   0.0.3
fonttools               4.39.3
freetype-py             2.3.0
frozenlist              1.3.3
fsspec                  2023.4.0
ftfy                    6.1.1
future                  0.18.3
fvcore                  0.1.5.post20221221
gast                    0.5.4
gdown                   4.7.1
gfpgan                  1.3.8
gitdb                   4.0.10
GitPython               3.1.32
google-auth             2.17.3
google-auth-oauthlib    1.0.0
gradio                  3.41.2
gradio_client           0.5.0
grpcio                  1.54.0
h11                     0.12.0
httpcore                0.15.0
httpx                   0.24.0
huggingface-hub         0.14.1
humanfriendly           10.0
idna                    2.10
ifnude                  0.0.3
imageio                 2.28.1
imageio-ffmpeg          0.4.9
importlib-metadata      6.8.0
importlib-resources     6.1.0
inflection              0.5.1
insightface             0.7.3
iopath                  0.1.9
Jinja2                  3.1.2
jmespath                0.10.0
joblib                  1.3.2
jsonmerge               1.8.0
jsonschema              4.17.3
kiwisolver              1.4.4
kornia                  0.6.7
lark                    1.1.2
lazy_loader             0.2
lightning-utilities     0.8.0
linkify-it-py           2.0.2
llvmlite                0.40.0
lmdb                    1.4.1
lpips                   0.1.4
lxml                    4.9.2
Markdown                3.4.3
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mdit-py-plugins         0.3.3
mdurl                   0.1.2
mediapipe               0.10.0
mmcv-full               1.7.1
mmdet                   2.26.0
mmengine                0.9.0
model-index             0.1.11
modelscope              1.9.2
mpmath                  1.3.0
multidict               6.0.4
multiprocess            0.70.14
mypy-extensions         1.0.0
networkx                3.1
numba                   0.57.0
numexpr                 2.8.7
numpy                   1.23.5
oauthlib                3.2.2
omegaconf               2.2.3
onnx                    1.14.0
onnxruntime             1.15.0
open-clip-torch         2.20.0
opencv-contrib-python   4.7.0.72
opencv-python           4.8.0.76
opencv-python-headless  4.8.1.78
opendatalab             0.0.10
openmim                 0.3.9
openxlab                0.0.27
ordered-set             4.1.0
orjson                  3.8.11
oss2                    2.17.0
packaging               23.1
pandas                  2.0.1
piexif                  1.1.3
Pillow                  9.5.0
PIMS                    0.6.0
pip                     23.3
portalocker             2.7.0
prettytable             3.9.0
protobuf                3.20.2
psutil                  5.9.5
pyarrow                 13.0.0
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pycairo                 1.23.0
pycocotools             2.0.7
pycparser               2.21
pycryptodome            3.19.0
pydantic                1.10.7
pydub                   0.25.1
pyfunctional            1.4.3
Pygments                2.15.1
pyparsing               3.0.9
pyre-extensions         0.0.29
pyreadline3             3.4.1
pyrsistent              0.19.3
PySocks                 1.7.1
python-dateutil         2.8.2
python-dotenv           1.0.0
python-multipart        0.0.6
python-slugify          8.0.1
pytorch-lightning       1.9.4
pytz                    2023.3
PyWavelets              1.4.1
pywin32                 306
PyYAML                  6.0
qudida                  0.0.4
realesrgan              0.3.0
regex                   2023.5.5
reportlab               4.0.0
requests                2.28.2
requests-oauthlib       1.3.1
resize-right            0.0.2
rich                    13.4.2
rlPyCairo               0.2.0
rsa                     4.9
safetensors             0.3.1
scikit-image            0.21.0
scikit-learn            1.3.1
scipy                   1.10.1
semantic-version        2.10.0
Send2Trash              1.8.2
sentencepiece           0.1.99
setuptools              60.2.0
simplejson              3.19.2
six                     1.16.0
slicerator              1.1.0
slugify                 0.0.1
smmap                   5.0.0
sniffio                 1.3.0
sortedcontainers        2.4.0
sounddevice             0.4.6
soupsieve               2.4.1
starlette               0.26.1
svglib                  1.5.1
sympy                   1.11.1
tabulate                0.9.0
tb-nightly              2.14.0a20230507
tensorboard-data-server 0.7.0
termcolor               2.3.0
terminaltables          3.1.10
text-unidecode          1.3
threadpoolctl           3.2.0
tifffile                2023.4.12
timm                    0.9.2
tinycss2                1.2.1
tokenizers              0.13.3
tomesd                  0.1.3
tomli                   2.0.1
toolz                   0.12.0
torch                   2.0.1+cu118
torchdiffeq             0.2.3
torchmetrics            0.11.4
torchsde                0.2.5
torchvision             0.15.2+cu118
tqdm                    4.65.0
trampoline              0.1.2
transformers            4.30.2
typing_extensions       4.5.0
typing-inspect          0.8.0
tzdata                  2023.3
uc-micro-py             1.0.2
urllib3                 1.26.15
uvicorn                 0.22.0
wcwidth                 0.2.6
webencodings            0.5.1
websockets              11.0.3
Werkzeug                2.3.3
wheel                   0.40.0
xformers                0.0.20
xxhash                  3.4.1
yacs                    0.1.8
yapf                    0.33.0
yarl                    1.9.2
zipp                    3.17.0

——

另外

使用系统为windows 11 专业版 22H2
webui 版本为 1.6.0
python 3.10.11
torch 2.0.1
cuda 11.8
xformers 0.0.20
gradio 3.41.2

很头疼，折腾了一天也没能让facechain在本地的stable diffusion上面跑起来，希望大佬可以救救我 :(((

**Comment by ly19965** [comment]
FaceChain 答疑群已解决

**Comment by MarkRenZC** [comment]
> FaceChain 答疑群已解决

求问解决方法在哪里可以找到
