### ISSUE TITLE
FaceChain error A1111

### ISSUE THREAD

**Issue by Adzido** [modelscope/facechain#374]
> *** Error executing callback ui_tabs_callback for C:\Users\AdziOo\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
>     Traceback (most recent call last):
>       File "C:\Users\AdziOo\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
>         res += c.callback() or []
>       File "C:\Users\AdziOo\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
>         import app
>       File "C:\Users\AdziOo\stable-diffusion-webui\extensions\facechain\app.py", line 19, in <module>
>         from facechain.inference_inpaint import GenPortrait_inpaint
>       File "C:\Users\AdziOo\stable-diffusion-webui\extensions\facechain\facechain\inference_inpaint.py", line 13, in <module>
>         from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, \
>     ImportError: cannot import name 'StableDiffusionControlNetInpaintPipeline' from 'diffusers' (C:\Users\AdziOo\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)

I installed it to A1111 and then after restart this.
Any idea?

**Comment by formulake** [comment]
Facing the same issue on installation in SD-Webui

>  C:\Users\kunal\.cache\modelscope\ast_indexer
> 2023-10-21 19:17:31,642 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 d4b4a4c301825728426983ed5781e174 and a total number of 943 components indexed
> *** Error executing callback ui_tabs_callback for F:\Tools\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
>     Traceback (most recent call last):
>       File "F:\Tools\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
>         res += c.callback() or []
>       File "F:\Tools\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
>         import app
>       File "F:\Tools\stable-diffusion-webui\extensions\facechain\app.py", line 19, in <module>
>         from facechain.inference_inpaint import GenPortrait_inpaint
>       File "F:\Tools\stable-diffusion-webui\extensions\facechain\facechain\inference_inpaint.py", line 13, in <module>
>         from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, \
>     ImportError: cannot import name 'StableDiffusionControlNetInpaintPipeline' from 'diffusers' (F:\Tools\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)

**Comment by Extraltodeus** [comment]
same here even after updating the transformers library to version 4.34.1

**Comment by MarkRenZC** [comment]
Updating the diffusers library to version 0.21.4 may solve this error

**Comment by wenmengzhou** [comment]
https://github.com/huggingface/diffusers/issues/3140  it seems to be the bug of diffusers, please upgrade to newer version
