### ISSUE TITLE
FileNotFoundError: Couldn't find a dataset script

### ISSUE THREAD

**Issue by Acephalia** [modelscope/facechain#376]
Hello, thank you for the great work on this extension. I am unfortunately getting an odd file not found error on A1111. Some help would be greatly appreciated. Thank You!

```
raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at S:\stable-diffusion-webui\extensions\facechain\worker_data\qw\training_data\ly261666\cv_portrait_model\person1_labeled\person1_labeled.py or any data file in the same directory.
```

**Comment by ly19965** [comment]
@wenmengzhou  please reply this when you're free.

**Comment by LikeGiver** [comment]
same problem on A1111

**Comment by wenmengzhou** [comment]
can you paste the running log here？

**Comment by dsully** [comment]
Same problem here. Via automatic1111 web ui or running the script directly.
