### ISSUE TITLE
docker: Error response from daemon: No command specified.  

### ISSUE THREAD

**Issue by Hansyvea** [modelscope/facechain#378]
Hi dev! I am using WSL2 to run the docker images with the following command:
```bash
docker run --gpus=all --name facechain --ipc=host --rm -p 7860:7860 -it --volume /mnt/c/Code:/workspace registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.0 
```
However, it returns the error written in the title. 
The cuda version on the host machine is this: Driver Version: 545.84  CUDA Version: 12.3. 
Is it because of the CUDA version difference?

**Comment by wangxingjun778** [comment]
> Hi dev! I am using WSL2 to run the docker images with the following command:
> 
> ```shell
> docker run --gpus=all --name facechain --ipc=host --rm -p 7860:7860 -it --volume /mnt/c/Code:/workspace registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.0 
> ```
> 
> However, it returns the error written in the title. The cuda version on the host machine is this: Driver Version: 545.84 CUDA Version: 12.3. Is it because of the CUDA version difference?

Yes, the cuda version mismatch, try to align the version between docker image and your host.

**Comment by sunbaigui** [comment]
closed as replied a solution, if there's any further question, feel free to reopen it.
