### ISSUE TITLE
Train Error, error when load_dataset

### ISSUE THREAD

**Issue by hwenjun18** [modelscope/facechain#388]
An error occur when run function load_dataset,
`
        dataset = load_dataset(
            args.dataset_name,
            args.dataset_config_name,
            cache_dir=args.cache_dir,
        )`

`    dataset = load_dataset(
  File "/opt/conda/envs/sd/lib/python3.10/site-packages/datasets/load.py", line 1810, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/opt/conda/envs/sd/lib/python3.10/site-packages/datasets/builder.py", line 1128, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.`

**Comment by azouever** [comment]
maybe here https://github.com/modelscope/facechain/issues/383#issuecomment-1780485263

**Comment by ginobilinie** [comment]
I have encountered the same question, do you have any solutions for it?

**Comment by LikeGiver** [comment]
@ginobilinie useful for me!

**Comment by sunbaigui** [comment]
closed as solved.
