### ISSUE TITLE
是否支持使用自己训练好的人脸Lora

### ISSUE THREAD

**Issue by BuQingYan** [modelscope/facechain#389]
请问是否支持使用自己在StableDiffusion中使用的人脸Lora模型，而不用重复训练

**Comment by ultimatech-cn** [comment]
应该可以,你把lora文件放到facechainlora的目录下,看看在界面上能不能刷出来.
不过lora生成完, facechain还是会换脸的,相当于lora模型其实起的作用会减弱

**Comment by sunbaigui** [comment]
closed as replied. Feel free to reopen it, if you have further question.
