### ISSUE TITLE
mmcv和modelscope版本问题

### ISSUE THREAD

**Issue by RyanzW0521** [modelscope/facechain#39]
目前看上去modelscop库里的很多task依然是基于mmcv<2.0.0编写的，要修改大量的地方，比如`from mmcv.parallel import MMDataParallel` ，后续会有更新吗

**Comment by wenmengzhou** [comment]
您好，当前使用modelscope需要使用mmcv-full，也就是mmcv 1.x版本，后续我们会看一下mmcv 2.x的升级可行性

**Comment by jjiikkkk** [comment]
这个仓库无法用啊

**Comment by yingdachen** [comment]
> 这个仓库无法用啊

the official recommended setup is with mmcv-1.7. please refer to the readme and documetation.
