### ISSUE TITLE
点击训练照片时报错

### ISSUE THREAD

**Issue by seekme-ai** [modelscope/facechain#391]
[WinError 6] 句柄无效。
<img width="372" alt="chrome_MYgsUuWjJi" src="https://github.com/modelscope/facechain/assets/8808091/dfca73f5-e76c-44c6-aa92-414c0d1b591e">
<img width="452" alt="chrome_SDAAFipjmJ" src="https://github.com/modelscope/facechain/assets/8808091/2cf40382-10c0-4676-9090-3d0ce49ee6db">

**Comment by ultimatech-cn** [comment]
你把后台的报错信息贴上来看看.
我遇到几个问题都是和acclerate有关. 把app.py里的 'accelerate', 'launch', f'{project_dir}/facechain/train_text_to_image_lora.py', 改成   'python' ,  f'{project_dir}/facechain/train_text_to_image_lora.py',

**Comment by sunbaigui** [comment]
closed. information is not enough to reproduce it.
