### ISSUE TITLE
How external developers can contribute code?

### ISSUE THREAD

**Issue by Bitterdhg** [modelscope/facechain#393]
Thank you for the wonderful repository. I would like to contribute some open-source models to this repository. Are there any tasks available for external developers to claim?

**Comment by sunbaigui** [comment]
> Thank you for the wonderful repository. I would like to contribute some open-source models to this repository. Are there any tasks available for external developers to claim?

sure, you are wanted. you can join us via the dingding code below:
<img width="181" alt="image" src="https://github.com/modelscope/facechain/assets/2352602/1987fc60-67c2-4bfa-93a0-3c24536b3454">
