### ISSUE TITLE
Lower the GPU memory restriction?

### ISSUE THREAD

**Issue by cgjosephlee** [modelscope/facechain#396]
I was able to run lora training and t2i inference using A4000 16G (#125), shall we remove or lower the criteria of GPU memory checking (#293)?

**Comment by cdcdx** [comment]
I can run even with a 12G graphics card.

**Comment by ultimatech-cn** [comment]
Try it.

**Comment by sunbaigui** [comment]
> I was able to run lora training and t2i inference using A4000 16G (#125), shall we remove or lower the criteria of GPU memory checking (#293)?

@wangxingjun778 please check on this.
@cgjosephlee if you are interested to contribute, you can join us via the code in #393 .

**Comment by ly19965** [comment]
Please refer to https://github.com/modelscope/facechain/issues/424
