### ISSUE TITLE
出的效果图与本人相差甚远？

### ISSUE THREAD

**Issue by wjpstudy** [modelscope/facechain#40]
按照Readme提示，在notebook上部署体验了下，感受是：跟本人五官不说毫无关系吧，也是相差甚远，几乎看不出来是本人，可是样例中效果来看没有这种问题，请问需要调节哪些参数从而增加体验感？

**Comment by sunbaigui** [comment]
建议你用2~3张手机自拍图进去做训练。不要用ps过的或者人脸分辨率小或者模糊的。

**Comment by jiqizaisikao** [comment]
下面这些效果不需要使用时候针对性训练，只需要一张照片，一个模版（一键换头，换脸型）
![WechatIMG54](https://github.com/modelscope/facechain/assets/16893734/03c08111-4684-4610-a930-7a62288c8b0a)
![WechatIMG55](https://github.com/modelscope/facechain/assets/16893734/e7cb7565-921e-476f-9129-235df9d70967)

这是我修改的开源代码，自己训练的模型，已经在微信小程序《换影CP》上线，需要不小的资源进行训练（相对我自己），我现在已经没有足够的资源进行更多优化和训练了，希望能找到朋友进行共同研究和合作

**Comment by jiqizaisikao** [comment]
但是我发现有些问题就是崩快概率相对较高，可能是因为inpainting限制因素太多导致了过多的冲突，而妙鸭这种文生图就具有更大的容错空间。

**Comment by jiqizaisikao** [comment]
我使用的参考图片还不是真人，是用facechain 合成的：
![test2](https://github.com/modelscope/facechain/assets/16893734/45f1302b-a581-4019-abe6-4f15178b3a22)

**Comment by sunbaigui** [comment]
> 下面这些效果不需要使用时候针对性训练，只需要一张照片，一个模版（一键换头，换脸型） ![WechatIMG54](https://user-images.githubusercontent.com/16893734/265146742-03c08111-4684-4610-a930-7a62288c8b0a.jpeg) ![WechatIMG55](https://user-images.githubusercontent.com/16893734/265146800-e7cb7565-921e-476f-9129-235df9d70967.jpeg)
> 
> 这是我修改的开源代码，自己训练的模型，已经在微信小程序《换影CP》上线，需要不小的资源进行训练（相对我自己），我现在已经没有足够的资源进行更多优化和训练了，希望能找到朋友进行共同研究和合作

看起来你在实现inpainting路线。目前最新版本上也支持了inpainting beta版本。欢迎你在这个上面继续优化，来贡献开源代码啦。
