### ISSUE TITLE
部署到sd webui上，用ui界面进行多次训练和生成，内存一直不释放，会把内存慢慢打爆，我的机器128G内存都不够，还是会爆，是不是哪块没释放内存啊

### ISSUE THREAD

**Issue by Thompshon** [modelscope/facechain#400]

**Comment by wenmengzhou** [comment]
是在linux上还是windows上？

**Comment by Thompshon** [comment]
> 是在linux上还是windows上？

在linux上

**Comment by wenmengzhou** [comment]
请问大概运行每次会上涨多少内存，一般多少次后会oom，我们复现下

**Comment by metrosir** [comment]
![image](https://github.com/modelscope/facechain/assets/8962001/6a06c194-d0ea-4a61-a723-bbe9ef1f5da3)
从我这边的训练过程中内存的指标变化情况来看，训练完以后是会自动释放的，请再确认下是使用FaceChain插件造成的还是因为使用了webUI中其他的插件造成的，还可以看下在使用FaceChain的过程中是否还同时在使用webUI中的其他的功能造成的这个问题

**Comment by Thompshon** [comment]
sorry，我的问题，关掉了
