### ISSUE TITLE
Got error when running "python3 app.py"

### ISSUE THREAD

**Issue by wczqhd** [modelscope/facechain#401]
Traceback (most recent call last):
  File "app.py", line 1422, in <module>
    inference_talkinghead()
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/gradio_client/serializing.py", line 44, in input_api_info
    types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2)  # type: ignore
KeyError: 'type'

I have change my gradio to 3.25.0, and got this error.

**Comment by ly19965** [comment]
@wwdok please check on this when you are free

**Comment by wwdok** [comment]
@wczqhd Do you solve the problem now ? 
If not, could you please provide deeper infomations like what is the final line of code in inference_talkinghead() that throws this error ?
I search `api_info.get("serialized_input", [api_info["info"]["type"]] * 2)` in google, find there are same issues, it seems ralated to version of gradio and gradio_client:
![image](https://github.com/modelscope/facechain/assets/43233772/81600234-32d4-4b92-a018-16a5287e952f)

**Comment by lvsh2012** [comment]
pip install gradio==3.50.2  

解决问题

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
