### ISSUE TITLE
Add a way to uninstall it , now it wont work as webui extension cause of mmcv error so i have 10 GB unused files as leftovers 

### ISSUE THREAD

**Issue by 2blackbar** [modelscope/facechain#409]
Can you at least tell me where it downloaded all the files so i can remove them manually ? This is uncool, its 10GB maybe more

**Comment by hassan-sd** [comment]
I've seen a bunch of the content downloaded to C:\Users\xxxxx\.cache\modelscope in case you want to remove them

**Comment by wenmengzhou** [comment]
C:\Users\xxxxx.cache\modelscope

**Comment by wenmengzhou** [comment]
try to execute  pip install openmim and mom install mmcv==1.7.1
