### ISSUE TITLE
Won't create tab | Error executing callback ui_tabs_callback

### ISSUE THREAD

**Issue by Trestantin** [modelscope/facechain#419]
Hello,

I have this error, i think something with char coding.
I've tried to solve it:

- checked the coding of style.css (UTF-8)
- tried to add this:
with open('style.css', 'r', encoding='utf-8') as css_file:
    self.css = css_file.read()

•   version: [v1.6.0-2-g4afaaf8a]
•  python: 3.10.11  
•  torch: 2.0.1+cu118  
•  xformers: 0.0.20  
•  gradio: 3.41.2

*** Error executing callback ui_tabs_callback for E:\AI_generate\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "E:\AI_generate\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "E:\AI_generate\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "E:\AI_generate\stable-diffusion-webui\extensions\facechain\app.py", line 1434, in <module>
        with gr.Blocks(css='style.css') as demo:
      File "E:\AI_generate\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 711, in __init__
        self.css = css_file.read()
      File "C:\Program Files\Python310\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 17114: character maps to <undefined>

**Comment by bboylalu** [comment]
Go to Control Panel -> Region -> Change system locale... -> check Beta: Use Unicode UTF-8 for worldwide language support -> click Ok -> reboot Windows. I suppose the error is because of the Chinese text, but it works for me after I checked that box.
![image](https://github.com/modelscope/facechain/assets/628193/6b850bad-510a-400d-a230-431520142f8d)

**Comment by xys123** [comment]
> Go to Control Panel -> Region -> Change system locale... -> check Beta: Use Unicode UTF-8 for worldwide language support -> click Ok -> reboot Windows. I suppose the error is because of the Chinese text, but it works for me after I checked that box.转到控制面板 -> 区域 -> 更改系统区域设置... ->检查 Beta：使用 Unicode UTF-8 获得全球语言支持 ->单击确定 ->重新启动 Windows。我想这个错误是因为中文文本，但在我选中该框后它对我有用。 ![image](https://private-user-images.githubusercontent.com/628193/303650278-6b850bad-510a-400d-a230-431520142f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTM5NDMsIm5iZiI6MTcxNDAxMzY0MywicGF0aCI6Ii82MjgxOTMvMzAzNjUwMjc4LTZiODUwYmFkLTUxMGEtNDAwZC1hMjMwLTQzMTUyMDE0MmY4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMjU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTgyYWZjYzgzN2I4YTZiMTkwYjZkYmZiOTMxYTM0ZGNiODMwMWFkYTY5ZTkyMTI1MjUwZTY1ZjdlNGMyNzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UYPjA6HGtAL7q0-H9av7sOgt0rlQgGToJ8a1Q_FEmZo)

非常好方法，爱来自瓷器

**Comment by Jane8899** [comment]
> Go to Control Panel -> Region -> Change system locale... -> check Beta: Use Unicode UTF-8 for worldwide language support -> click Ok -> reboot Windows. I suppose the error is because of the Chinese text, but it works for me after I checked that box. ![image](https://private-user-images.githubusercontent.com/628193/303650278-6b850bad-510a-400d-a230-431520142f8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzM1MzcsIm5iZiI6MTcxNjIzMzIzNywicGF0aCI6Ii82MjgxOTMvMzAzNjUwMjc4LTZiODUwYmFkLTUxMGEtNDAwZC1hMjMwLTQzMTUyMDE0MmY4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxOTI3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmFhMTUzNjM2NmEwNDA0M2U0NDA0MDM4NjBhNTJmMDIzZmZkOTFlOWY4MDdhYmM4YTAyMWIwMjgxNGYzYzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iD7wHQ4tdTUU3quhSL1Oq2FbCqgXvuDV05Bzbo1vcnU)

Thank you very much. Work for me!

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
