### ISSUE TITLE
datasets.builder - HF google storage unreachable. Downloading and preparing it from source

### ISSUE THREAD

**Issue by zhangxiying** [modelscope/facechain#420]
训练时（2张图片）卡了10多分钟，出现了 WARNING - datasets.builder - HF google storage unreachable. Downloading and preparing it from source这样的警告，看提示是去huggingface下载数据集了，不知道为什么要下载什么数据，之前训练没有出现过这个警告，训练比较快的完成了，最近出现了这个警告，麻烦看一下如何避免去网络下载
![image](https://github.com/modelscope/facechain/assets/22190543/e53fa543-28c2-44b2-947a-dcd3c8e8c0b0)

**Comment by zhangxiying** [comment]
![image](https://github.com/modelscope/facechain/assets/22190543/ccb80334-2e17-47da-994d-7412a347c918)

**Comment by Walin1349** [comment]
我也遇到了和这个问题，解决了吗？

**Comment by zhangxiying** [comment]
> 我也遇到了和这个问题，解决了吗？

设置了这个环境变量：export  HF_DATASETS_OFFLINE=1
不知道会有什么影响，不知道去huggingface下载了什么数据集
