### ISSUE TITLE
'-' and '.' cannot start or end the name, max length is 96

### ISSUE THREAD

**Issue by yamosin** [modelscope/facechain#423]
System:Windows 11 torch 2.0.0 cuda 11.8
Hello
When use fixed templates portrait mode get this error (train and style mode is fine)
Seem like an absolute path problem, or a path length problem.

`huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\sd-webui-aki-v4.4\.cache\modelscope\hub\damo\face_chain_control_model\model/ControlNet'.`

**Comment by willis** [comment]
I also have this problem
