### ISSUE TITLE
Stable Diffusion extension won't install

### ISSUE THREAD

**Issue by recycleaway7** [modelscope/facechain#425]
When I click Install for FaceChain on the Extensions tab of Automatic1111 it does a never-ending "Processing..." step. That step normally takes a few seconds but I've let it sit for 10+ minutes and it never finishes. It builds a FaceChain folder in my extensions folder, but whenever that folder exists my .bat startup gets stuck and my Stable Diffusion won't startup unless I delete that FaceChain folder. I've also tried installing via .zip file and that didn't work either. My A1111 is up to date. Anyone got any ideas of what I can try?

**Comment by wenmengzhou** [comment]
can you provide some installing logs?

**Comment by recycleaway7** [comment]
> can you provide some installing logs?

I don't get any errors and nothing shows up in the log. It just says "processing | 500/0.1s" or whatever, with the 500 number being however many seconds I let it run and 0.1 being the expected time. It seems like the extensions/facechain folder fills up with everything it's supposed to, but for some reason it just completely breaks my A1111 SD to the point where I can't use it again until I delete that facechain folder.

**Comment by wenmengzhou** [comment]
during facechain installation, in Windows platform mmcv-full will be needed and built for very long time,  it may be stucked here?

you can  try to execute C:\stable-diffusion-webui-v13\venv\Scripts\pip list |grep mmcv to see whether it has been successfully installed，  if not please wait until mmcv to be built

**Comment by recycleaway7** [comment]
> during facechain installation, in Windows platform mmcv-full will be needed and built for very long time, it may be stucked here?
> 
> you can try to execute C:\stable-diffusion-webui-v13\venv\Scripts\pip list |grep mmcv to see whether it has been successfully installed， if not please wait until mmcv to be built

That was it. I didn't have mmcv in my pip list so I did   pip install mmcv   and that took about 20-25 minutes to finish. Installing the extension took about 10 seconds after that and I'm seeing the FaceChain tab after restarting. Thanks!

**Comment by escalate007** [comment]
> > during facechain installation, in Windows platform mmcv-full will be needed and built for very long time, it may be stucked here?
> > you can try to execute C:\stable-diffusion-webui-v13\venv\Scripts\pip list |grep mmcv to see whether it has been successfully installed， if not please wait until mmcv to be built
> 
> That was it. I didn't have mmcv in my pip list so I did pip install mmcv and that took about 20-25 minutes to finish. Installing the extension took about 10 seconds after that and I'm seeing the FaceChain tab after restarting. Thanks!

I also resolved it by waiting for more than 20min.Thanks for your practice.
