### ISSUE TITLE
Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by itmuse** [modelscope/facechain#43]
Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)

当有多张显卡的时候，会找不到指定的显卡，请问需要怎么解决？

**Comment by dengpao-lfz** [comment]
用 CUDA_VISIBLE_DEVICES=1 python app.py 运行，可以训练。
但是推理的时候报错
with safe_open(filename, framework="pt", device=device) as f:
OSError: No such device (os error 19)

**Comment by sunbaigui** [comment]
> > 用 CUDA_VISIBLE_DEVICES=1 python app.py 运行，可以训练。
> 
> 双显卡，可以用`CUDA_VISIBLE_DEVICES=0 python app.py` 允许，支持训练和推流，试验成功

感谢支持
