### ISSUE TITLE
UnboundLocalError: local variable 'subprocess' referenced before assignment

### ISSUE THREAD

**Issue by farizy4n** [modelscope/facechain#438]
> instance_data_dir E:\Ai\TensorRT\webui\extensions\facechain\worker_data\qw\training_data\ly261666/cv_portrait_model\person1
> Traceback (most recent call last):
>   File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 148, in train_lora_fn
>     subprocess.run(command, check=True)
> UnboundLocalError: local variable 'subprocess' referenced before assignment
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
>     result = await self.call_function(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
>     response = f(*args, **kwargs)
>   File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 799, in run
>     train_lora_fn(base_model_path=base_model_path,
>   File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 149, in train_lora_fn
>     except subprocess.CalledProcessError as e:
> UnboundLocalError: local variable 'subprocess' referenced before assignment

Whats worng with that? i cant fix it.

**Comment by abc8350712** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\admin\miniconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Work\stable-diffusion-webui\extensions\facechain\facechain\inference.py", line 25, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "C:\Work\stable-diffusion-webui\extensions\facechain\facechain\data_process\preprocessing.py", line 207, in __init__
    self.face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
  File "C:\Work\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 162, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Work\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\Work\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: FaceDetectionPipeline: DamoFdDetect: No module named 'mmcv._ext'
instance_data_dir C:\Work\stable-diffusion-webui\extensions\facechain\worker_data\qw\training_data\ly261666/cv_portrait_model\person1
Traceback (most recent call last):
  File "C:\Work\stable-diffusion-webui\extensions\facechain\app.py", line 148, in train_lora_fn
    subprocess.run(command, check=True)
UnboundLocalError: local variable 'subprocess' referenced before assignment

same error

**Comment by farizy4n** [comment]
Lets wait...

**Comment by abc8350712** [comment]
> Lets wait...

Did you run the code on win10 too?

**Comment by ly19965** [comment]
This has been solved by this PR https://github.com/modelscope/facechain/pull/427

**Comment by escalate007** [comment]
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\admin\miniconda3\lib\multiprocessing\process.py", line 314, in _bootstrap self.run() File "C:\Users\admin\miniconda3\lib\multiprocessing\process.py", line 108, in run self._target(*self._args, **self._kwargs) File "C:\Work\stable-diffusion-webui\extensions\facechain\facechain\inference.py", line 25, in _data_process_fn_process Blipv2()(input_img_dir) File "C:\Work\stable-diffusion-webui\extensions\facechain\facechain\data_process\preprocessing.py", line 207, in **init** self.face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1') File "C:\Work\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 162, in pipeline return build_pipeline(cfg, task_name=task) File "C:\Work\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline return build_from_cfg( File "C:\Work\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') ModuleNotFoundError: FaceDetectionPipeline: DamoFdDetect: No module named 'mmcv._ext' instance_data_dir C:\Work\stable-diffusion-webui\extensions\facechain\worker_data\qw\training_data\ly261666/cv_portrait_model\person1 Traceback (most recent call last): File "C:\Work\stable-diffusion-webui\extensions\facechain\app.py", line 148, in train_lora_fn subprocess.run(command, check=True) UnboundLocalError: local variable 'subprocess' referenced before assignment
> 
> same error

the same error，then I have used the PR #427  to fix it，but it still be this way.
