### ISSUE TITLE
app.py运行后能成功加载但是无法监听启动服务，尝试管理员模式也没用

### ISSUE THREAD

**Issue by mopring** [modelscope/facechain#444]
<img width="731" alt="image" src="https://github.com/modelscope/facechain/assets/53283061/6c6047d7-846d-4e3b-8494-f344b84bfa4e">

**Comment by hcl67** [comment]
mine was resolved by installing the specific version of gardio:

pip install gradio==3.50

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
