### ISSUE TITLE
Error at training

### ISSUE THREAD

**Issue by farizy4n** [modelscope/facechain#448]
This has been solved by this PR https://github.com/modelscope/facechain/pull/427

_Originally posted by @ly19965 in https://github.com/modelscope/facechain/issues/438#issuecomment-1829181441_
           

> 
> 2023-11-30 02:37:03,539 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
> 2023-11-30 02:37:03,542 - modelscope - INFO - TensorFlow version 2.14.0 Found.
> 2023-11-30 02:37:03,542 - modelscope - INFO - Loading ast index from C:\Users\Al Farizy\.cache\modelscope\ast_indexer
> 2023-11-30 02:37:03,646 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 4bba8c18e70a19b2844f6993ffdce729 and a total number of 943 components indexed
> 2023-11-30 02:37:06,665 - modelscope - INFO - Use user-specified model revision: v4.0
> 2023-11-30 02:37:11,458 - modelscope - INFO - Use user-specified model revision: v1.0.1
> 2023-11-30 02:37:12,285 - modelscope - WARNING - ('PIPELINES', 'skin-retouching-torch', 'skin-retouching-torch') not found in ast index file
> 2023-11-30 02:37:12,285 - modelscope - INFO - initiate model from C:\Users\Al Farizy\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch
> 2023-11-30 02:37:12,286 - modelscope - INFO - initiate model from location C:\Users\Al Farizy\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch.
> 2023-11-30 02:37:12,293 - modelscope - WARNING - No preprocessor field found in cfg.
> 2023-11-30 02:37:12,293 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
> 2023-11-30 02:37:12,294 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\Al Farizy\\.cache\\modelscope\\hub\\damo\\cv_unet_skin_retouching_torch'}. trying to build by task and model information.
> 2023-11-30 02:37:12,294 - modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor
> 2023-11-30 02:37:15,697 - modelscope - INFO - Model revision not specified, use revision: v2.0.2
> 2023-11-30 02:37:17,700 - modelscope - INFO - initiate model from C:\Users\Al Farizy\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
> 2023-11-30 02:37:17,700 - modelscope - INFO - initiate model from location C:\Users\Al Farizy\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
> 2023-11-30 02:37:17,707 - modelscope - WARNING - No preprocessor field found in cfg.
> 2023-11-30 02:37:17,707 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
> 2023-11-30 02:37:17,708 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\Al Farizy\\.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
> 2023-11-30 02:37:17,708 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
> 2023-11-30 02:37:17,710 - modelscope - INFO - loading model from C:\Users\Al Farizy\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
> 2023-11-30 02:37:18,062 - modelscope - INFO - load model done
> Process Process-8:
> Traceback (most recent call last):
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
>     return obj_cls(**args)
>   File "C:\Users\Al Farizy\.cache\modelscope\modelscope_modules\cv_unet_skin_retouching_torch\ms_wrapper.py", line 76, in __init__
>     self.sess, self.input_node_name, self.out_node_name = self.load_onnx_model(
>   File "C:\Users\Al Farizy\.cache\modelscope\modelscope_modules\cv_unet_skin_retouching_torch\ms_wrapper.py", line 93, in load_onnx_model
>     sess = onnxruntime.InferenceSession(onnx_path)
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
>     raise e
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
>     raise ValueError(
> ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "multiprocessing\process.py", line 314, in _bootstrap
>   File "multiprocessing\process.py", line 108, in run
>   File "E:\Ai\TensorRT\webui\extensions\facechain\facechain\inference.py", line 25, in _data_process_fn_process
>     Blipv2()(input_img_dir)
>   File "E:\Ai\TensorRT\webui\extensions\facechain\facechain\data_process\preprocessing.py", line 205, in __init__
>     self.skin_retouching = pipeline('skin-retouching-torch', model='damo/cv_unet_skin_retouching_torch', model_revision='v1.0.1')
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\modelscope\pipelines\builder.py", line 163, in pipeline
>     return build_pipeline(cfg, task_name=task)
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\modelscope\pipelines\builder.py", line 67, in build_pipeline
>     return build_from_cfg(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> ValueError: SkinRetouchingTorchPipeline: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
> instance_data_dir E:\Ai\TensorRT\webui\extensions\facechain\worker_data\qw\training_data\ly261666/cv_portrait_model\viona
> Traceback (most recent call last):
>   File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 148, in train_lora_fn
>     subprocess.run(command, check=True)
> UnboundLocalError: local variable 'subprocess' referenced before assignment
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
>     result = await self.call_function(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
>     response = f(*args, **kwargs)
>   File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 799, in run
>     train_lora_fn(base_model_path=base_model_path,
>   File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 149, in train_lora_fn
>     except subprocess.CalledProcessError as e:
> UnboundLocalError: local variable 'subprocess' referenced before assignment
> 

![image](https://github.com/modelscope/facechain/assets/145122436/4b860b77-8960-46f1-8144-00d0aa553d71)

**Comment by RenatoSerk** [comment]
Assuming you're on windows, remove the import that's a bit later and it should work.
![image](https://github.com/modelscope/facechain/assets/15863488/690a249b-29f9-4e92-bfc6-8407d70b4625)
Error is gone, don't know why that import is there but we don't care about it because we're on windows

**Comment by farizy4n** [comment]
Traceback (most recent call last):
  File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Ai\TensorRT\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Ai\TensorRT\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 799, in run
    train_lora_fn(base_model_path=base_model_path,
  File "E:\Ai\TensorRT\webui\extensions\facechain\app.py", line 149, in train_lora_fn
    except subprocess.CalledProcessError as e:
UnboundLocalError: local variable 'subprocess' referenced before assignment
