### ISSUE TITLE
A1111 style prompt

### ISSUE THREAD

**Issue by yupeng1111** [modelscope/facechain#450]
Nice work, i notice that a1111 style prompts are being used, e.g.  ((monochrome)). But i found nothing in codes (maybe i missed) about parsing the token weight like [https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/prompt_parser.py#L371](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/prompt_parser.py#L371). Could this lead to less promising performance?

**Comment by sunbaigui** [comment]
@You-Cun please checkout this.

**Comment by You-Cun** [comment]
We actually do not use the a1111 style prompts when testing the style LoRAs though we planned to use it at the beginning. As such, the parameters are optimized without a1111 style and cannot easily adjusted to a1111 style prompts.
