### ISSUE TITLE
生成人物面部表情问题

### ISSUE THREAD

**Issue by BuQingYan** [modelscope/facechain#455]
请问下是否有方法可以控制生成人物的面部表情参照模板图片的表情。比如有些模板眼睛是斜的，但是换脸后眼睛是在中间的，看起来很呆板，请问是否有方法可以控制生成人物的面部表情和参照模板一致

**Comment by Augenstern000** [comment]
目前我们开源版本没有推出这个功能，后续我们会优化这些细节，感谢您的反馈
