### ISSUE TITLE
[ERROR]: MS Visual Studio

### ISSUE THREAD

**Issue by Woisek** [modelscope/facechain#458]
First I want to say, it's not cool, if a repo doesn't install everything need for it to run.
Second, when installed from another application, like WebUI, the User expects that it runs right out of the box.

This all doesn't apply here.
After installing this extension through WebUI, it just doesn't work because something is allegedly not installed.
I get this error:

F:\Programme\Python310\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'mmcv._ext' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

But fact is, MS Visual C++ 14 IS installed.
![Zwischenablagebild](https://github.com/modelscope/facechain/assets/122026301/8468c578-4864-4988-a6cf-5285954e1612)

So, how can this be solved?

**Comment by liuyhwangyh** [comment]
Please install mmcv with:  
min install mmcv-full==1.7.2
ref: https://mmcv.readthedocs.io/en/latest/get_started/installation.html

**Comment by Woisek** [comment]
That didn't work.

--installing mmcv...
Installing requirements for mmcv
Couldn't install requirements for mmcv.
Command: "I:\Super SD 2.0\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mmcv-full==1.7.0 --prefer-binary
Error code: 1
stdout: Collecting mmcv-full==1.7.0
  Using cached mmcv-full-1.7.0.tar.gz (593 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [14 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "T:\systemp\pip-install-8jyb4wmm\mmcv-full_aa17ceb76e2849258c11d7a99251bd75\setup.py", line 461, in <module>
      ext_modules=get_extensions(),
    File "T:\systemp\pip-install-8jyb4wmm\mmcv-full_aa17ceb76e2849258c11d7a99251bd75\setup.py", line 365, in get_extensions
      ext_ops = extension(
    File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1048, in CUDAExtension
      library_dirs += library_paths(cuda=True)
    File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths
      paths.append(_join_cuda_home(lib_dir))
    File "I:\Super SD 2.0\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2223, in _join_cuda_home
      raise EnvironmentError('CUDA_HOME environment variable is not set. '
  OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: I:\Super SD 2.0\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

ERROR facechain: failed to install mmcv, make sure to have "CUDA Toolkit" and "Build Tools for Visual Studio" installed
Installing requirements for diffusers

![Zwischenablagebild (1)](https://github.com/modelscope/facechain/assets/122026301/43bab325-abbd-4a5f-b39a-10cc98806718)

Any other ideas?

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
