### ISSUE TITLE
No such file or directory: '/tmp/qw/personalizaition_lora/pytorch_lora_weights.bin'

### ISSUE THREAD

**Issue by YuyangYin** [modelscope/facechain#46]
File "/home/yyy/facechain/facechain/inference.py", line 47, in main_diffusion_inference
    pipe = merge_lora(pipe, lora_human_path, multiplier_human, from_safetensor=False)
  File "/home/yyy/facechain/facechain/merge_lora.py", line 15, in merge_lora
    checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), 
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/personalizaition_lora/pytorch_lora_weights.bin
训练生成的为safetensor，为什么代码中的为bin？为什么会找不到该文件？请教，感谢。

**Comment by potoyeee** [comment]
> 你好，请问你解决了吗，我遇到了相同的问题

**Comment by zengjichen** [comment]
hi, you can temp modify the code :

**Comment by zengjichen** [comment]
if(lora_path.endswith('bin')):
            
            checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), map_location=torch.device(device))
        else:
            checkpoint= load_file(lora_path+'pytorch_lora_weights.safetensors', device=device)

**Comment by zengjichen** [comment]
> > 你好，请问你解决了吗，我遇到了相同的问题

you can temporary fix the problem ,follow my code

**Comment by cdswyda** [comment]
same erorr

**Comment by jjiikkkk** [comment]
我也是 这个代码好像是不能用的 藏着掖着模型

**Comment by Puwong** [comment]
> > > 你好，请问你解决了吗，我遇到了相同的问题
> 
> you can temporary fix the problem ,follow my code

I use this code, but got another problem:

FileNotFoundError: No such file or directory: "/tmp/qw/personalizaition_lorapytorch_lora_weights.safetensors"

**Comment by Puwong** [comment]
> > > > 你好，请问你解决了吗，我遇到了相同的问题
> > 
> > 
> > you can temporary fix the problem ,follow my code
> 
> I use this code, but got another problem:
> 
> FileNotFoundError: No such file or directory: "/tmp/qw/personalizaition_lorapytorch_lora_weights.safetensors"

我重新提了一个issue，我用win11跑应该是没有生成模型文件。不知道楼上的修改过哪些？如果有safetensors是生成了模型文件了？

**Comment by itmuse** [comment]
> > > > > 你好，请问你解决了吗，我遇到了相同的问题
> > > 
> > > 
> > > you can temporary fix the problem ,follow my code
> > 
> > 
> > I use this code, but got another problem:
> > FileNotFoundError: No such file or directory: "/tmp/qw/personalizaition_lorapytorch_lora_weights.safetensors"
> 
> 我重新提了一个issue，我用win11跑应该是没有生成模型文件。不知道楼上的修改过哪些？如果有safetensors是生成了模型文件了？

遇到相同的问题，把`facechain/merge_lora.py` 文件修改为：

```python
    if(lora_path.endswith('bin')):
        checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), map_location=torch.device(device))
    else:
        checkpoint= load_file(lora_path+'pytorch_lora_weights.safetensors', device=device)  
```
也是没有解决问题。

**Comment by zengjichen** [comment]
> > > > > > 你好，请问你解决了吗，我遇到了相同的问题
> > > > 
> > > > 
> > > > you can temporary fix the problem ,follow my code
> > > 
> > > 
> > > I use this code, but got another problem:
> > > FileNotFoundError: No such file or directory: "/tmp/qw/personalizaition_lorapytorch_lora_weights.safetensors"
> > 
> > 
> > 我重新提了一个issue，我用win11跑应该是没有生成模型文件。不知道楼上的修改过哪些？如果有safetensors是生成了模型文件了？
> 
> 遇到相同的问题，把`facechain/merge_lora.py` 文件修改为：
> 
> ```python
>     if(lora_path.endswith('bin')):
>         checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), map_location=torch.device(device))
>     else:
>         checkpoint= load_file(lora_path+'pytorch_lora_weights.safetensors', device=device)  
> ```
> 
> 也是没有解决问题。

 i run ok , this is my solution
def merge_lora(pipeline, lora_path, multiplier, from_safetensor=False, device='cpu', dtype=torch.float32):
    LORA_PREFIX_UNET = "lora_unet"
    LORA_PREFIX_TEXT_ENCODER = "lora_te"
   if from_safetensor:
          state_dict = load_file(lora_path, device=device)
      else:
          ## add follow  code 
          if(lora_path.endswith('bin')):
              
              checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), map_location=torch.device(device))
          else:
              checkpoint= load_file(lora_path+'/pytorch_lora_weights.safetensors', device=device)
         
          new_dict = dict()

**Comment by zengjichen** [comment]
> > > > > > 你好，请问你解决了吗，我遇到了相同的问题
> > > > 
> > > > 
> > > > you can temporary fix the problem ,follow my code
> > > 
> > > 
> > > I use this code, but got another problem:
> > > FileNotFoundError: No such file or directory: "/tmp/qw/personalizaition_lorapytorch_lora_weights.safetensors"
> > 
> > 
> > 我重新提了一个issue，我用win11跑应该是没有生成模型文件。不知道楼上的修改过哪些？如果有safetensors是生成了模型文件了？
> 
> 遇到相同的问题，把`facechain/merge_lora.py` 文件修改为：
> 
> ```python
>     if(lora_path.endswith('bin')):
>         checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), map_location=torch.device(device))
>     else:
>         checkpoint= load_file(lora_path+'pytorch_lora_weights.safetensors', device=device)  
> ```
> 
> 也是没有解决问题。
~~~ python

def merge_lora(pipeline, lora_path, multiplier, from_safetensor=False, device='cpu', dtype=torch.float32):
    LORA_PREFIX_UNET = "lora_unet"
    LORA_PREFIX_TEXT_ENCODER = "lora_te"
    if from_safetensor:
        state_dict = load_file(lora_path, device=device)
    else:
        if(lora_path.endswith('bin')):
            
            checkpoint = torch.load(os.path.join(lora_path, 'pytorch_lora_weights.bin'), map_location=torch.device(device))
        else:
            checkpoint= load_file(lora_path+'/pytorch_lora_weights.safetensors', device=device)
        new_dict = dict()

~~~

**Comment by cdswyda** [comment]
我后来解决这个问题了。 
我出现这个错误是因为训练失败了，在解决训练过程中的错误之后，此处的代码没有问题。
也就是说我没有修改代码，但没有这个错错误了，有相同问题的人可以检查下训练过程中的日志，来排查问题

**Comment by zengjichen** [comment]
> > 我后来解决这个问题了。 我出现这个错误是因为训练失败了，在解决训练过程中的错误之后，此处的代码没有问题。 也就是说我没有修改代码，但没有这个错错误了，有相同问题的人可以检查下训练过程中的日志，来排查问题
> 
> 是的，我也遇到这个问题了，UI界面上是正确完成训练，我其实在训练过程中显存不够了，所以这个模型文件没有成功保存，就是这个意思

3090 会有这个问题,但是v100 是ok的.迷惑操作哈哈

**Comment by sunbaigui** [comment]
@YuyangYin have you solved your problem according the suggestions above.

**Comment by sunbaigui** [comment]
closed, feel free to reopen it, if you have further questions
