### ISSUE TITLE
FaceChain在webui中加载不出来

### ISSUE THREAD

**Issue by yuyifan1991** [modelscope/facechain#479]
FaceChain通过url在webui中安装了，刷新后，是界面加载不出来

**Comment by ArlanCooper** [comment]
+1

**Comment by dayongitt** [comment]
+1

**Comment by h3clikejava** [comment]
+1

**Comment by onyxlee** [comment]
I just installed in A1111 webui v1.7.0. The tab also doesn't show up. Can someone please take a look? Thanks.

**Comment by dengfeng0729** [comment]
+1

**Comment by ghkim89** [comment]
It does not work even in Web UI 1.8.0 version.
