### ISSUE TITLE
无法下载  人脸融合模型 cv_unet-image-face-fusion_damo

### ISSUE THREAD

**Issue by potoyeee** [modelscope/facechain#48]
你好，能提供下载链接吗

报错如下：
- modelscope - INFO - Model revision not specified, use the latest revision: v1.1
- urllib3.exceptions.MaxRetryError: None: Max retries exceeded with url: http://www.modelscope.cn/api/v1/models/damo/cv_unet-image-face-fusion_damo/repo?Revision=v1.1&FilePath=description/.DS_Store (Caused by ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))

**Comment by tastelikefeet** [comment]
你好，似乎是连接问题，请问硬件环境是什么呢，本地服务器还是colab？您可以尝试直接下载下这个模型：https://www.modelscope.cn/models/damo/cv_unet-image-face-fusion_damo/files
