### ISSUE TITLE
run run_inference.py  BUG?

### ISSUE THREAD

**Issue by AN-ZE** [modelscope/facechain#481]
I run "python run_inference.py", error is
```
    if int(sr_img_size) != 0:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I suspect this is a bug.
https://github.com/modelscope/facechain/blob/ad1fc19affd5dd3027980388b168c6ec2a0c52b6/run_inference.py#L79
sr_img_size=None, portrait_stylization_idx=None

https://github.com/modelscope/facechain/blob/ad1fc19affd5dd3027980388b168c6ec2a0c52b6/facechain/inference.py#L595
https://github.com/modelscope/facechain/blob/ad1fc19affd5dd3027980388b168c6ec2a0c52b6/facechain/inference.py#L620

sr_img_size=None?  sr_img_size!=0?

**Comment by AN-ZE** [comment]
I fixed it. 
https://github.com/modelscope/facechain/pull/484

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
