### ISSUE TITLE
幫我看看這些dependence是對的嗎，我用colab，如果順序不對也幫我調一下

### ISSUE THREAD

**Issue by wfq1971** [modelscope/facechain#483]
!pip3 install typing-extensions==4.6.1
!pip3 install kaleido
!pip3 install cohere
!pip3 install openai==1.5.0
!pip3 install tiktoken
!pip3 install pydantic==2.0.2
!pip3 install tensorflow==2.14.0
!pip3 install tensorflow-probability==0.23.0
!pip3 install -r facechain/requirements.txt

import os
os.chdir('/content/')    # 注意替换成上述clone后的代码文件夹主路径
print(os.getcwd())

!pip3 install fastapi==0.1.0
!pip3 install gradio==3.50.2
!pip3 install controlnet_aux==0.0.6
!pip3 install kaleido
!pip3 install python-slugify
!pip3 install onnxruntime==1.15.1
!pip3 install edge-tts
!pip3 install modelscope==1.10.0

**Comment by wfq1971** [comment]
https://colab.research.google.com/drive/1yES5OSkqKmWCQaHwFCedmLg8n291DBvS?usp=sharing

**Comment by wfq1971** [comment]
以下錯誤
/content
Traceback (most recent call last):
  File "/content/facechain/app.py", line 10, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 20, in <module>
    from fastapi import UploadFile
ImportError: cannot import name 'UploadFile' from 'fastapi' (/usr/local/lib/python3.10/dist-packages/fastapi/__init__.py)

**Comment by YuanyuanZhang37** [comment]
试一下pip install --upgrade accelerate

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
