### ISSUE TITLE
Error on my mac, CUDA is not available

### ISSUE THREAD

**Issue by lijianqiang12** [modelscope/facechain#488]
<img width="459" alt="截屏2024-01-03 16 35 06" src="https://github.com/modelscope/facechain/assets/10259429/20e3f95f-a1c5-4c35-a31f-b5b12042d0ca">

macOS 14.2.1, Apple M2 Ultra

Is there any way to make it compatible with maOS?

**Comment by molyswu** [comment]
cuda版本与torch版本不兼容

**Comment by lijianqiang12** [comment]
> cuda版本与torch版本不兼容

没有mac的CUDA😭
