### ISSUE TITLE
what is the original model of "ly261666/cv_portrait_model"?

### ISSUE THREAD

**Issue by Yongssss** [modelscope/facechain#489]
The model called 'ly261666/cv_portrait_model' (https://modelscope.cn/models/ly261666/cv_portrait_model/summary) seems like not be original 'leosamsMoonfilm_filmGrain20' and it seems like you fine-tuned it, especially for the VAE model including the VAE encoder.

**Comment by ly19965** [comment]
It is the original leosamsMoonfilm_filmGrain20, we only store it on the modelscope platform
