### ISSUE TITLE
把更新后的代码拉下来，再运行打开网址后直接报错了

### ISSUE THREAD

**Issue by shengzewen** [modelscope/facechain#50]
![image](https://github.com/modelscope/facechain/assets/48091887/a17cc8d7-735c-4116-8b13-bef792638eee)

**Comment by wen020** [comment]
+1

**Comment by yingdachen** [comment]
如果您要再本地运行，请参考README里的环境安装部分。

https://github.com/modelscope/facechain#3-conda-virtual-environment

直接运行app.py是不行的。

**Comment by shengzewen** [comment]
> 如果您要再本地运行，请参考README里的环境安装部分。
> 
> https://github.com/modelscope/facechain#3-conda-virtual-environment
> 
> 直接运行app.py是不行的。

我是在服务器上运行的，按照这个步骤安装了，然后再运行的app.py
