### ISSUE TITLE
您好，能发布一个windows版的部署说明吗？小白搞了三天都没成功报错太多了

### ISSUE THREAD

**Issue by CeerQuit** [modelscope/facechain#501]
1.装了mmcv还是提示ModuleNotFoundError: No module named 'mmcv._ext'
2.这个报错不知道怎么操作File "d:\anaconda3\envs\facechain\lib\site-packages\datasets\data_files.py", line 475, in get_data_patterns
    raise EmptyDatasetError(f"The directory at {base_path} doesn't contain any data files") from None
datasets.data_files.EmptyDatasetError: The directory at D:/facechain/worker_data/qw/training_data/AI-ModelScope/stable-diffusion-xl-base-1.0/was_labeled doesn't contain any data files
Error executing the command: Command '['python', 'D:\\facechain/facechain/train_text_to_image_lora_sdxl.py', '--

求求大佬发布个windows版本的吧

**Comment by wenmengzhou** [comment]
pip install mim

mom install mmcv-full

**Comment by CeerQuit** [comment]
还是不行。。

**Comment by gfpyc** [comment]
刚刚搞定，遇见同样第一个问题。
参照https://github.com/modelscope/facechain/pull/468/commits/094e3c00d04e17de5a82f303457cb4d3906085cd里面没通过的修改。
`# 对应版本1.7.0+torch2.1.1cu121， 1.7.0+torch2.1.0cu121， 1.7.0+torch2.1.1cu118， 1.7.0+torch2.1.0cu118
pip install mmcv_full=='1.7.0+torch2.1.1cu121' -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`

然后我正常跑起来了。

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
