### ISSUE TITLE
要先安装CUDA，CUDA还需要visual studio,不是一般的麻烦啊，有简洁的安装方法吗？

### ISSUE THREAD

**Issue by jinnaluo0** [modelscope/facechain#505]
要先安装CUDA，CUDA还需要visual studio,不是一般的麻烦啊，有简洁的安装方法吗？

**Comment by Tendo33** [comment]
不安装cuda怎么跑模型啊哈哈哈🤣

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
