### ISSUE TITLE
一定要先训练人物lora才能使用后面的生成人物照片的功能吗？

### ISSUE THREAD

**Issue by guijuzhejiang** [modelscope/facechain#507]
不训练人物lora，能不能通过一张照片生成写真？

**Comment by ccyhxg** [comment]
现在有一些这样的技术了，facechain即将开源FACT技术支持，同时也可以参考魔搭社区现有的一些技术，比如InstantID

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
