### ISSUE TITLE
gradio version error

### ISSUE THREAD

**Issue by Rocky77JHxu** [modelscope/facechain#510]
Hello author of facechain, as of today, I have found that it is best to follow the version of `gradio=3.23` in the graphic. Otherwise, many old codes do not support the new version of graphics, such as`gradio==4.x.x`. I hope this can help everyone~!!!

**Comment by zhuohaoNg** [comment]
I met the same situation, too. When I used the provided requirement.txt to pip install dependency packages, it auto installed  gradio-4.16.0(up to date) and then the error "module 'gradio' has no attribute 'Box'" would occur. I tried your suggestion, but  another error occurred when selected input images through web. It just showed "error"  without a log to explaination. So, I tried using other gradio versions such as gradio-3.50.0 which would be OK. I check the code commit version which I cloned is 98979a1, hope my case can also help others.

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
