### ISSUE TITLE
Can you remove mmcv lib dependence???

### ISSUE THREAD

**Issue by Johnson-yue** [modelscope/facechain#524]
Can you remove the dependency on the mmcv library? 

Because mmcv often changes a lot, is very unstable and not backwards compatible, and has very strict environmental requirements. It is strongly recommended dependency on the mmcv library to improve the usability of the code

**Comment by sunbaigui** [comment]
would you like to contribute this? we suffered from this a lot.

**Comment by sunbaigui** [comment]
After evaluation, due to the relatively large amount of work involved, we will temporarily close this issue for now. We also welcome interested developers to contribute by submitting a Pull Request (PR).
