### ISSUE TITLE
请问FaceChain-SuDe的源码什么时候公开呀？

### ISSUE THREAD

**Issue by Monalissaa** [modelscope/facechain#531]
感谢您提出的在One-shot Subject-Driven Generation上做的SuDe方法，这种方式显著的提升了可编辑性，我对您的工作非常感兴趣，请问您什么时候可以开源此方法的代码呀

**Comment by rfan-debug** [comment]
同求实现代码，谢谢！

**Comment by sunbaigui** [comment]
@slpal please check out this issue.

**Comment by slpal** [comment]
> @slpal please check out this issue.

We are preparing to release the code before the end of June.

**Comment by sunbaigui** [comment]
@rfan-debug @Monalissaa sude code was uploaded, enjoy. https://github.com/modelscope/facechain/tree/main/more_apps/Facechain-SuDe

**Comment by JoshonSmith** [comment]
> @rfan-debug @Monalissaa sude code was uploaded, enjoy. https://github.com/modelscope/facechain/tree/main/more_apps/Facechain-SuDe

good work!
请问 FaceChain-SuDe 是否支持多个参考主题的生成，比如输入一张男孩和一张女孩的图像，生成合照

**Comment by rfan-debug** [comment]
@JoshonSmith 如果我理解对的话，你的需求跟这项工作本身的功能不是很一致。你可能需要考虑使用FaceID ip-adapter: https://huggingface.co/h94/IP-Adapter-FaceID
