### ISSUE TITLE
从sdwebui扩展中安装（install from url），重启后不显示facechain

### ISSUE THREAD

**Issue by dengfeng0729** [modelscope/facechain#533]
从sdwebui扩展中安装（install from url），重启后不显示facechain, 有朋友遇到这个问题吗？

**Comment by Lynn2023** [comment]
我也是
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing requirements for diffusers
Launching Web UI with arguments: --theme light --xformers --api --autolaunch
Civitai Helper: Get Custom Model Folder
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.3.1, num models: 22
[lora-prompt-tool] Get Custom Model Folder
ControlNet preprocessor location: G:\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\annotator\downloads
2024-03-22 13:42:48,343 - ControlNet - INFO - ControlNet v1.1.441
2024-03-22 13:42:48,426 - ControlNet - INFO - ControlNet v1.1.441
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [1681bf15ca] from G:\sd-webui-aki-v4.6.1\models\Stable-diffusion\PONY\js2prony_v10.safetensors
2024-03-22 13:42:49,402 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Settings:
Civitai Helper: max_size_preview: True
Civitai Helper: skip_nsfw_preview: False
Civitai Helper: open_url_with_js: True
Civitai Helper: proxy:
2024-03-22 13:42:49,999 - modelscope - INFO - PyTorch version 2.1.2+cu118 Found.
2024-03-22 13:42:50,009 - modelscope - INFO - Loading ast index from G:\sd-webui-aki-v4.6.1\.cache\modelscope\hub\ast_indexer
Creating model from config: G:\sd-webui-aki-v4.6.1\repositories\generative-models\configs\inference\sd_xl_base.yaml
2024-03-22 13:42:50,313 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 d5f1181da20c4b632256d7ae966f0089 and a total number of 964 components indexed
*** Error executing callback ui_tabs_callback for G:\sd-webui-aki-v4.6.1\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4.6.1\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "G:\sd-webui-aki-v4.6.1\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "G:\sd-webui-aki-v4.6.1\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference import preprocess_pose, GenPortrait
      File "G:\sd-webui-aki-v4.6.1\extensions\facechain\facechain\inference.py", line 10, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel, \
    ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (G:\sd-webui-aki-v4.6.1\python\lib\site-packages\diffusers\__init__.py)

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 20.2s (prepare environment: 9.4s, import torch: 2.2s, import gradio: 0.7s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.3s, list SD models: 0.2s, load scripts: 1.8s, create ui: 2.4s, gradio launch: 2.3s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: G:\sd-webui-aki-v4.6.1\models\VAE\sdxlVAE_v10.safetensors
Applying attention optimization: xformers... done.
Model loaded in 5.3s (load weights from disk: 1.1s, create model: 0.6s, apply weights to model: 3.0s, apply half(): 0.2s, calculate empty prompt: 0.2s).

**Comment by datuizhuang** [comment]
> 我也是 Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] Version: v1.7.0 Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e Installing requirements for diffusers Launching Web UI with arguments: --theme light --xformers --api --autolaunch Civitai Helper: Get Custom Model Folder Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu. [-] ADetailer initialized. version: 24.3.1, num models: 22 [lora-prompt-tool] Get Custom Model Folder ControlNet preprocessor location: G:\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\annotator\downloads 2024-03-22 13:42:48,343 - ControlNet - INFO - ControlNet v1.1.441 2024-03-22 13:42:48,426 - ControlNet - INFO - ControlNet v1.1.441 sd-webui-prompt-all-in-one background API service started successfully. Loading weights [1681bf15ca] from G:\sd-webui-aki-v4.6.1\models\Stable-diffusion\PONY\js2prony_v10.safetensors 2024-03-22 13:42:49,402 - ControlNet - INFO - ControlNet UI callback registered. Civitai Helper: Settings: Civitai Helper: max_size_preview: True Civitai Helper: skip_nsfw_preview: False Civitai Helper: open_url_with_js: True Civitai Helper: proxy: 2024-03-22 13:42:49,999 - modelscope - INFO - PyTorch version 2.1.2+cu118 Found. 2024-03-22 13:42:50,009 - modelscope - INFO - Loading ast index from G:\sd-webui-aki-v4.6.1.cache\modelscope\hub\ast_indexer Creating model from config: G:\sd-webui-aki-v4.6.1\repositories\generative-models\configs\inference\sd_xl_base.yaml 2024-03-22 13:42:50,313 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 d5f1181da20c4b632256d7ae966f0089 and a total number of 964 components indexed *** Error executing callback ui_tabs_callback for G:\sd-webui-aki-v4.6.1\extensions\facechain\scripts\facechain_sdwebui.py Traceback (most recent call last): File "G:\sd-webui-aki-v4.6.1\modules\script_callbacks.py", line 166, in ui_tabs_callback res += c.callback() or [] File "G:\sd-webui-aki-v4.6.1\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs import app File "G:\sd-webui-aki-v4.6.1\extensions\facechain\app.py", line 16, in from facechain.inference import preprocess_pose, GenPortrait File "G:\sd-webui-aki-v4.6.1\extensions\facechain\facechain\inference.py", line 10, in from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel, ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (G:\sd-webui-aki-v4.6.1\python\lib\site-packages\diffusers__init__.py)
> 
> Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. Startup time: 20.2s (prepare environment: 9.4s, import torch: 2.2s, import gradio: 0.7s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.3s, list SD models: 0.2s, load scripts: 1.8s, create ui: 2.4s, gradio launch: 2.3s, app_started_callback: 0.1s). Loading VAE weights specified in settings: G:\sd-webui-aki-v4.6.1\models\VAE\sdxlVAE_v10.safetensors Applying attention optimization: xformers... done. Model loaded in 5.3s (load weights from disk: 1.1s, create model: 0.6s, apply weights to model: 3.0s, apply half(): 0.2s, calculate empty prompt: 0.2s).

你这个diffusers库报错了啊，没有’StableDiffusionXLPipeline‘这个module，看看diffusers的版本

**Comment by bj803** [comment]
尝试在环境变量中添加红圈里这一项(我是这样解决的)
![屏幕截图 2025](https://github.com/modelscope/facechain/assets/109253859/9a99fbf8-aba8-4695-bd8c-0f174a8efd54)

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
