### ISSUE TITLE
Can I use FaceChain on my computer? RTX - Graphic Memory: 24GB, Dedicated video memory: 8GB Shared System memory: 16gb

### ISSUE THREAD

**Issue by ananzabonanza** [modelscope/facechain#535]
I received a warning during the training phase indicating that the system was insufficient. It said it required 19 or 18 GB of VRAM. It was either 18 or 19, I don't remember exactly.
It might sound a bit silly, but I looked for ways to convert RAM into VRAM, but it seems impossible.
I don't know the working principle, but I have an idea.
Could I possibly complete the training phase from Google Colab or another system, then transfer the training files (if there are any) to my computer and start building the model?

i912900k
36GB RAM
RTX 3070 256 Bit GDDR6 8 GB

**Comment by arafatx** [comment]
8GB vram is not enough

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
