### ISSUE TITLE
build URL failed

### ISSUE THREAD

**Issue by cweihua** [modelscope/facechain#536]
root@autodl-container-62a64293ee-42b86af4:~/facechain# python3 app.py
2024-03-25 09:51:32,859 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-03-25 09:51:32,860 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-03-25 09:51:32,888 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 476ca29614fa9bf6a63f1730a8bad634 and a total number of 946 components indexed
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
app.py:1276: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['/root/facechain/resources/inpaint_template/1.jpg'], ['/root/facechain/resources/inpaint_template/2.jpg'], ['/root/facechain/resources/inpaint_template/3.jpg'], ['/root/facechain/resources/inpaint_template/4.jpg'], ['/root/facechain/resources/inpaint_template/5.jpg']]
app.py:1379: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
[['resources/tryon_garment/garment1.png'], ['resources/tryon_garment/garment2.png'], ['resources/tryon_garment/garment3.png'], ['resources/tryon_garment/garment4.png']]
app.py:1530: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
Running on local URL:  http://127.0.0.1:7860
2024/03/25 09:51:38 [W] [service.go:132] login to server failed: EOF

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
