### ISSUE TITLE
plan for opensource ImageID?

### ISSUE THREAD

**Issue by tachen-cs** [modelscope/facechain#538]
Hi team,

Congrats on the CVPR acceptance! Amazing work on the listening and imaging pipeline introduced in your paper "FaceChain-ImagineID: Freely Crafting High-Fidelity Diverse Talking Faces from Disentangled Audio". I enjoyed reading it. Just wondering about any plan you have to open-source it. 

Best,

**Comment by yaotingwangofficial** [comment]
mark

**Comment by xiao-keeplearning** [comment]
From https://github.com/modelscope/facechain/blob/main/doc/installation_for_talkinghead.md can see
acturally use SadTalker

**Comment by sunbaigui** [comment]
merged to #547
