### ISSUE TITLE
why facechain train with 512 image on XL ?

### ISSUE THREAD

**Issue by SlZeroth** [modelscope/facechain#540]
when train xl lora as you can see in the app.py train image resolution is 512 is it same with sd1.5

I cant understand why facechain 1024 resolution for train XL lora . can you answer this?

because almost  training XL LORA case use 1024 resolution image for train

any reason for use 512 ?

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
