### ISSUE TITLE
有更多的服饰吗

### ISSUE THREAD

**Issue by liaoweiguo** [modelscope/facechain#55]
目前只有几个屌爆了的silver armor之类的

examples = {
    'prompt_male': [
        ['silver armor'],
        ['T-shirt']
    ],
    'prompt_female': [
        ['beautiful traditional hanfu, upper_body'],
        ['an elegant evening gown']
    ],
}

example_styles = [
    {'name': '默认风格(default style)'},
    {'name': '凤冠霞帔(Chinese traditional gorgeous suit)',
     'model_id': 'ly261666/civitai_xiapei_lora',
     'revision': 'v1.0.0',
     'bin_file': 'xiapei.safetensors',
     'multiplier_style': 0.35,
     'add_prompt_style': 'red, hanfu, tiara, crown, '},
]

**Comment by yingdachen** [comment]
迭代中，您也可以自己试着改代码或者从C站下风格lora适配。或者等待项目再添加
