### ISSUE TITLE
图片分辨率设置

### ISSUE THREAD

**Issue by aigconline** [modelscope/facechain#555]
项目介绍分辨率可选512x512, 768x768, 1024x1024, 2048x2048，请问是怎么设置图片的分辨率的？

**Comment by sunbaigui** [comment]
Since we've updated to the newest simplified version, you can now select SR modules from Hugging Face or ModelScope to accomplish this.

**Comment by aigconline** [comment]
Please tell me, is the SR module connected to facechain, or does it wait for facechain to generate the image and then use the SR module to enlarge the image?

**Comment by You-Cun** [comment]
In the previous version of FaceChain (https://github.com/modelscope/facechain/tree/v3.0.0), the SR module is used to enlarge the image generated by FaceChain considering the stability of the style LoRA models.

**Comment by aigconline** [comment]
I built the v3.0.0 version, and the webui shows the resolution. Thank you very much.

**Comment by aigconline** [comment]
`        sr_pipe = pipeline(Tasks.image_super_resolution, model='damo/cv_rrdb_image-super-resolution')
        if portrait_stylization_idx is not None:
            out_results = []
            if int(portrait_stylization_idx) == 0:
                img_cartoon = pipeline(Tasks.image_portrait_stylization, model='damo/cv_unet_person-image-cartoon_compound-models')
            if int(portrait_stylization_idx) == 1:
                img_cartoon = pipeline(Tasks.image_portrait_stylization, model='damo/cv_unet_person-image-cartoon-3d_compound-models')

            for i in range(len(final_gen_results)):
                img = final_gen_results[i]
                img = Image.fromarray(img[:,:,::-1])
                result = img_cartoon(img)[OutputKeys.OUTPUT_IMG]
                cv2.imwrite('tmp.png', result)
                result_img = cv2.imread('tmp.png')
                out_results.append(result_img)

            os.system('rm tmp.png')

            final_gen_results = out_results

        if portrait_stylization_idx is None:
            if 'xl-base' in base_model_path:
                if int(sr_img_size) != 1:
                    out_results = []
                    for i in range(len(final_gen_results)):
                        img = final_gen_results[i]
                        if int(sr_img_size) == 0:
                            out_img = cv2.resize(
                                img, (512, 512),
                                interpolation=cv2.INTER_AREA)
                        else:
                            img = Image.fromarray(img[:,:,::-1])
                            out_img = sr_pipe(img)['output_img']
                            if int(sr_img_size) == 2:
                                new_h = 1024
                                new_w = 1024
                            else:
                                new_h = 2048
                                new_w = 2048
                            out_img = cv2.resize(
                                out_img, (new_w, new_h),
                                interpolation=cv2.INTER_AREA)
                        out_results.append(out_img)
                    final_gen_results = out_results
            else:
                if int(sr_img_size) != 0:
                    out_results = []
                    for i in range(len(final_gen_results)):
                        img = final_gen_results[i]
                        img = Image.fromarray(img[:,:,::-1])
                        out_img = sr_pipe(img)['output_img']
                        ratio = 1
                        if int(sr_img_size) == 1:
                            ratio = 0.375
                        elif int(sr_img_size) == 2:
                            ratio = 0.5
                        if ratio < 1:
                            out_img = cv2.resize(
                                out_img, (0, 0),
                                fx=ratio,
                                fy=ratio,
                                interpolation=cv2.INTER_AREA)
                        out_results.append(out_img)
                    final_gen_results = out_results`
May I ask why this code was removed from the latest main branch? Is it unstable?
