### ISSUE TITLE
请问在modelscope的notebook中执行git clone失败是什么原因呢

### ISSUE THREAD

**Issue by fytxlj** [modelscope/facechain#559]
root@dsw-504553-5c546cd576-lczdq:/mnt/workspace# GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/modelscope/facechain.git --depth 1
正克隆到 'facechain'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (239/239), done.
error: RPC 失败。curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: 远端意外挂断了
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败

**Comment by sunbaigui** [comment]
这个你可以查阅相关文档看如何解决，有时多尝试几次即可，这是个常见的问题，这边就先关闭了。
