### ISSUE TITLE
和“妙鸭”的差距大吗？

### ISSUE THREAD

**Issue by dragen1860** [modelscope/facechain#56]
有人跑起来额吗，和“妙鸭”的差距大不大，差距在哪些地方呢？谢谢

**Comment by tastelikefeet** [comment]
思路不同，妙鸭类似局部inpaint，facechain整体画面都是生成的，不需要模板。另外，facechain只需要一张照片，训练和推理比较快

**Comment by xylcbd** [comment]
试了一下，目前生成的图片完全不像同一个人，这块感觉需要优化。

**Comment by yingdachen** [comment]
持续迭代中。具体效果可以大家自己试试。在modelscope创空间或者自己基于镜像+源代码等方式都可以的

**Comment by Anychnn** [comment]
调用了下diffusers库而已，默认脚本连train_text_encoder都没打开，效果很令人汗颜啊

**Comment by y3093** [comment]
其实有更方便快速低成本的方案，和本人照片相似度很高…… 对硬件要求配置也低很多；已开发相应的小程序（AI多面体），目前在内测中，近半个月内会上线~

**Comment by Anychnn** [comment]
> 其实有更方便快速低成本的方案，和本人照片相似度很高…… 对硬件要求配置也低很多；已开发相应的小程序（AI多面体），目前在内测中，近半个月内会上线~

有试用链接吗

**Comment by y3093** [comment]
> 

在内部测试中，修复bug和调prompt稳定了就会开始对外推了~ 半个月内会正式上线

**Comment by y3093** [comment]
> > 其实有更方便快速低成本的方案，和本人照片相似度很高…… 对硬件要求配置也低很多；已开发相应的小程序（AI多面体），目前在内测中，近半个月内会上线~
> 
> 有试用链接吗

在内部测试中，修复bug和调prompt稳定了就会开始对外推了~ 半个月内会正式上线

**Comment by y3093** [comment]
> > 其实有更方便快速低成本的方案，和本人照片相似度很高…… 对硬件要求配置也低很多；已开发相应的小程序（AI多面体），目前在内测中，近半个月内会上线~
> 
> 有试用链接吗

在内部测试中，修复bug和调prompt稳定了就会开始对外推了~ 半个月内会正式上线

**Comment by dragen1860** [comment]
谁能透露一下“妙鸭”的方案么？

**Comment by feixueck** [comment]
> > > 其实有更方便快速低成本的方案，和本人照片相似度很高…… 对硬件要求配置也低很多；已开发相应的小程序（AI多面体），目前在内测中，近半个月内会上线~
> > 
> > 
> > 有试用链接吗
> 
> 在内部测试中，修复bug和调prompt稳定了就会开始对外推了~ 半个月内会正式上线

期待,希望早点面世

**Comment by y3093** [comment]
> 

谢谢~ 
这两天研究发布正式版本，发现要做算法备案，吐了……
问了下机构，要3w块钱，审核需要等4个月左右 T T

在研究怎么解决

**Comment by y3093** [comment]
> > > > 其实有更方便快速低成本的方案，和本人照片相似度很高…… 对硬件要求配置也低很多；已开发相应的小程序（AI多面体），目前在内测中，近半个月内会上线~
> > > 
> > > 
> > > 有试用链接吗
> > 
> > 
> > 在内部测试中，修复bug和调prompt稳定了就会开始对外推了~ 半个月内会正式上线
> 
> 期待,希望早点面世

感谢期待~
最近在研究发布正式版，发现要做算法备案……
问了下代办机构，要3w块钱，耗时4个月左右…… 吐了 T T

在研究如何曲线救国

**Comment by jiqizaisikao** [comment]
我自己修改开源代码，训练了一个模型，微信最新小程序<换影CP>可以一键换头，换脸型，类似于Adobe的生成填充，不过需要不小的资源进行训练，我现在已经没有足够的资源进行训练和优化了，希望能找到合作伙伴共同研究和开发，谢谢！
![WechatIMG59](https://github.com/modelscope/facechain/assets/16893734/125b54a9-fdfe-4933-a462-f15bbad77754)
![WechatIMG58](https://github.com/modelscope/facechain/assets/16893734/59a51508-9a6a-4ac2-b652-a23fe535271e)
![WechatIMG54](https://github.com/m
![WechatIMG55](https://github.com/modelscope/facechain/assets/16893734/100e5834-fc99-41b5-bfb9-2ad1748cc7a3)
odelscope/facechain/assets/16893734/f8ff2f71-4329-4de5-8de0-d7864228fa18)

**Comment by jiqizaisikao** [comment]
不需要使用时候训练，只需要一张照片和一个模版，不过崩坏概率较高，可能是因为inpaiting条件限制太多，导致了冲突，而妙鸭这样的文生图具有较大的容错空间

**Comment by dragen1860** [comment]
> 

妙鸭不是文生图吧？ 他不是有参考模板么
