### ISSUE TITLE
modelscope notebook运行成功，但是什么都不能点

### ISSUE THREAD

**Issue by leafiy** [modelscope/facechain#561]
![image](https://github.com/modelscope/facechain/assets/870449/2873e5da-682f-45e2-bf9b-f8f143c90eee)
![image](https://github.com/modelscope/facechain/assets/870449/4de884ca-225e-4757-9b33-811ed9dcaecc)

**Comment by mountlin** [comment]
I also encountered this problem when using modelscope notebook. It seems that the proxy of AliYun PAI-DSW restricts direct access to WebUI Assets. I later deployed directly using AliYun PAI-DSW. The process is similar and there is no such problem.
BTW, PAI-DSW has a free trial quota that can be claimed.

**Comment by sunbaigui** [comment]
> I also encountered this problem when using modelscope notebook. It seems that the proxy of AliYun PAI-DSW restricts direct access to WebUI Assets. I later deployed directly using AliYun PAI-DSW. The process is similar and there is no such problem. BTW, PAI-DSW has a free trial quota that can be claimed.

@wangxingjun778 please check this out.

**Comment by sunbaigui** [comment]
@leafiy This is caused by the existing memory fragmentation issue. Currently, there is a restart mechanism on ModelScope that can ensure its use.
