### ISSUE TITLE
Remove/delete?

### ISSUE THREAD

**Issue by Sirmadsen** [modelscope/facechain#563]
Hi,

Where are all the models downloaded to? I want to delete the extension but can't find all the models that it downloaded.

**Comment by You-Cun** [comment]
The models downloaded by modelscope.snapshot_download are saved in MODELSCOPE_CACHE. The default path is ~/.cache/modelscope, and you can adjust it by "export MODELSCOPE_CACHE=/path/to/cache/directory".
