### ISSUE TITLE
是否可以扩展到其它的基础模型

### ISSUE THREAD

**Issue by cqflgl** [modelscope/facechain#567]
感谢大佬们的辛苦付出和开源！
facechain-fact似乎只适用于指定的leosamsMoonfilm和majic基础模型，是否可以参考InstantID（只能用于SDXL版本），将适用范围扩展到所有基于SD1.5的大模型？
如果可以，因为SD1.5的强大社区生态，相信facechain-fact的使用者会更多。

**Comment by You-Cun** [comment]
Theoretically FaceChain can be extended to other SD1.5 models with probable performance drop according to the difference between the base models in training and inference. You can achieve this by modifying the base model path in facechain/inference_fact.py.

**Comment by sunbaigui** [comment]
> Theoretically FaceChain can be extended to other SD1.5 models with probable performance drop according to the difference between the base models in training and inference. You can achieve this by modifying the base model path in facechain/inference_fact.py.

@cqflgl FACT was designed with an emphasis on enhanced compatibility with the SD1.5 ecosystem. You can attempt the process by following the previously mentioned steps.
