### ISSUE TITLE
compatibility issue between modelscope and mmcv

### ISSUE THREAD

**Issue by JohnsonXi** [modelscope/facechain#568]
There seems to be a compatibility issue between modelscope and mmcv. When modelscope=1.9.0, there are errors when mmcv-full=1.7.2 or mmcv>2.0.0. Could you please specify the required versions of modelscope and mmcv in the requirements.txt file or the documentation?

**Comment by ly19965** [comment]
please refer to the official install documents of modelscope: https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85

**Comment by huangxin168** [comment]
按照这里安装mmcv：https://modelscope.cn/docs/intro/environment-setup
