### ISSUE TITLE
Initiates huge downloads on webui start

### ISSUE THREAD

**Issue by sou-long** [modelscope/facechain#571]
Installing facechain and restarting sd-webui initiated downloading of multiple models from "modelscope" hub, as far as I understand it. There's no indication of how many models would be downloaded (now it's 3.8GB total and still goes). The download location is %userprofile%/.cache/modelscope/hub (on windows). 

Is that normal? I see that models are named similarly to the images in `style_image` folder, and if there's 1:1 correspondence, I infer some multi-dozen-gigabytes and hours of downloads. Something went wrong with my install I guess. 

If I delete extensions/facechain, sd-webui starts as usual. If I clone it back, downloads resume (from where I interrupted them last time).

Update: I tested it on a clean sd-webui installation to make sure it's not misconfig. After downloading all these models, when I start sd-webui, facechain checks all the models again, which takes around a few minutes only to start webui.
![image](https://github.com/modelscope/facechain/assets/93844085/254c10db-6267-4cba-a435-535d75c664c7)

**Comment by wenmengzhou** [comment]
“After downloading all these models, when I start sd-webui, facechain checks all the models again, which takes around a few minutes only to start webui.”

a few minutes are taken to initalize models which can not be optimized

**Comment by ldavis9000aws** [comment]
30GB download of models and counting....absolutely ridiculous...
