### ISSUE TITLE
app.py默认开启了share=True，导致使用者可能在未知情时暴露内网服务

### ISSUE THREAD

**Issue by LJFYYJ** [modelscope/facechain#574]
危害：app.py的demo.queue(status_update_rate=1).launch(share=True)，默认开启了gradio的share=True，导致可能在使用者未知情的情况下，直接打通frp隧道，向公网暴露内网服务，增加使用者机器被入侵的风险。
参考：stable-diffusion-webui项目，默认在运行./webui.sh时是share=False的；除非加上参数./webui.sh --share，才会打通frp隧道，提供公网可访问的服务。
建议：在app.py中去掉share=True参数，保证默认配置的安全，即默认只在127.0.0.1:7860上提供服务。用户如果需要开放公网可访问的服务，可以自己添加相应参数。

**Comment by sunbaigui** [comment]
Thank you for the feedback, it has been corrected.
