### ISSUE TITLE
facechain prevents Stable Diffusion WebUI from starting

### ISSUE THREAD

**Issue by soundprayer** [modelscope/facechain#576]
I have two instances of SD WebUI (1.9.4 and 1.8.x) installed via Stability Matrix. In every one of them installing Facechain make webui stuck forever at the beginning with no error code. Removing extension manually from extensions folder make SD webUI start again with no problems

**Comment by nitinmukesh** [comment]
Same problem

**Comment by wenmengzhou** [comment]
can you provide some logs？Maybe downloading models

**Comment by nitinmukesh** [comment]
> can you provide some logs？Maybe downloading models

I have posted the logs here
https://github.com/modelscope/facechain/issues/577

**Comment by wenmengzhou** [comment]
duplicated with #576

**Comment by mr-september** [comment]
Malware behaviour. Never asked for consent, just straight up downloaded many GBs of models.
