### ISSUE TITLE
Gradio unable to display all pictures in Aliyun

### ISSUE THREAD

**Issue by leonchen2012** [modelscope/facechain#578]
I followed the advice to rent a A10 GPU machine on Aliyun, and run the notebook successfully. 
Here is what I got when clicking on "http://127.0.0.1:7860"(Aliyun opened this url as "https://dsw-gateway-cn-hangzhou.data.aliyun.com/dsw-543203/proxy/7860/"
![nopic](https://github.com/modelscope/facechain/assets/4454566/1cdcab06-7c9b-4924-91fc-78f00f3f6ccd)

I opened the crapped picture file, the url  is "https://dsw-gateway-cn-hangzhou.data.aliyun.com/file=/tmp/gradio/396b3223dcf63a761737db074bd2bb80f7dce2ca/Bleak_autumn.jpg".

Suspect that there are some compatibility issue between Gradio and Aliyun? Maybe there is some kind of root folder setting or file serving setting?

I clicked & uploaded a photo, but the "generate" button didn't work under this situation.

**Comment by You-Cun** [comment]
Please refer to issue https://github.com/modelscope/facechain/issues/561.
