### ISSUE TITLE
RuntimeError: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by lvsh2012** [modelscope/facechain#580]
gradio 正常启动了，但是在生成的时报错：RuntimeError: nms_impl: implementation for device cuda:0 not found.‘’

#70 按照方式还是不行

(facechain) root@dl:/mnt/code/facechain# pip show mmcv-full
Name: mmcv-full
Version: 1.7.2
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: /mnt/conda/envs/facechain/lib/python3.8/site-packages
Requires: addict, numpy, packaging, Pillow, pyyaml, yapf

(facechain) root@dl:/mnt/code/facechain# pip show torch
Name: torch
Version: 2.3.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /mnt/conda/envs/facechain/lib/python3.8/site-packages

**Comment by You-Cun** [comment]
There may be many reasons for such error. You can try the checking methods in https://blog.csdn.net/seven_hells/article/details/134864191 to ensure the version of PyTorch and CUDA.
