### ISSUE TITLE
这个项目跟easy-photo有关联吗？

### ISSUE THREAD

**Issue by Pevernow** [modelscope/facechain#585]
没有别的意思，只是单纯觉得有点像。
都是用sd做个人写真的。
想问问有哪些异同点？

**Comment by sunbaigui** [comment]
The authors of Easy-Photo has also made significant contributions to FaceChain, both projects are distinctive and well-crafted, and I recommend paying attention to and using them both, as they are both actively maintained and meticulously open-source projects.
