### ISSUE TITLE
FaceChain-SuDe 是否支持多个参考主题的生成

### ISSUE THREAD

**Issue by JoshonSmith** [modelscope/facechain#586]
good work!
请问 FaceChain-SuDe 是否支持多个参考主题的生成，比如输入一张男孩和一张女孩的图像，生成合照

**Comment by sunbaigui** [comment]
@slpal please check this out.

**Comment by qpc1611094** [comment]
FaceChain-SuDe is only designed to make generated attributes more diverse, thus it does not have the ability to build multiple subjects on its own. But it can still work for enriching attributes when combined with existing multi-subject works, such as CustomDiffusion, Cones 2, etc.
