### ISSUE TITLE
mmcv版本不兼容

### ISSUE THREAD

**Issue by Pevernow** [modelscope/facechain#587]
mmcv1.7.2最高仅支持到torch2.1.2
torch2.2,2.3,2.4只支持mmcv2.2

请尽快迁移到mmcv2.x上

**Comment by ly19965** [comment]
由于modelsocpe包含太多的模型，适配起来很麻烦，估计暂时没有升级的打算，可以找modelscope官方答疑群确定下相应计划

**Comment by ucasiggcas** [comment]
大佬帮忙看下这个问题，
https://github.com/modelscope/modelscope/issues/937

**Comment by HobbitArmy** [comment]
torch2.4只支持mmcv2.2 ????
Soga

**Comment by huangxin168** [comment]
按照这里装 mmcv：https://modelscope.cn/docs/intro/environment-setup
