### ISSUE TITLE
Nothing showing on Facechain tab

### ISSUE THREAD

**Issue by clacheek** [modelscope/facechain#591]
Installation was smooth with no errors, but is there supposed to be anything on the Facechain tab? What am I missing? The README instructions are vague on how this thing even works. Please improve the documentation, or else there will always be someone like me asking dumb questions. Since there are no error prompts, there's nothing else to report. Here's a screenshot. **I'm using ReForge WebUI (it's a Forge fork because Forge is long dead).**
![image](https://github.com/user-attachments/assets/6eddfc24-3867-4a1b-a005-305db02d0684)

**Comment by wenmengzhou** [comment]
can you use sdwebui？ we haven't tested using Reforge webui
