### ISSUE TITLE
在魔塔社区notebook中不管是ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.1还是其他镜像，都不能正常运行成功

### ISSUE THREAD

**Issue by love530love** [modelscope/facechain#598]
# Step1: 我的notebook -> PAI-DSW -> GPU环境

# Step2: 进入Notebook cell，执行下述命令从github clone代码：
!GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/modelscope/facechain.git --depth 1

# Step3: 切换当前工作路径，安装依赖
import os
os.chdir('/mnt/workspace/facechain')    # 注意替换成上述clone后的代码文件夹主路径
print(os.getcwd())

!pip3 install gradio==3.50.2
!pip3 install controlnet_aux==0.0.6
!pip3 install python-slugify
!pip3 install onnxruntime==1.15.1
!pip3 install edge-tts
!pip3 install modelscope==1.10.0

# Step4: 启动服务，点击生成的URL即可访问web页面，上传照片开始训练和预测
!python3 app.py

按以上要求运行后打开的网页无法使用。
换了多种调试方法还是无法正常运行，反复处于这种状态：
![微信截图_20240828165352](https://github.com/user-attachments/assets/1ab6eff8-88e4-4082-bced-e34a16efeefa)

**Comment by sunbaigui** [comment]
@You-Cun please check this.

**Comment by sunbaigui** [comment]
merged to #597
