### ISSUE TITLE
我是否可以预下载这些模型，下载的模型应该放在哪个目录下，请教

### ISSUE THREAD

**Issue by changqingla** [modelscope/facechain#599]

**Comment by cyscn** [comment]
修改PYTHONPATH/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py 70行
if isinstance(cache_dir, Path):
        cache_dir = str(cache_dir)
下面添加：
cache_dir = '你的指定目录/.cache'即可
这个'你的指定目录/.cache'你得先mkdir好
