### ISSUE TITLE
Can facechain be deployed on multiple Gpus for concurrent training and inference?

### ISSUE THREAD

**Issue by woshiodoman** [modelscope/facechain#602]
Can facechain be deployed on multiple Gpus for concurrent training and inference?

**Comment by sunbaigui** [comment]
@You-Cun please check this.

**Comment by You-Cun** [comment]
Currently we do not support training and inference on multiple GPUs in Gradio interface. It is suggested to modify run_inference.py for multiple GPU for script execution.

**Comment by woshiodoman** [comment]
> Currently we do not support training and inference on multiple GPUs in Gradio interface. It is suggested to modify run_inference.py for multiple GPU for script execution.

Thank you so much, I'll try it.
