### ISSUE TITLE
[TopoFR] result on MFR

### ISSUE THREAD

**Issue by TranThanh96** [modelscope/facechain#609]
I found your model on MFR: http://iccv21-mfr.com/#/leaderboard/academic 
Is that correct? Which dataset did you use for training? 
Have you tried training with WF42M, and if so, what were your results?

**Comment by DanJun6737** [comment]
Hi @TranThanh96 ~

In fact, the model we published on MFR was trained using the WebFace42M dataset. For a detailed analysis of the results, please refer to our [paper](https://arxiv.org/abs/2410.10587). It is worth mentioning that to ensure our TopoFR model achieves outstanding generalization performance on MFR, we applied insights and tricks we gathered from our experiences in previous competitions during its training.

**Comment by TranThanh96** [comment]
@DanJun6737 Can you share some tips? and when will you update source code training with partial fc ?
