### ISSUE TITLE
这个里面的模型可以换吗 不够写实

### ISSUE THREAD

**Issue by jjiikkkk** [modelscope/facechain#61]
搞出来的人像还是很卡通啊

**Comment by wen020** [comment]
+1

**Comment by sunbaigui** [comment]
风格模型可自由切换，需要配套改些东西，目前已有部分教程。完整教程后面会单独出。请耐心等待。可以关注魔搭公众号每周周报。

**Comment by hemath1001** [comment]
> 风格模型可自由切换，需要配套改些东西，目前已有部分教程。完整教程后面会单独出。请耐心等待。可以关注魔搭公众号每周周报。

棒！想问下“风格模型”说的是推断时候即插即用的LORA对吧，但感觉要追求更真实的话，得把人脸LORA训练时所用的y261666\cv_portrait_model这里的模型也更换吧？这里的模型可以更换吗（感觉这部分文件都是魔塔专门的格式？），这部分算是非开源的吗~ 感谢回复！
