### ISSUE TITLE
TopoFR 训练CUDA out of memory

### ISSUE THREAD

**Issue by sssssshf** [modelscope/facechain#615]
训练模型时报错 内存不足，与arcface训练参数一致，但在这会报错误。 不知道为什么，有没有大佬解答一下 ，我把batchsize 压缩到32都还是会报错。显卡 两个 32G 
![image](https://github.com/user-attachments/assets/f6705c6f-c52c-48e3-9cdf-d6b65a35c1c9)

配置文件如下：
![image](https://github.com/user-attachments/assets/ec6fa13b-6955-4bfb-80d7-25060beaf6e2)

**Comment by sunbaigui** [comment]
hi @DanJun6737 , Please take a look at this when you get a chance.

**Comment by sssssshf** [comment]
> Hi~ @sssssshf 这就是显存不足报错 TopoFR我们是采用了四张卡训练 两张卡的话你尝试把r100改为r50试试，或者再减小一下batch-size. 卡多一点性能能够好一点

有点跟之前的显存不足报的错有区别，我同样的配置在arcface可以训练起来，我现在把 batchsize改成1 都是报错的状态 我把网络模型都改成res18也是报错

**Comment by DanJun6737** [comment]
Hi @sssssshf 
那尝试多两张卡试试？这套程序我们验证了是没有问题的。arcface不那么吃训练资源，TopoFR需要多一点的训练资源。因为TopoFR的拓扑结构对齐策略是需要一定的计算量的，并且是需要在足够的点上构建单纯复形，一般不建议batch-size设为1.

**Comment by sssssshf** [comment]
> Hi @sssssshf 那尝试多两张卡试试？这套程序我们验证了是没有问题的。arcface不那么吃训练资源，TopoFR需要多一点的训练资源。因为TopoFR的拓扑结构对齐策略是需要一定的计算量的，并且是需要在足够的点上构建单纯复形，一般不建议batch-size设为1.

我知道不设为1  就是像看下缩小下batchsize会不会报这个错 我再看下哪里出的问题。

**Comment by DanJun6737** [comment]
@sssssshf 
config.margin_list = (1.0, 0.5, 0.0) 改为这个试试 
要是还是报错显存不足 那估计得多加几张卡训练

**Comment by sssssshf** [comment]
> @sssssshf config.margin_list = (1.0, 0.5, 0.0) 改为这个试试 要是还是报错显存不足 那估计得多加几张卡训练

![image](https://github.com/user-attachments/assets/b3207b31-deaf-4b85-932b-1d8ca2130af6)
还是会吧会报错。。。您那边用这个参数会报错吗  大概多少个g显存训练的模型

**Comment by DanJun6737** [comment]
@sssssshf 用4张32G的卡试。4张V100跑R50/R100/R200框架肯定是没有问题的。
