### ISSUE TITLE
docker pull always failed.

### ISSUE THREAD

**Issue by hujunyao** [modelscope/facechain#617]
docker pull registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.1

It complains:

docker pull registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.8.1
Error response from daemon: Get "https://registry.cn-hangzhou.aliyuncs.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

it seems the address expired?

**Comment by sunbaigui** [comment]
hi @You-Cun , Please take a look at this when you get a chance.

**Comment by You-Cun** [comment]
It may be a temporary issue with the server or network. Please try again after a while and check if there exists same problem.
