### ISSUE TITLE
error installing today

### ISSUE THREAD

**Issue by lgwjames** [modelscope/facechain#618]
*** Error executing callback ui_tabs_callback for C:\Users\jessi\Desktop\SD Forge\webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\Users\jessi\Desktop\SD Forge\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference_fact import GenPortrait
      File "C:\Users\jessi\Desktop\SD Forge\webui\extensions\facechain\facechain\inference_fact.py", line 20, in <module>
        from modelscope.pipelines import pipeline
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
        from modelscope.msdatasets import MsDataset
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
        from modelscope.msdatasets.ms_dataset import MsDataset
      File "C:\Users\jessi\Desktop\SD Forge\webui\venv\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
        from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
    ModuleNotFoundError: No module named 'datasets'

---

**Comment by sunbaigui** [comment]
hi @You-Cun , Please take a look at this when you get a chance.

**Comment by Hunt3rseeker** [comment]
I am having the same issue.

**Comment by Helge666** [comment]
Same issue:

> *** Error executing callback ui_tabs_callback for C:\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py
>     Traceback (most recent call last):
>       File "C:\automatic1111\modules\script_callbacks.py", line 283, in ui_tabs_callback
>         res += c.callback() or []
>       File "C:\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
>         import app
>       File "C:\automatic1111\extensions\facechain\app.py", line 16, in <module>
>         from facechain.inference_fact import GenPortrait
>       File "C:\automatic1111\extensions\facechain\facechain\inference_fact.py", line 20, in <module>
>         from modelscope.pipelines import pipeline
>       File "c:\automatic1111\venv\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
>         from .base import Pipeline
>       File "c:\automatic1111\venv\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
>         from modelscope.msdatasets import MsDataset
>       File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
>         from modelscope.msdatasets.ms_dataset import MsDataset
>       File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
>         from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
>     ModuleNotFoundError: No module named 'datasets'

Windows 10, RTX 3090 24GB

**Comment by blounolito** [comment]
I found that you need to install a very specific version of datasets in order to make it works.
I added this in my pip libraries ;
```
datasets==2.16.0
oss2
```

**Comment by scooller** [comment]
I hace the same error

**Comment by TungyuYoung** [comment]
same error. don't know how to fix it...

**Comment by applefryduck** [comment]
> Same issue. Windows 10, RTX 3090 24GB
> 
> > *** Error executing callback ui_tabs_callback for C:\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py
> > Traceback (most recent call last):
> > File "C:\automatic1111\modules\script_callbacks.py", line 283, in ui_tabs_callback
> > res += c.callback() or []
> > File "C:\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
> > import app
> > File "C:\automatic1111\extensions\facechain\app.py", line 16, in 
> > from facechain.inference_fact import GenPortrait
> > File "C:\automatic1111\extensions\facechain\facechain\inference_fact.py", line 20, in 
> > from modelscope.pipelines import pipeline
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\pipelines__init__.py", line 4, in 
> > from .base import Pipeline
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\pipelines\base.py", line 16, in 
> > from modelscope.msdatasets import MsDataset
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets__init__.py", line 2, in 
> > from modelscope.msdatasets.ms_dataset import MsDataset
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in 
> > from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
> > ModuleNotFoundError: No module named 'datasets'
> 
> You can overcome this and the following ModuleNotFoundError by installing the missing modules:
> 
> PS C:\automatic1111\venv\Scripts> .\activate.ps1 (venv) PS C:\automatic1111\venv\Scripts> pip install datasets oss2
> 
> But after doing that, you'll run into this error:
> 
> > *** Error executing callback ui_tabs_callback for C:\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py
> > Traceback (most recent call last):
> > File "C:\automatic1111\modules\script_callbacks.py", line 283, in ui_tabs_callback
> > res += c.callback() or []
> > File "C:\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
> > import app
> > File "C:\automatic1111\extensions\facechain\app.py", line 16, in 
> > from facechain.inference_fact import GenPortrait
> > File "C:\automatic1111\extensions\facechain\facechain\inference_fact.py", line 20, in 
> > from modelscope.pipelines import pipeline
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\pipelines__init__.py", line 4, in 
> > from .base import Pipeline
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\pipelines\base.py", line 16, in 
> > from modelscope.msdatasets import MsDataset
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets__init__.py", line 2, in 
> > from modelscope.msdatasets.ms_dataset import MsDataset
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 24, in 
> > from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
> > File "c:\automatic1111\venv\lib\site-packages\modelscope\msdatasets\utils\hf_datasets_util.py", line 44, in 
> > from datasets.utils.file_utils import (OfflineModeIsEnabled,
> > ImportError: cannot import name 'OfflineModeIsEnabled' from 'datasets.utils.file_utils' (c:\automatic1111\venv\lib\site-packages\datasets\utils\file_utils.py)

The command , pip install datasets, would install the latest datasets package, which is incompactable with modelscope.
I solved the issue by installing the older version datasets with pip install datasets==2.*

**Comment by scooller** [comment]
now i have error
` DLL load failed while importing _ext: No se encontró el proceso especificado.`

**Comment by You-Cun** [comment]
Please install datasets newer than 2.16.0.

**Comment by sunbaigui** [comment]
merge to #623
