### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by kanglue** [modelscope/facechain#621]
follow conda install instruction, encounter error message.

(facechain) root@efa0a5b27714:/home/facechain# python app.py
Traceback (most recent call last):
  File "/home/facechain/app.py", line 9, in <module>
    import gradio as gr
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 7, in <module>
    from gradio.components.base import Component, FormComponent
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/gradio/components/__init__.py", line 39, in <module>
    from gradio.components.native_plot import BarPlot, LinePlot, NativePlot, ScatterPlot
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/gradio/components/native_plot.py", line 12, in <module>
    import pandas as pd
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/opt/conda/envs/facechain/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Package                      Version
---------------------------- -------------------
absl-py                      2.1.0
accelerate                   1.0.1
addict                       2.4.0
aiofiles                     23.2.1
aiohappyeyeballs             2.4.3
aiohttp                      3.10.10
aiosignal                    1.3.1
aliyun-python-sdk-core       2.16.0
aliyun-python-sdk-kms        2.16.5
annotated-types              0.7.0
anyio                        4.6.2.post1
astunparse                   1.6.3
async-timeout                4.0.3
attrs                        24.2.0
basicsr                      1.4.2
cachetools                   5.5.0
certifi                      2024.8.30
cffi                         1.17.1
charset-normalizer           3.4.0
click                        8.1.7
coloredlogs                  15.0.1
contourpy                    1.2.1
controlnet-aux               0.0.6
crcmod                       1.7
cryptography                 43.0.3
cycler                       0.12.1
datasets                     3.0.2
diffusers                    0.19.0
dill                         0.3.8
edge-tts                     6.1.15
einops                       0.8.0
exceptiongroup               1.2.2
facexlib                     0.3.0
fastapi                      0.115.4
ffmpy                        0.4.0
filelock                     3.16.1
filterpy                     1.4.5
flatbuffers                  24.3.25
fonttools                    4.54.1
frozenlist                   1.5.0
fsspec                       2024.9.0
future                       1.0.0
gast                         0.6.0
gfpgan-patch                 1.3.8
google-auth                  2.35.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
gradio                       5.4.0
gradio_client                1.4.2
grpcio                       1.67.0
h11                          0.14.0
h5py                         3.12.1
httpcore                     1.0.6
httpx                        0.27.2
huggingface-hub              0.26.1
humanfriendly                10.0
idna                         3.10
imageio                      2.36.0
importlib_metadata           8.5.0
invisible-watermark          0.2.0
jax                          0.4.30
jaxlib                       0.4.30
Jinja2                       3.1.4
jmespath                     0.10.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.7
libclang                     18.1.1
llvmlite                     0.43.0
lmdb                         1.5.1
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.8.4
mdurl                        0.1.2
mediapipe                    0.10.11
ml_dtypes                    0.5.0
mmcv-full                    1.7.2
mmdet                        2.26.0
mmengine                     0.10.5
modelscope                   1.10.0
mpmath                       1.3.0
multidict                    6.1.0
multiprocess                 0.70.16
networkx                     3.4.2
numba                        0.60.0
numpy                        2.0.2
nvidia-cublas-cu11           11.11.3.6
nvidia-cublas-cu12           12.4.5.8
nvidia-cuda-cupti-cu11       11.8.87
nvidia-cuda-cupti-cu12       12.4.127
nvidia-cuda-nvrtc-cu11       11.8.89
nvidia-cuda-nvrtc-cu12       12.4.127
nvidia-cuda-runtime-cu11     11.8.89
nvidia-cuda-runtime-cu12     12.4.127
nvidia-cudnn-cu11            9.1.0.70
nvidia-cudnn-cu12            9.1.0.70
nvidia-cufft-cu11            10.9.0.58
nvidia-cufft-cu12            11.2.1.3
nvidia-curand-cu11           10.3.0.86
nvidia-curand-cu12           10.3.5.147
nvidia-cusolver-cu11         11.4.1.48
nvidia-cusolver-cu12         11.6.1.9
nvidia-cusparse-cu11         11.7.5.86
nvidia-cusparse-cu12         12.3.1.170
nvidia-nccl-cu11             2.21.5
nvidia-nccl-cu12             2.21.5
nvidia-nvjitlink-cu12        12.4.127
nvidia-nvtx-cu11             11.8.86
nvidia-nvtx-cu12             12.4.127
oauthlib                     3.2.2
onnxruntime                  1.15.1
opencv-contrib-python        4.10.0.84
opencv-python                4.10.0.84
opt_einsum                   3.4.0
orjson                       3.10.10
oss2                         2.19.1
packaging                    24.1
pandas                       2.0.3
pillow                       11.0.0
pip                          24.2
platformdirs                 4.3.6
propcache                    0.2.0
protobuf                     3.20.1
psutil                       6.1.0
pyarrow                      18.0.0
pyasn1                       0.6.1
pyasn1_modules               0.4.1
pycocotools                  2.0.8
pycparser                    2.22
pycryptodome                 3.21.0
pydantic                     2.9.2
pydantic_core                2.23.4
pydub                        0.25.1
Pygments                     2.18.0
pyparsing                    3.2.0
python-dateutil              2.9.0.post0
python-multipart             0.0.12
python-slugify               8.0.4
pytz                         2024.2
PyWavelets                   1.4.1
PyYAML                       6.0.2
regex                        2024.9.11
requests                     2.32.3
requests-oauthlib            2.0.0
rich                         13.9.3
rsa                          4.9
ruff                         0.7.1
safehttpx                    0.1.1
safetensors                  0.4.5
scikit-image                 0.19.3
scipy                        1.14.1
semantic-version             2.10.0
setuptools                   75.1.0
shellingham                  1.5.4
simplejson                   3.19.3
six                          1.16.0
sniffio                      1.3.1
sortedcontainers             2.4.0
sounddevice                  0.5.1
starlette                    0.41.2
sympy                        1.13.1
tb-nightly                   2.19.0a20241024
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.0
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.5.0
terminaltables               3.1.10
text-unidecode               1.3
tf-estimator-nightly         2.8.0.dev2021122109
tifffile                     2024.9.20
timm                         1.0.11
tokenizers                   0.20.1
tomli                        2.0.2
tomlkit                      0.12.0
torch                        2.5.0+cu118
torchaudio                   2.5.0+cu118
torchvision                  0.20.0
tqdm                         4.66.5
transformers                 4.46.0
triton                       3.1.0
typer                        0.12.5
typing_extensions            4.12.2
tzdata                       2024.2
urllib3                      2.2.3
uvicorn                      0.32.0
websockets                   12.0
Werkzeug                     3.0.6
wheel                        0.44.0
wrapt                        1.16.0
xxhash                       3.5.0
yapf                         0.40.2
yarl                         1.16.0
zipp                         3.20.2

**Comment by sunbaigui** [comment]
hi @You-Cun , Please take a look at this when you get a chance.

**Comment by You-Cun** [comment]
It seems like the version is numpy is too high, you can try 1.22.0. A feasible environment is as follows for reference.
Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
accelerate                    0.21.0
adaseq                        0.6.4
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.8.5
aiosignal                     1.3.1
albumentations                1.3.1
aliyun-python-sdk-core        2.13.36
aliyun-python-sdk-kms         2.16.1
altair                        5.4.1
aniso8601                     9.0.1
annotated-types               0.5.0
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
apex                          0.1
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astor                         0.8.1
astropy                       5.2.2
asttokens                     2.2.1
astunparse                    1.6.3
async-lru                     2.0.4
async-timeout                 4.0.2
attrs                         23.1.0
audioread                     3.0.0
av                            10.0.0
Babel                         2.12.1
backcall                      0.2.0
backports.zoneinfo            0.2.1
basicsr                       1.4.2
beautifulsoup4                4.12.2
biopython                     1.81
bitarray                      2.8.0
bitsandbytes                  0.41.0
bitstring                     4.0.2
black                         23.7.0
bleach                        6.0.0
blis                          0.7.10
blobfile                      2.0.2
bmt-clipit                    1.0
boltons                       23.0.0
boto3                         1.28.16
botocore                      1.31.16
cachetools                    5.3.1
catalogue                     2.0.9
certifi                       2023.5.7
cffi                          1.15.1
cfgv                          3.3.1
charset-normalizer            2.0.4
chumpy                        0.70
cityscapesScripts             2.2.2
click                         8.0.4
clip                          1.0
cloudpickle                   2.2.1
cmake                         3.27.0
colorama                      0.4.6
coloredlogs                   14.0
comm                          0.1.3
conda                         23.5.0
conda-content-trust           0.1.3
conda-package-handling        1.9.0
confection                    0.1.0
ConfigArgParse                1.7
contextlib2                   21.6.0
contourpy                     1.1.0
control-ldm                   0.0.1
controlnet-aux                0.0.6
crcmod                        1.7
cryptography                  39.0.1
cycler                        0.11.0
cymem                         2.0.7
Cython                        0.29.36
dataclasses                   0.6
datasets                      2.13.0
ddpm-guided-diffusion         0.0.0
debugpy                       1.6.7
decorator                     4.4.2
decord                        0.6.0
deepspeed                     0.10.0
defusedxml                    0.7.1
descartes                     1.1.0
detectron2                    0.6
dgl                           1.1.1+cu117
diffusers                     0.29.0
dill                          0.3.6
Distance                      0.1.3
distlib                       0.3.7
dnspython                     2.4.1
dropout-layer-norm            0.1
easydict                      1.10
easyrobust                    0.2.4
edit-distance                 1.0.6
editdistance                  0.6.2
einops                        0.6.1
embeddings                    0.0.8
emoji                         2.7.0
en-core-web-sm                3.4.0
espnet-tts-frontend           0.0.3
et-xmlfile                    1.1.0
eventlet                      0.33.3
exceptiongroup                1.1.2
executing                     1.2.0
expecttest                    0.1.5
face-alignment                1.4.0
fairscale                     0.4.13
fairseq                       0.12.2
faiss                         1.7.2
fastai                        2.7.12
fastapi                       0.115.5
fastcore                      1.5.29
fastdownload                  0.0.7
fastjsonschema                2.18.0
fastprogress                  1.0.3
fasttext                      0.9.2
ffmpeg                        1.4
ffmpeg-python                 0.2.0
ffmpy                         0.4.0
filelock                      3.12.2
fire                          0.5.0
flake8                        6.1.0
flash-attn                    1.0.8
Flask                         2.1.3
Flask-Cors                    4.0.0
Flask-RESTful                 0.3.10
Flask-SocketIO                4.3.2
flask-talisman                1.0.0
flatbuffers                   23.5.26
fonttools                     4.41.1
fqdn                          1.5.1
frozenlist                    1.4.0
fsspec                        2023.6.0
ftfy                          6.1.1
funasr                        0.7.1
funtextprocessing             0.1.1
future                        0.18.3
fvcore                        0.1.5.post20221221
g2p                           1.1.20230511
g2p-en                        2.1.0
gast                          0.3.3
google-auth                   2.22.0
google-auth-oauthlib          1.0.0
google-pasta                  0.2.0
gradio                        3.47.1
gradio_client                 0.6.0
greenlet                      2.0.2
grpcio                        1.56.2
h11                           0.14.0
h5py                          2.10.0
hdbscan                       0.8.33
healpy                        1.16.3
hjson                         3.1.0
httpcore                      1.0.7
httpx                         0.27.2
huggingface-hub               0.26.2
humanfriendly                 10.0
hydra-core                    1.3.2
HyperPyYAML                   1.2.1
identify                      2.5.26
idna                          3.4
imageio                       2.31.1
imageio-ffmpeg                0.4.8
imgaug                        0.4.0
importlib-metadata            6.8.0
importlib-resources           6.0.0
inflect                       7.0.0
iniconfig                     2.0.0
iopath                        0.1.9
ipdb                          0.13.13
ipykernel                     6.25.0
ipython                       8.12.2
ipython-genutils              0.2.0
ipywidgets                    8.0.7
isoduration                   20.11.0
isort                         5.12.0
itsdangerous                  2.1.2
jaconv                        0.3.4
jamo                          0.4.1
jedi                          0.18.2
jieba                         0.42.1
Jinja2                        3.1.2
jmespath                      0.10.0
joblib                        1.3.1
json-tricks                   3.17.2
json5                         0.9.14
jsonpatch                     1.32
jsonplus                      0.8.0
jsonpointer                   2.1
jsonschema                    4.18.4
jsonschema-specifications     2023.7.1
jupyter                       1.0.0
jupyter_client                8.3.0
jupyter-console               6.6.3
jupyter_core                  5.3.1
jupyter-events                0.7.0
jupyter-lsp                   2.2.0
jupyter_server                2.7.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.3
jupyterlab-pygments           0.2.2
jupyterlab_server             2.24.0
jupyterlab-widgets            3.0.8
kaldiio                       2.18.0
kantts                        1.0.1
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.4
kornia                        0.6.12
kwsbp                         0.0.6
langcodes                     3.3.0
lap                           0.4.0
librosa                       0.9.2
lightning-utilities           0.9.0
lit                           16.0.6
llvmlite                      0.40.1
lmdb                          1.4.1
lpips                         0.1.4
lxml                          4.9.3
lyft-dataset-sdk              0.0.8
Markdown                      3.4.3
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.5.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
megatron-util                 1.3.2
MinDAEC                       0.0.2
mir-eval                      0.7
mistune                       3.0.1
ml-collections                0.1.1
mmcls                         0.25.0
mmcv-full                     1.7.0
mmdet                         2.28.2
mmdet3d                       1.0.0a1
mmsegmentation                0.30.0
mock                          5.1.0
modelscope                    1.8.1
moviepy                       1.0.3
mpi4py                        3.1.4
mpmath                        1.3.0
msgpack                       1.0.5
multidict                     6.0.4
multiprocess                  0.70.14
MultiScaleDeformableAttention 1.0
munkres                       1.1.4
murmurhash                    1.0.9
mypy-extensions               1.0.0
narwhals                      1.14.1
nbclient                      0.8.0
nbconvert                     7.7.3
nbformat                      5.9.2
nerfacc                       0.2.2
nest-asyncio                  1.5.7
networkx                      2.8.4
ninja                         1.11.1
nltk                          3.8.1
nodeenv                       1.8.0
notebook                      7.0.1
notebook_shim                 0.2.3
numba                         0.57.1
numpy                         1.22.0
nuscenes-devkit               1.1.10
nvdiffrast                    0.3.1
oauthlib                      3.2.2
omegaconf                     2.3.0
onnx                          1.14.0
onnxruntime                   1.15.1
onnxsim                       0.4.33
open-clip-torch               2.20.0
opencv-python                 4.8.0.74
opencv-python-headless        4.8.0.74
openpyxl                      3.1.2
opt-einsum                    3.3.0
orjson                        3.10.11
oss2                          2.18.1
overrides                     7.3.1
packaging                     23.0
pai-easycv                    0.11.2
paint-ldm                     0.0.0
pandas                        1.3.5
pandocfilters                 1.5.0
panopticapi                   0.1
panphon                       0.20.0
parso                         0.8.3
pathspec                      0.11.2
pathy                         0.10.2
peft                          0.11.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.0.0
pip                           23.2.1
pkgutil_resolve_name          1.3.10
platformdirs                  3.9.1
plotly                        5.15.0
pluggy                        1.0.0
plyfile                       1.0.1
pointnet2                     0.0.0
pooch                         1.7.0
portalocker                   2.7.0
pre-commit                    3.3.3
preshed                       3.0.8
prettytable                   3.8.0
proglog                       0.1.10
prometheus-client             0.17.1
prompt-toolkit                3.0.39
protobuf                      3.20.0
psutil                        5.9.5
ptflops                       0.7
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
py-sound-connect              0.2.1
pyarrow                       12.0.1
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pybind11                      2.11.1
pyclipper                     1.3.0.post4
pycocoevalcap                 1.2
pycocotools                   2.0.6
pycodestyle                   2.11.0
pycosat                       0.6.4
pycparser                     2.21
pycryptodome                  3.18.0
pycryptodomex                 3.18.0
pydantic                      1.10.12
pydantic_core                 2.4.0
pyDeprecate                   0.3.2
pydot                         1.4.2
pydub                         0.25.1
pyerfa                        2.0.0.3
pyflakes                      3.1.0
Pygments                      2.15.1
PyMCubes                      0.1.4
pynini                        2.1.5
pynndescent                   0.5.10
pyOpenSSL                     23.0.0
pyparsing                     3.0.9
pypinyin                      0.49.0
pyquaternion                  0.9.9
PySocks                       1.7.1
pysptk                        0.1.18
pytest                        7.4.0
pythainlp                     4.0.2
python-crfsuite               0.9.9
python-dateutil               2.8.2
python-engineio               3.14.2
python-json-logger            2.0.7
python-multipart              0.0.17
python-slugify                8.0.4
python-socketio               4.6.1
pytorch-lightning             1.7.7
pytorch-metric-learning       2.3.0
pytorch-wavelets              1.3.0
pytorch-wpe                   0.0.1
pytorch3d                     0.7.4
pytz                          2023.3
pyvi                          0.1.1
PyWavelets                    1.4.1
PyYAML                        6.0.1
pyzmq                         25.1.0
qtconsole                     5.4.3
QtPy                          2.3.1
qudida                        0.0.4
rapidfuzz                     3.1.2
referencing                   0.30.0
regex                         2023.6.3
requests                      2.29.0
requests-oauthlib             1.3.1
resampy                       0.4.2
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.5.1
rotary-emb                    0.1
rotary-embedding-torch        0.2.5
rouge                         1.0.1
rouge-score                   0.0.4
rpds-py                       0.9.2
rsa                           4.9
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
s3transfer                    0.6.1
sacrebleu                     2.3.1
sacremoses                    0.0.53
safetensors                   0.3.1
scikit-image                  0.19.3
scikit-learn                  1.3.0
scipy                         1.10.1
seaborn                       0.12.2
semantic-version              2.10.0
Send2Trash                    1.8.2
sentencepiece                 0.1.99
seqeval                       1.2.2
setuptools                    67.8.0
Shapely                       1.8.5
shotdetect-scenedetect-lgss   0.0.4
simplejson                    3.19.1
six                           1.16.0
sklearn-crfsuite              0.3.6
smart-open                    6.3.0
smplx                         0.1.28
sniffio                       1.3.0
sortedcontainers              2.4.0
soundfile                     0.12.1
soupsieve                     2.4.1
sox                           1.4.1
spacy                         3.4.4
spacy-legacy                  3.0.12
spacy-loggers                 1.0.4
speechbrain                   0.5.15
srsly                         2.4.7
stack-data                    0.6.2
stanza                        1.5.0
starlette                     0.41.3
subword-nmt                   0.3.8
sympy                         1.12
tabulate                      0.9.0
taming-transformers-rom1504   0.0.6
tb-nightly                    2.14.0a20230801
tenacity                      8.2.2
tensorboard                   2.13.0
tensorboard-data-server       0.7.1
tensorboardX                  2.6.1
tensorflow                    1.15.5+cu113
tensorflow-estimator          1.15.1
termcolor                     2.3.0
terminado                     0.17.1
terminaltables                3.1.10
text-unidecode                1.3
text2sql-lgesql               1.3.0
TextGrid                      1.5
tf-slim                       1.1.0
thinc                         8.1.10
thop                          0.1.1.post2209072238
threadpoolctl                 3.2.0
tifffile                      2023.7.10
tiktoken                      0.4.0
timm                          0.5.4
tinycss2                      1.2.1
tinycudann                    1.6
tokenizers                    0.13.3
tomli                         2.0.1
toolz                         0.12.0
torch                         2.0.1+cu117
torch-complex                 0.4.3
torch-scatter                 2.1.1
torchaudio                    2.0.2+cu117
torchmetrics                  0.11.4
torchsummary                  1.5.1
torchvision                   0.15.2+cu117
tornado                       6.3.2
tqdm                          4.65.0
traitlets                     5.9.0
transformers                  4.30.2
trimesh                       2.35.39
triton                        2.0.0
ttsfrd                        0.2.1
typeguard                     2.13.3
typer                         0.7.0
typing                        3.7.4.3
typing_extensions             4.12.2
ujson                         5.8.0
umap-learn                    0.5.3
unicodecsv                    0.14.1
unicodedata2                  15.0.0
unicore                       0.0.1
Unidecode                     1.3.6
uri-template                  1.3.0
urllib3                       1.26.16
utils                         1.0.1
uvicorn                       0.32.1
videofeatures-clipit          1.0
virtualenv                    20.24.2
wasabi                        0.10.1
wcwidth                       0.2.6
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.6.1
websockets                    11.0.3
wenetruntime                  1.11.0
Werkzeug                      2.0.3
wget                          3.2
wheel                         0.38.4
widgetsnbextension            4.0.8
wrapt                         1.15.0
xtcocotools                   1.13
xxhash                        3.3.0
yacs                          0.1.8
yapf                          0.30.0
yarl                          1.9.2
zhconv                        1.4.3
zipp                          3.16.2
