### ISSUE TITLE
Question about TopoFR (misalignment of paper and code implementation) ?

### ISSUE THREAD

**Issue by Bear-kai** [modelscope/facechain#626]
I just scaned the code snippet for helping better understanding the paper. And (maybe) I found two issues:

1.  The input `img` of `compute_topological_loss()` is actually the augmented version, since `img_randomaug = img` ([link](https://github.com/modelscope/facechain/blob/7864aee7fb25e3f5e7d35dec64f379fee4ddd544/face_module/TopoFR/train.py#L157)) is not a deep copy, resulting the simultaneous modifaction to `img` when modifing `img_randomaug`.
2. In GUM.py, the [computation](https://github.com/modelscope/facechain/blob/7864aee7fb25e3f5e7d35dec64f379fee4ddd544/face_module/TopoFR/GUM.py#L48) is different from Eq.(7) in the paper.

Moreover, in the Appendix A.1:

> Notably, in our method, we focus on preserving the 0-dimension homology H0 in the topological structure alignment loss Lsa. Because preliminary experiments demonstrated that using the 1-dimension or higher-dimension homology only increases model’s training time without clear performance gains. 

How do you experimented with H1 or higher-dimension homology?  The released `topology.py` only supports H0.

**Comment by sunbaigui** [comment]
hi @DanJun6737 ,Please take a look at this when you get a chance.
