### ISSUE TITLE
模型文件格式问题，大家有遇到吗

### ISSUE THREAD

**Issue by LU-V** [modelscope/facechain#64]
生成模型时是.safetensors文件：
![89db7b829f71e2cce569afae3f33800](https://github.com/modelscope/facechain/assets/38043478/5b47d61e-7c07-435f-9330-08ba264fe2b4)

使用模型时使用的是 .bin文件：
![eddba413ec7d071b1f372d59727346e](https://github.com/modelscope/facechain/assets/38043478/1e61c30b-3ef7-4988-b057-962ea0a2eca5)

**Comment by sunbaigui** [comment]
合并issue到https://github.com/modelscope/facechain/issues/46
