### ISSUE TITLE
Could not find a version that satisfies the requirement tf-estimator-nightly==2.8.0.dev2021122109

### ISSUE THREAD

**Issue by wang-xin-yuan-001** [modelscope/facechain#66]
2.8.0的tensorflow好像有问题，python的3.8可以下载这个包吗？
INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 3.8.0rc1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement tf-estimator-nightly==2.8.0.dev2021122109 (from tensorflow) (from versions: none)
ERROR: No matching distribution found for tf-estimator-nightly==2.8.0.dev2021122109

**Comment by wangxingjun778** [comment]
> 2.8.0的tensorflow好像有问题，python的3.8可以下载这个包吗？ INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while. ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 3.8.0rc1 Requires-Python >=3.9 ERROR: Could not find a version that satisfies the requirement tf-estimator-nightly==2.8.0.dev2021122109 (from tensorflow) (from versions: none) ERROR: No matching distribution found for tf-estimator-nightly==2.8.0.dev2021122109

py3.8 环境测试下来是可以支持tf2.8.0的，可参考pypi的版本兼容说明： https://pypi.org/project/tensorflow-gpu/2.8.0/

如果本环境的tf gpu安装有问题，可尝试安装tensorflow-cpu，facechain亦兼容tf cpu版本，可参考：https://github.com/modelscope/facechain/blob/main/requirements.txt

**Comment by gpww** [comment]
遇到一样的问题：
25.59 INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
25.59 ERROR: Could not find a version that satisfies the requirement tf-estimator-nightly==2.8.0.dev2021122109 (from tensorflow) (from versions: none)
25.59 ERROR: No matching distribution found for tf-estimator-nightly==2.8.0.dev2021122109

**Comment by sunbaigui** [comment]
I find those two videos outside, hope it will solve your problem.
1.) ubuntu reference: 【facechain本地Linux系统部署详细教程（ubuntu)-哔哩哔哩】 https://b23.tv/40lkyM0 .
2.) windows reference: 【"妙鸭相机"开源版facechain本地部署详细教程（windows系统）-哔哩哔哩】 https://b23.tv/EeL2iwB .
