### ISSUE TITLE
使用windows11反复尝试修改已经可以跑起来，到形象体验->开始生成报错，实在没找到原因，还是请帮忙确认下，这个错误是否可以定位到问题？

### ISSUE THREAD

**Issue by Puwong** [modelscope/facechain#75]
windows11
python3.8
CUDA 11.7
GPU GeForce RTX 4060

与readme中环境的差异：
1、mmcv-full==1.7.0 报错，nms_impl: implementation for device cuda:0 not found. 反复卸载重装依旧报错，改用1.7.1后成功。
到形象体验->开始生成报错：
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\facechain\\tmp/qw/personalizaition_lora\\pytorch_lora_weights.bin'

**Comment by Puwong** [comment]
看来并不是这个错误这么简单，我修改了运行python的部分，应该是模型文件根本没有生成。
2023-08-20 19:07:36,695 - modelscope - INFO - Loading done! Current index file version is 1.8.3, with md5 4a973db6e60a17966a0cb2f4bdc05d45 and a total number of 895 components indexed
Traceback (most recent call last):
  File "facechain/train_text_to_image_lora.py", line 56, in <module>
    from facechain.inference import data_process_fn
ModuleNotFoundError: No module named 'facechain'
训练已经完成！请切换至 [形象体验] 标签体验模型效果(Training done, please switch to the inference tab to generate photos.)

**Comment by sunbaigui** [comment]
windows的官方支持目前工程侧正在整理当中。请稍等。

**Comment by ultimatech-cn** [comment]
检查diffusers的版本，如果是0.20，降到0.19试试。
我今天就是这么解决的。

**Comment by Puwong** [comment]
这个我尝试了一下，还是和之前一样报错，我改过路径，包括python运行的虚拟环境路径，你能跑成还是蛮厉害的，估计我哪里还有问题。

等待官方反馈看什么时候能把win支持的好一些。
