### ISSUE TITLE
Error when training data

### ISSUE THREAD

**Issue by mafamily2496** [modelscope/facechain#76]
在windows11下运行app.py出现这个错误：'PYTHONPATH' 不是内部或外部命令，也不是可运行的程序

**Comment by ultimatech-cn** [comment]
可以看一下kigner的分支，里面有个app-win10.py.

**Comment by hemath1001** [comment]
> 可以看一下kigner的分支，里面有个app-win10.py.

这个分支现在是不是没有了？
