### ISSUE TITLE
模型如何直接本地加载，代码中默认下载地址是哪里？

### ISSUE THREAD

**Issue by yinjianjie** [modelscope/facechain#78]
局限于模型下载的速度和效率太慢

**Comment by tastelikefeet** [comment]
可以使用：
```python
from modelscope import snapshot_download
snapshot_download('some-model-id')
```
之后运行时不会重复下载模型了

**Comment by 66li** [comment]
如果容器化的话怎么配置呢，比如我只对/data/的数据做持久化，怎么让所有的模型都放到/data呢

**Comment by yingdachen** [comment]
> 如果容器化的话怎么配置呢，比如我只对/data/的数据做持久化，怎么让所有的模型都放到/data呢

配置MODELSCOPE_CACHE环境变量即可

**Comment by 66li** [comment]
MODELSCOPE_CACHE中也会有第一次用图片训练出来的产品吗

**Comment by 66li** [comment]
就是人脸LoRA模型

**Comment by yinjianjie** [comment]
模型手动下载后，应该放在哪个目录下，发现还是会重新下载

**Comment by sunbaigui** [comment]
we'll work on it, thanks for your advise and suggestion.

**Comment by GeneLiuXe** [comment]
Same problem, need a tutorial for downloading models manually.

**Comment by sunbaigui** [comment]
> Same problem, need a tutorial for downloading models manually.

@wangxingjun778 please check this out and reply it once you have a time :)

**Comment by livehl** [comment]
env MODELSCOPE_CACHE=/mnt/workspace/.cache/modelscope

**Comment by xyxxmb** [comment]
人脸识别模型：damo/cv_ir_face-recognition-ood_rts 需要依赖人脸检测模型：damo/cv_ddsar_face-detection_iclr23-damofd，我把人脸识别模型下载好了并修改成本地路径 /home/xxx/xxxx，也想修改人脸检测模型的本地路径，我应该怎么在外层指定这个检测模型的本地路径？

**Comment by sunbaigui** [comment]
> 人脸识别模型：damo/cv_ir_face-recognition-ood_rts 需要依赖人脸检测模型：damo/cv_ddsar_face-detection_iclr23-damofd，我把人脸识别模型下载好了并修改成本地路径 /home/xxx/xxxx，也想修改人脸检测模型的本地路径，我应该怎么在外层指定这个检测模型的本地路径？

we will set this a new feature. currently we can not support this.
