### ISSUE TITLE
修改prompt导致生成失败

### ISSUE THREAD

**Issue by Lemonnn7** [modelscope/facechain#79]
我将upper_body修改为full body，结果生成图片失败，请问这是什么原因导致的？

**Comment by sunbaigui** [comment]
prompt目前建议只做一些衣服的修改。内测也发现了prompt完全自定义的话结果不稳定。后续我们也会集思广益出更点经典稳定的prompt给到大家。也会出相应教学视频，如何修改prompt能出稳定的效果会有些规则。
