### ISSUE TITLE
Running on local URL:  http://127.0.0.1:7860

### ISSUE THREAD

**Issue by shengzewen** [modelscope/facechain#80]
想问下这个本地的URL是在哪里设置的，我想设置其他的端口号

**Comment by 66li** [comment]
GRADIO_SERVER_PORT=7890
这个环境变量设置在程序的运行环境就行
url是这个环境变量
GRADIO_SERVER_NAME

**Comment by shengzewen** [comment]
> GRADIO_SERVER_PORT=7890 这个环境变量设置在程序的运行环境就行 url是这个环境变量 GRADIO_SERVER_NAME

感谢，设置成功了
