### ISSUE TITLE
你们好多好多的问题啊，都跑我邮箱里来了 ：（ 去魔塔社区吧，一了百了

### ISSUE THREAD

**Issue by jjiikkkk** [modelscope/facechain#86]
这里的代码大概率是有点问题的

**Comment by sunbaigui** [comment]
有疑问的小伙伴可以发邮件到sunbaigui85@126.com。或者加答疑群：酷蛙FaceChain开源项目2群。

**Comment by aetherwu** [comment]
> 有疑问的小伙伴可以发邮件到[sunbaigui85@126.com](mailto:sunbaigui85@126.com)。或者加答疑群：酷蛙FaceChain开源项目2群。

这里就是最好的社区。
