### ISSUE TITLE
炼丹的一些疑问

### ISSUE THREAD

**Issue by chuck-ma** [modelscope/facechain#87]
1. 不使用 换脸模型，只使用lora，得到的结果和本人相差甚远。使用的照片为多角度自拍照，10张作用。看起来炼丹效果很随机，结果主要是靠换脸模型保证出图相似度？

**Comment by sunbaigui** [comment]
主要搭配使用。lora是脸型与大致五官。最后换是精细五官。由于参数空间有限，目前图片张数不是越多越好，3张左右比较好。正在开发更稳定的训练中。

**Comment by chuck-ma** [comment]
![image](https://github.com/modelscope/facechain/assets/74402255/5700822e-9944-439a-9f06-36f631c8532f)
https://github.com/cloneofsimo/lora/discussions/37

我看 sd 1.5 ，只是使用 lora，就可以达到很好的相似度。不过，我自己的lora实验里也没有达到这么好的训练效果，也不确定这种相似度效果是随机的巧合还是可以通过工程手段复现的。 参数空间有限，是指 lora文件的体积有限吗？

**Comment by h3clikejava** [comment]
> ![image](https://user-images.githubusercontent.com/74402255/262204168-5700822e-9944-439a-9f06-36f631c8532f.png) [cloneofsimo/lora#37](https://github.com/cloneofsimo/lora/discussions/37)
> 
> 我看 sd 1.5 ，只是使用 lora，就可以达到很好的相似度。不过，我自己的lora实验里也没有达到这么好的训练效果，也不确定这种相似度效果是随机的巧合还是可以通过工程手段复现的。 参数空间有限，是指 lora文件的体积有限吗？

我可以炼出相似度较高的LoRA，目前遇到的问题是多个LoRA叠加后会导致相似度迅速下降。例如真人LoRA + 卡通风格LoRA就会要么不像真人，要么不够卡通。你有什么建议吗？

**Comment by chuck-ma** [comment]
@h3clikejava 你炼出较高相似度的 lora是可以稳定复现的吗？工程上，只要保证样品数据没问题？
可以使用 sd xl作为模型底座训练lora，这样只需要 真人lora就行了
