### ISSUE TITLE
python3 app.py 后没有任何输出

### ISSUE THREAD

**Issue by gang-liu** [modelscope/facechain#88]
![image-20230822070451190](https://github.com/modelscope/facechain/assets/8311718/ebaf7237-19fd-4cdc-98f6-0bac006c69a5)
如题

**Comment by sunbaigui** [comment]
有没有127.0.0.1的链接输出。

**Comment by sunbaigui** [comment]
辛苦截图运行后的log。

**Comment by xllusion-dong** [comment]
windows环境直接用python命令
python app.py
另外app.py在windows上需要做小的改动。可以试试kinder的app-wen10.py

**Comment by gang-liu** [comment]
可以用python app.py又会出现下面的问题。已经安装markupsafe也是如此。
![image-20230822075233952](https://github.com/modelscope/facechain/assets/8311718/f929e0d3-c5b8-40f4-903f-ddc57943fc65)

**Comment by ultimatech-cn** [comment]
应该是路径的问题，你可以尝试改代码把文件路径打出来，看对不对。
或者直接用
kinder分支的app-win10.py

**Comment by yingdachen** [comment]
can you push your kinder branch so that we can take a look at your app-win.py?

**Comment by sunbaigui** [comment]
I find those two videos outside, hope it will solve your problem.
1.) ubuntu reference: 【facechain本地Linux系统部署详细教程（ubuntu)-哔哩哔哩】 https://b23.tv/40lkyM0 .
2.) windows reference: 【"妙鸭相机"开源版facechain本地部署详细教程（windows系统）-哔哩哔哩】 https://b23.tv/EeL2iwB .

I'll close this issue temporally, feel free to reopen it if you have any further questions.
