### ISSUE TITLE
ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'>

### ISSUE THREAD

**Issue by applech666** [modelscope/facechain#93]
2023-08-22 10:40:03,479 - modelscope - INFO - Use user-specified model revision: v2.0
2023-08-22 10:40:03,567 - modelscope - INFO - Use user-specified model revision: v2.0
2023-08-22 10:40:03,577 - modelscope - INFO - Use user-specified model revision: v2.0
2023-08-22 10:40:03,580 - modelscope - INFO - Use user-specified model revision: v2.0
The config attributes {'timestep_spacing': 'leading'} were passed to DDPMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
{'clip_sample_range', 'thresholding', 'variance_type', 'dynamic_thresholding_ratio', 'sample_max_value'} was not found in config. Values will be initialized to default values.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/data/projects/cp2023/facechain/facechain/train_text_to_image_lora.py:1103 in <module>       │
│                                                                                                  │
│   1100                                                                                           │
│   1101                                                                                           │
│   1102 if __name__ == "__main__":                                                                │
│ ❱ 1103 │   main()                                                                                │
│   1104                                                                                           │
│                                                                                                  │
│ /mnt/data/projects/cp2023/facechain/facechain/train_text_to_image_lora.py:556 in main            │
│                                                                                                  │
│    553 │   text_encoder = CLIPTextModel.from_pretrained(                                         │
│    554 │   │   model_dir, subfolder="text_encoder"                                               │
│    555 │   )                                                                                     │
│ ❱  556 │   vae = AutoencoderKL.from_pretrained(model_dir, subfolder="vae")                       │
│    557 │   unet = UNet2DConditionModel.from_pretrained(                                          │
│    558 │   │   model_dir, subfolder="unet"                                                       │
│    559 │   )                                                                                     │
│                                                                                                  │
│ /home/research/anaconda3/envs/sdwebui/lib/python3.10/site-packages/diffusers/models/modeling_uti │
│ ls.py:561 in from_pretrained                                                                     │
│                                                                                                  │
│   558 │   │   │   │   │   # move the params from meta device to cpu                              │
│   559 │   │   │   │   │   missing_keys = set(model.state_dict().keys()) - set(state_dict.keys(   │
│   560 │   │   │   │   │   if len(missing_keys) > 0:                                              │
│ ❱ 561 │   │   │   │   │   │   raise ValueError(                                                  │
│   562 │   │   │   │   │   │   │   f"Cannot load {cls} from {pretrained_model_name_or_path} bec   │
│   563 │   │   │   │   │   │   │   f" missing: \n {', '.join(missing_keys)}. \n Please make sur   │
│   564 │   │   │   │   │   │   │   " `low_cpu_mem_usage=False` and `device_map=None` if you wan   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Cannot load <class 'diffusers.models.autoencoder_kl.AutoencoderKL'> from /home/research/.cache/modelscope/hub/ly261666/cv_portrait_model/film/film because the following keys are missing: 
 encoder.mid_block.attentions.0.value.weight, decoder.mid_block.attentions.0.value.weight, encoder.mid_block.attentions.0.value.bias, decoder.mid_block.attentions.0.query.bias, encoder.mid_block.attentions.0.query.bias, 
decoder.mid_block.attentions.0.value.bias, encoder.mid_block.attentions.0.proj_attn.weight, encoder.mid_block.attentions.0.key.weight, decoder.mid_block.attentions.0.key.bias, decoder.mid_block.attentions.0.key.weight, 
decoder.mid_block.attentions.0.proj_attn.weight, decoder.mid_block.attentions.0.query.weight, encoder.mid_block.attentions.0.key.bias, encoder.mid_block.attentions.0.proj_attn.bias, 
decoder.mid_block.attentions.0.proj_attn.bias, encoder.mid_block.attentions.0.query.weight. 
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

**Comment by sunbaigui** [comment]
hi, if you can supply more details about your system and environment, it will help us to reproduce this problem.

**Comment by applech666** [comment]
thanks, I have solved it.
vae = AutoencoderKL.from_pretrained(model_dir, subfolder="vae") 
==>vae = AutoencoderKL.from_pretrained(model_dir, subfolder="vae", low_cpu_mem_usage=False, device_map=None)
